import type { ListingCard as _ListingCardBase } from "../backend.d";

// Re-export all backend types
export type {
  AuditEntry,
  AuditFilter,
  CarrierInfo,
  ComplianceNote,
  DisputeResolution,
  DisputeView,
  Error_,
  Feedback,
  Message,
  Page,
  PagedResult,
  PagedResult_1,
  PlatformMetrics,
  ReputationStats,
  ShippingMethod,
  TokenInfo,
  TradePaymentStatus,
  TradeView,
  TxHistoryFilter,
  UserFilter,
  UserProfile,
} from "../backend.d";

/**
 * Extended ListingCard — adds `description` and `digitalFileUrl` fields
 * exposed by the backend since v46. The generated backend.d.ts is
 * regenerated by the platform on deploy; until then we augment here.
 */
export interface ListingCard extends _ListingCardBase {
  description: string;
  digitalFileUrl: string;
  categoryId: bigint;
  categorySlug: string;
  isPromoted: boolean;
}

export {
  DisputeReason,
  DisputeStatus,
  ItemCondition,
  ListingCategory,
  ResolutionOutcome,
  ShippingCarrier,
  ShippingServiceType,
  TradeStatus,
  TradeToken,
  TrustLevel,
  UserRole,
  Variant_all_seller_buyer,
} from "../backend.d";

export type {
  ListingId,
  TradeId,
  DisputeId,
  FeedbackId,
  MessageId,
  UserId,
  Timestamp,
} from "../backend.d";

// ─── UI-specific types ───────────────────────────────────────────────────────

export interface PageParams {
  page: number;
  pageSize: number;
}

export interface FilterState {
  query?: string;
  category?: string;
  priceMin?: bigint;
  priceMax?: bigint;
  location?: string;
  condition?: string;
  shippingCarrier?: string;
}

export type TradeStatusLabel =
  | "Pending"
  | "Funded"
  | "Buyer Confirmed"
  | "Complete"
  | "Refunded"
  | "Disputed"
  | "Cancelled";

export type TrustLevelBadge = {
  level: "new" | "bronze" | "silver" | "gold";
  label: string;
  color: string;
};

export type NavItem = {
  label: string;
  to: string;
  icon: string;
};
