/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddressVerification {
  'active' : boolean,
  'expiresAt' : Timestamp,
  'level' : bigint,
  'txCount' : bigint,
  'verifiedAt' : Timestamp,
}
export interface AuditEntry {
  'id' : bigint,
  'action' : string,
  'actorId' : Principal,
  'timestamp' : Timestamp,
  'details' : string,
  'targetId' : [] | [string],
}
export interface AuditFilter {
  'targetFilter' : [] | [string],
  'actionFilter' : [] | [string],
  'actorFilter' : [] | [Principal],
}
export interface BalanceView {
  'chain' : ChainType,
  'error' : [] | [string],
  'usdtBalance' : bigint,
  'usdcBalance' : bigint,
  'lastChecked' : bigint,
}
export interface CarrierInfo {
  'displayName' : string,
  'description' : string,
  'carrier' : ShippingCarrier,
}
export type CategoryId = bigint;
export interface CategoryNode {
  'id' : CategoryId,
  'labelEn' : string,
  'labelUk' : string,
  'slug' : string,
  'legacyCategory' : ListingCategory,
  'parentId' : [] | [CategoryId],
}
export type ChainType = { 'SPL' : null } |
  { 'BEP20' : null } |
  { 'TRC20' : null } |
  { 'Polygon' : null } |
  { 'ERC20' : null } |
  { 'Avalanche' : null };
export interface ComplianceNote {
  'id' : bigint,
  'note' : string,
  'actorId' : Principal,
  'timestamp' : Timestamp,
}
export interface CreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface CyclesStatus {
  'isWarning' : boolean,
  'currentBalance' : bigint,
  'warningThreshold' : bigint,
  'estimatedDailyBurn' : bigint,
}
export interface DigitalDelivery {
  'inspectionDeadline' : [] | [Timestamp],
  'password' : [] | [string],
  'fileHash' : [] | [string],
  'revealedAt' : [] | [Timestamp],
  'fileUrl' : string,
}
export type DisputeId = bigint;
export type DisputeReason = { 'other' : null } |
  { 'item_damaged' : null } |
  { 'seller_unresponsive' : null } |
  { 'item_differs' : null } |
  { 'item_not_received' : null };
export interface DisputeResolution {
  'notes' : string,
  'outcome' : ResolutionOutcome,
  'resolvedBy' : UserId,
}
export type DisputeStatus = { 'resolved' : null } |
  { 'opened' : null } |
  { 'escalated_to_admin' : null } |
  { 'under_review' : null };
export interface DisputeView {
  'id' : DisputeId,
  'evidenceUrls' : Array<string>,
  'status' : DisputeStatus,
  'trade' : TradeId,
  'evidenceAttachments' : Array<MediaAttachment>,
  'initiator' : UserId,
  'jury' : [] | [JuryView],
  'createdAt' : Timestamp,
  'description' : string,
  'resolution' : [] | [DisputeResolution],
  'moderatorNotes' : Array<string>,
  'resolvedAt' : [] | [Timestamp],
  'reason' : DisputeReason,
}
export type Error = { 'insufficient_funds' : null } |
  { 'rate_limited' : null } |
  { 'dispute_already_open' : null } |
  { 'not_found' : null } |
  { 'banned' : null } |
  { 'invalid_input' : string } |
  { 'escrow_error' : string } |
  { 'already_exists' : null } |
  { 'unauthorized' : null };
export interface ErrorLogEntry {
  'id' : bigint,
  'functionName' : string,
  'moduleName' : string,
  'errorMessage' : string,
  'userPrincipal' : [] | [Principal],
  'timestamp' : bigint,
  'severity' : ErrorSeverity,
}
export type ErrorSeverity = { 'warning' : null } |
  { 'info' : null } |
  { 'error' : null } |
  { 'critical' : null };
export interface EscrowAccount {
  'fee' : bigint,
  'sellerPrincipal' : UserId,
  'token' : TradeToken,
  'ledgerCanisterId' : Principal,
  'deadline' : Timestamp,
  'tradeId' : TradeId,
  'lockedAt' : Timestamp,
  'buyerPrincipal' : UserId,
  'amount' : bigint,
}
export interface Feedback {
  'id' : FeedbackId,
  'trade' : TradeId,
  'createdAt' : Timestamp,
  'comment' : string,
  'rating' : bigint,
  'reviewed' : UserId,
  'reviewer' : UserId,
}
export type FeedbackId = bigint;
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpResponse {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type ItemCondition = { 'new' : null } |
  { 'fair' : null } |
  { 'good' : null } |
  { 'poor' : null } |
  { 'likeNew' : null };
export interface JurorDashboardEntry {
  'deadline' : Timestamp,
  'tradeId' : TradeId,
  'sellerVotes' : bigint,
  'hasVoted' : boolean,
  'totalJurors' : bigint,
  'buyerVotes' : bigint,
  'reason' : DisputeReason,
  'disputeId' : DisputeId,
}
export interface JurorStats {
  'principal' : Principal,
  'successRate' : number,
  'activeCount' : bigint,
  'stakedAmount' : number,
  'registeredAt' : Timestamp,
  'resolvedCount' : bigint,
}
export interface JurorVote {
  'vote' : JurorVoteChoice,
  'reasoning' : string,
  'timestamp' : bigint,
  'jurorPrincipal' : Principal,
}
export type JurorVoteChoice = { 'sellerWins' : null } |
  { 'buyerWins' : null };
export interface JuryView {
  'jurors' : Array<Principal>,
  'votes' : Array<JurorVote>,
  'deadline' : Timestamp,
}
export interface LiabilityEvent {
  'tradeId' : [] | [bigint],
  'timestamp' : Timestamp,
  'amount' : bigint,
  'reason' : string,
}
export interface LinkPreview {
  'url' : string,
  'title' : [] | [string],
  'fetchedAt' : Timestamp,
  'description' : [] | [string],
  'siteName' : [] | [string],
  'imageUrl' : [] | [string],
}
export interface ListingCard {
  'id' : ListingId,
  'categoryId' : CategoryId,
  'title' : string,
  'sellerPrincipal' : UserId,
  'priceAmount' : bigint,
  'categorySlug' : string,
  'shippingMethods' : Array<ShippingMethod>,
  'createdAt' : Timestamp,
  'description' : string,
  'sellerTrustLevel' : TrustLevel,
  'isPromoted' : boolean,
  'sellerRating' : bigint,
  'priceToken' : TradeToken,
  'category' : ListingCategory,
  'sellerUsername' : string,
  'location' : string,
  'photos' : Array<string>,
  'digitalFileUrl' : string,
  'condition' : ItemCondition,
}
export type ListingCategory = { 'clothing' : null } |
  { 'other' : null } |
  { 'books' : null } |
  { 'digital' : null } |
  { 'services' : null } |
  { 'electronics' : null };
export type ListingId = bigint;
export type ListingInquiryId = bigint;
export interface ListingInquiryMessage {
  'id' : ListingInquiryMessageId,
  'content' : string,
  'createdAt' : Timestamp,
  'sender' : UserId,
  'inquiryId' : ListingInquiryId,
}
export type ListingInquiryMessageId = bigint;
export interface MediaAttachment {
  'url' : string,
  'mimeType' : string,
  'fileName' : string,
  'fileSize' : bigint,
}
export interface MeestConfig {
  'senderPudoRef' : [] | [string],
  'enabled' : boolean,
  'deliveryTypes' : Array<string>,
}
export interface Message {
  'id' : MessageId,
  'attachmentUrl' : [] | [string],
  'trade' : TradeId,
  'content' : string,
  'sender' : UserId,
  'sentAt' : Timestamp,
  'attachments' : Array<MediaAttachment>,
}
export type MessageId = bigint;
export interface MetricsSummary {
  'totalTrades' : bigint,
  'totalVolume' : bigint,
  'p95LatencyMs' : bigint,
  'errorRate' : number,
  'memoryUsage' : bigint,
  'activeTrades' : bigint,
  'avgTradeValue' : bigint,
  'disputeRate' : number,
  'totalRevenue' : bigint,
  'cyclesBalance' : bigint,
}
export interface ModuleMetricsView {
  'memoryUsedBytes' : bigint,
  'cyclesConsumed' : bigint,
  'moduleName' : string,
  'lastUpdated' : bigint,
  'errorCount' : bigint,
  'requestCount' : bigint,
}
export interface NotificationEvent {
  'id' : bigint,
  'read' : boolean,
  'tradeId' : bigint,
  'message' : string,
  'timestamp' : Timestamp,
  'eventType' : string,
}
export interface NovaPoshtaBranch {
  'ref' : string,
  'cityRef' : string,
  'name' : string,
  'address' : string,
  'schedule' : [] | [string],
}
export interface NovaPoshtaConfig {
  'enabled' : boolean,
  'senderBranchRef' : string,
  'deliveryTypes' : Array<string>,
}
export interface PackageDetails {
  'weight' : bigint,
  'height' : bigint,
  'places' : bigint,
  'length' : bigint,
  'declaredValue' : bigint,
  'width' : bigint,
}
export interface Page {
  'totalCount' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<TradeView>,
}
export interface PagedResult {
  'page' : bigint,
  'totalCount' : bigint,
  'pageSize' : bigint,
  'items' : Array<AuditEntry>,
}
export interface PagedResult_1 {
  'page' : bigint,
  'totalCount' : bigint,
  'pageSize' : bigint,
  'items' : Array<UserProfile>,
}
export interface PaymentMethod {
  'token' : TradeToken,
  'addedAt' : Timestamp,
  'address' : string,
  'verification' : [] | [AddressVerification],
}
export interface PaymentVerificationResult {
  'status' : PaymentVerificationStatus,
  'blockNumber' : bigint,
  'confirmedAmount' : number,
  'confirmedRecipient' : string,
  'txHash' : string,
  'errorReason' : [] | [string],
}
export type PaymentVerificationStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'failed' : null };
export interface PlatformMetrics {
  'totalTrades' : bigint,
  'activeUsersLast30d' : bigint,
  'avgTradeCompletionMs' : bigint,
  'totalListings' : bigint,
  'tradesByToken' : Array<[TradeToken, bigint]>,
  'disputeRatePct' : bigint,
}
export interface PlatformMetrics__1 {
  'totalTrades' : bigint,
  'activeUsersLast24h' : bigint,
  'totalVolume' : number,
  'monthlyActiveUsers' : bigint,
  'completedTrades' : bigint,
  'avgSettlementTimeMin' : number,
  'disputeRate' : number,
  'swapSuccessRate' : number,
}
export type ProposalId = bigint;
export type ProposalStatus = { 'active' : null } |
  { 'expired' : null } |
  { 'rejected' : null } |
  { 'executed' : null } |
  { 'passed' : null };
export type ProposalType = { 'TextResolution' : { 'description' : string } } |
  { 'TreasuryTransfer' : { 'recipient' : Principal, 'amount' : bigint } } |
  { 'ParameterChange' : { 'key' : string, 'value' : string } };
export interface ProposalView {
  'id' : ProposalId,
  'status' : ProposalStatus,
  'noVotes' : bigint,
  'executedAt' : [] | [Timestamp],
  'yesVotes' : bigint,
  'createdAt' : Timestamp,
  'description' : string,
  'deadline' : Timestamp,
  'proposalType' : ProposalType,
  'proposer' : UserId,
  'voterCount' : bigint,
}
export interface RateCacheEntry { 'rateInCents' : bigint, 'fetchedAt' : bigint }
export interface ReputationStats {
  'reputationScore' : bigint,
  'trustLevel' : TrustLevel,
  'averageRating' : number,
  'completedTrades' : bigint,
  'disputeRate' : number,
}
export type ResolutionOutcome = { 'buyer_wins' : null } |
  { 'split' : null } |
  { 'seller_wins' : null };
export type Result = { 'ok' : null } |
  { 'err' : Error };
export type Result_1 = {
    'ok' : { 'active' : boolean, 'txCount' : bigint, 'verifiedAt' : Timestamp }
  } |
  { 'err' : Error };
export type Result_10 = { 'ok' : boolean } |
  { 'err' : Error };
export type Result_11 = { 'ok' : DisputeId } |
  { 'err' : Error };
export type Result_12 = { 'ok' : FeedbackId } |
  { 'err' : Error };
export type Result_13 = { 'ok' : TradeId } |
  { 'err' : Error };
export type Result_14 = {
    'ok' : {
      'status' : string,
      'trackingNumber' : string,
      'estimatedDelivery' : [] | [string],
      'statusHistory' : Array<{ 'status' : string, 'timestamp' : bigint }>,
      'isDelivered' : boolean,
      'carrier' : string,
    }
  } |
  { 'err' : Error };
export type Result_15 = {
    'ok' : Array<{ 'name' : string, 'address' : string, 'index' : string }>
  } |
  { 'err' : Error };
export type Result_16 = { 'ok' : bigint } |
  { 'err' : Error };
export type Result_17 = { 'ok' : Array<DisputeView> } |
  { 'err' : Error };
export type Result_18 = { 'ok' : Array<NovaPoshtaBranch> } |
  { 'err' : Error };
export type Result_19 = { 'ok' : Array<JurorDashboardEntry> } |
  { 'err' : Error };
export type Result_2 = { 'ok' : PaymentVerificationResult } |
  { 'err' : Error };
export type Result_20 = {
    'ok' : Array<
      { 'id' : string, 'name' : string, 'type' : string, 'address' : string }
    >
  } |
  { 'err' : Error };
export type Result_21 = { 'ok' : Array<ListingInquiryMessage> } |
  { 'err' : Error };
export type Result_22 = { 'ok' : LinkPreview } |
  { 'err' : Error };
export type Result_23 = { 'ok' : Array<JurorStats> } |
  { 'err' : Error };
export type Result_24 = { 'ok' : DigitalDelivery } |
  { 'err' : Error };
export type Result_25 = { 'ok' : ProposalId } |
  { 'err' : Error };
export type Result_26 = { 'ok' : ListingCard } |
  { 'err' : Error };
export type Result_27 = { 'ok' : ProposalStatus } |
  { 'err' : Error };
export type Result_28 = { 'ok' : PaymentMethod } |
  { 'err' : Error };
export type Result_5 = { 'ok' : UserProfile } |
  { 'err' : Error };
export type Result_6 = { 'ok' : Message } |
  { 'err' : Error };
export type Result_7 = { 'ok' : ListingInquiryMessage } |
  { 'err' : Error };
export type Result_8 = { 'ok' : SavedSearch } |
  { 'err' : Error };
export type Result_9 = { 'ok' : string } |
  { 'err' : Error };
export interface SavedSearch {
  'id' : SavedSearchId,
  'owner' : UserId,
  'paramsJson' : string,
  'name' : string,
  'createdAt' : Timestamp,
}
export type SavedSearchId = bigint;
export type ShippingCarrier = { 'meest' : null } |
  { 'nova_poshta' : null } |
  { 'self_pickup' : null } |
  { 'digital' : null } |
  { 'ukrposhta' : null };
export interface ShippingMethod {
  'type' : ShippingServiceType,
  'estimatedDays' : bigint,
  'carrier' : ShippingCarrier,
}
export interface ShippingOption {
  'cost' : number,
  'deliveryDays' : bigint,
  'available' : boolean,
  'carrier' : ShippingCarrier,
  'costNat' : bigint,
}
export interface ShippingSelection {
  'provider' : string,
  'branchRef' : [] | [string],
  'cost' : bigint,
  'deliveryType' : string,
  'address' : [] | [string],
}
export type ShippingServiceType = { 'express' : null } |
  { 'standard' : null };
export type TTNStatus = { 'Failed' : null } |
  { 'Success' : null } |
  { 'InProgress' : null } |
  { 'Pending' : null };
export type Timestamp = bigint;
export interface TokenInfo {
  'decimals' : bigint,
  'token' : TradeToken,
  'name' : string,
  'network' : string,
  'isNative' : boolean,
  'priority' : bigint,
  'symbol' : string,
}
export type TradeId = bigint;
export interface TradePaymentStatus {
  'status' : TradeStatus,
  'isManual' : boolean,
  'token' : TradeToken,
  'formattedAmount' : string,
  'tradeId' : TradeId,
  'tokenInfo' : [] | [TokenInfo],
  'amount' : bigint,
  'verificationResult' : [] | [PaymentVerificationResult],
}
export type TradeStatus = { 'payment_verified' : null } |
  { 'cancelled' : null } |
  { 'disputed' : null } |
  { 'pending' : null } |
  { 'refunded' : null } |
  { 'funded' : null } |
  { 'buyer_confirmed' : null } |
  { 'complete' : null } |
  { 'awaiting_approval' : null };
export type TradeToken = { 'USDT_ERC20' : null } |
  { 'USDT_AVAX' : null } |
  { 'USDC_ERC20' : null } |
  { 'USDT_BEP20' : null } |
  { 'USDC_AVAX' : null } |
  { 'ckUSDC' : null } |
  { 'ckUSDT' : null } |
  { 'USDC_SPL' : null } |
  { 'USDT_TRC20' : null } |
  { 'USDC_POLYGON' : null } |
  { 'USDT_POLYGON' : null };
export interface TradeView {
  'id' : TradeId,
  'escrowAccount' : [] | [EscrowAccount],
  'status' : TradeStatus,
  'completedAt' : [] | [Timestamp],
  'listing' : ListingId,
  'token' : TradeToken,
  'ttnNumber' : [] | [string],
  'createdAt' : Timestamp,
  'confirmedAt' : [] | [Timestamp],
  'seller' : UserId,
  'shippingSelection' : [] | [ShippingSelection],
  'refundDeadline' : [] | [Timestamp],
  'fundedAt' : [] | [Timestamp],
  'buyer' : UserId,
  'amount' : bigint,
  'digitalDelivery' : [] | [DigitalDelivery],
  'ttnCreationStatus' : TTNStatus,
}
export type TrustLevel = { 'new' : null } |
  { 'bronze' : null } |
  { 'gold' : null } |
  { 'silver' : null };
export interface TxHistoryFilter {
  'to' : [] | [Timestamp],
  'status' : [] | [TradeStatus],
  'token' : [] | [TradeToken],
  'from' : [] | [Timestamp],
}
export interface UkrposhtaConfig {
  'enabled' : boolean,
  'senderOfficeRef' : [] | [string],
  'deliveryTypes' : Array<string>,
}
export interface UserFilter {
  'roleFilter' : [] | [UserRole],
  'bannedFilter' : [] | [boolean],
}
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'bio' : string,
  'reputationScore' : bigint,
  'username' : string,
  'createdAt' : Timestamp,
  'trustLevel' : TrustLevel,
  'role' : UserRole,
  'liabilityBalance' : bigint,
  'avatarUrl' : string,
  'liabilityHistory' : Array<LiabilityEvent>,
  'isBanned' : boolean,
  'suspendedUntil' : [] | [Timestamp],
  'paymentMethods' : Array<PaymentMethod>,
}
export type UserRole = { 'admin' : null } |
  { 'moderator' : null } |
  { 'user' : null };
export interface VaultAddressView {
  'chain' : ChainType,
  'network' : string,
  'tokenSymbol' : string,
  'address' : string,
  'derivedAt' : bigint,
}
export interface WithdrawalRecord {
  'id' : bigint,
  'executedAt' : Timestamp,
  'recipient' : Principal,
  'amount' : bigint,
  'proposalId' : bigint,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<string>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    CreateCertificateResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_transformResponse' : ActorMethod<
    [
      {
        'context' : Uint8Array,
        'response' : {
          'status' : bigint,
          'body' : Uint8Array,
          'headers' : Array<{ 'value' : string, 'name' : string }>,
        },
      },
    ],
    {
      'status' : bigint,
      'body' : Uint8Array,
      'headers' : Array<{ 'value' : string, 'name' : string }>,
    }
  >,
  'addComplianceNote' : ActorMethod<[UserId, string], undefined>,
  'addEvidence' : ActorMethod<[DisputeId, Array<MediaAttachment>], Result>,
  'addFavorite' : ActorMethod<[ListingId], Result>,
  'addModeratorNote' : ActorMethod<[DisputeId, string], Result>,
  'addPaymentMethod' : ActorMethod<[TradeToken, string, boolean], Result_28>,
  'adminGetAllTrades' : ActorMethod<[], Array<TradeView>>,
  'adminPromoteListing' : ActorMethod<[ListingId], Result>,
  'adminRemoveListing' : ActorMethod<[ListingId, string], Result>,
  'appealDispute' : ActorMethod<[DisputeId, string], Result>,
  'assignJurors' : ActorMethod<[DisputeId], Result>,
  'banUser' : ActorMethod<[UserId, string], undefined>,
  'bumpListing' : ActorMethod<[ListingId], Result>,
  'calculateShippingCost' : ActorMethod<
    [string, string, number, ShippingServiceType],
    { 'ok' : { 'transitDays' : bigint, 'costUAH' : bigint } } |
      { 'err' : string }
  >,
  'canConfirmDelivery' : ActorMethod<[TradeId], boolean>,
  'castJurorVote' : ActorMethod<[DisputeId, JurorVoteChoice, string], Result>,
  'checkAndExpireTimeouts' : ActorMethod<[], bigint>,
  'checkDigitalInspectionDeadline' : ActorMethod<[TradeId], Result_10>,
  'checkJuryDeadlines' : ActorMethod<[], bigint>,
  'cleanupResolvedListings' : ActorMethod<
    [],
    {
      'deletedCount' : bigint,
      'skippedByDispute' : bigint,
      'photosToDelete' : Array<string>,
    }
  >,
  'closeProposal' : ActorMethod<[ProposalId], Result_27>,
  'confirmPaymentReceived' : ActorMethod<[TradeId], Result>,
  'confirmPaymentSent' : ActorMethod<[TradeId], Result>,
  'createListing' : ActorMethod<
    [
      string,
      string,
      ListingCategory,
      [] | [CategoryId],
      bigint,
      TradeToken,
      ItemCondition,
      Array<string>,
      string,
      Array<ShippingMethod>,
      boolean,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [PackageDetails],
      [] | [NovaPoshtaConfig],
      [] | [UkrposhtaConfig],
      [] | [MeestConfig],
    ],
    Result_26
  >,
  'createMeestTTN' : ActorMethod<[TradeId], Result_9>,
  'createMeestWaybill' : ActorMethod<
    [string, string, number, string, bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createNovaPoshtaTTN' : ActorMethod<[TradeId], Result_9>,
  'createProposal' : ActorMethod<[ProposalType, string], Result_25>,
  'createUkrPoshtaWaybill' : ActorMethod<
    [string, string, number, string, bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createUkrposhtaTTN' : ActorMethod<[TradeId], Result_9>,
  'createWaybill' : ActorMethod<
    [string, string, number, string, bigint, ShippingServiceType],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deactivateListing' : ActorMethod<[ListingId], Result>,
  'deleteSavedSearch' : ActorMethod<[SavedSearchId], Result>,
  'demoteFromModerator' : ActorMethod<[UserId], undefined>,
  'estimateTokenAmount' : ActorMethod<[bigint, TradeToken], [] | [bigint]>,
  'executeProposal' : ActorMethod<[ProposalId], Result>,
  'getAllUsers' : ActorMethod<[bigint, bigint, UserFilter], PagedResult_1>,
  'getAuditLog' : ActorMethod<[bigint, bigint, AuditFilter], PagedResult>,
  'getCachedRate' : ActorMethod<[TradeToken], [] | [RateCacheEntry]>,
  'getComplianceNotes' : ActorMethod<[UserId], Array<ComplianceNote>>,
  'getCyclesStatus' : ActorMethod<[], CyclesStatus>,
  'getDashboardMetrics' : ActorMethod<[], PlatformMetrics__1>,
  'getDigitalDelivery' : ActorMethod<[TradeId], Result_24>,
  'getDispute' : ActorMethod<[DisputeId], [] | [DisputeView]>,
  'getDisputeJurors' : ActorMethod<[DisputeId], [] | [JuryView]>,
  'getDisputesByTrade' : ActorMethod<[TradeId], Array<DisputeView>>,
  'getEndpointErrorRate' : ActorMethod<[string, bigint], number>,
  'getErrorLog' : ActorMethod<[bigint, [] | [string]], Array<ErrorLogEntry>>,
  'getExecutionHistory' : ActorMethod<[], Array<ProposalView>>,
  'getExpiredListings' : ActorMethod<[bigint, bigint], Array<ListingCard>>,
  'getExplorerApiKeyStatus' : ActorMethod<
    [],
    {
      'bscScanConfigured' : boolean,
      'infuraConfigured' : boolean,
      'tronGridConfigured' : boolean,
    }
  >,
  'getFavoriteListings' : ActorMethod<[], Array<ListingCard>>,
  /**
   * / This canister's own principal — used as the escrow recipient in ICRC-2 transfers.
   */
  'getFeedbackForTrade' : ActorMethod<[TradeId], Array<Feedback>>,
  'getJurorDashboard' : ActorMethod<[], Array<JurorDashboardEntry>>,
  'getJuryPool' : ActorMethod<[], Result_23>,
  'getLinkPreview' : ActorMethod<[string], Result_22>,
  'getListing' : ActorMethod<[ListingId], [] | [ListingCard]>,
  'getListingInquiryMessages' : ActorMethod<[ListingId, UserId], Result_21>,
  'getListingsByUser' : ActorMethod<
    [UserId, bigint, bigint],
    Array<ListingCard>
  >,
  'getMeestPUDOs' : ActorMethod<
    [string, [] | [string], [] | [bigint]],
    Result_20
  >,
  'getMetricsSummary' : ActorMethod<[], MetricsSummary>,
  'getModeratorThread' : ActorMethod<[TradeId], Array<Message>>,
  'getModuleMetrics' : ActorMethod<[], Array<ModuleMetricsView>>,
  'getMyDisputes' : ActorMethod<[], Array<DisputeView>>,
  'getMyFeedback' : ActorMethod<[], Array<Feedback>>,
  'getMyJurorDashboard' : ActorMethod<[], Result_19>,
  'getMyListings' : ActorMethod<[bigint, bigint], Array<ListingCard>>,
  'getMyPaymentMethods' : ActorMethod<[], Array<PaymentMethod>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMyTrades' : ActorMethod<
    [{ 'all' : null } | { 'seller' : null } | { 'buyer' : null }],
    Array<TradeView>
  >,
  'getMyTransactionHistory' : ActorMethod<
    [TxHistoryFilter, bigint, bigint],
    Page
  >,
  'getNovaPoshtaBranches' : ActorMethod<
    [string, [] | [string], [] | [bigint]],
    Result_18
  >,
  'getNovaPoshtaCityRef' : ActorMethod<[string], Result_9>,
  'getOpenDisputeQueue' : ActorMethod<[bigint, bigint], Result_17>,
  'getP95Latency' : ActorMethod<[string, bigint], bigint>,
  'getPaymentMethods' : ActorMethod<[], Array<PaymentMethod>>,
  'getPaymentVerificationStatus' : ActorMethod<
    [TradeId],
    [] | [PaymentVerificationResult]
  >,
  'getPlatformMetrics' : ActorMethod<[], PlatformMetrics>,
  'getProposal' : ActorMethod<[ProposalId], [] | [ProposalView]>,
  'getProposals' : ActorMethod<[[] | [ProposalStatus]], Array<ProposalView>>,
  'getRequestRate' : ActorMethod<[string, bigint], bigint>,
  'getSavedSearches' : ActorMethod<[], Array<SavedSearch>>,
  'getSellerLiability' : ActorMethod<[Principal], Result_16>,
  'getShippingOptions' : ActorMethod<
    [number, string, string],
    { 'ok' : Array<ShippingOption> } |
      { 'err' : string }
  >,
  'getSupportedCarriers' : ActorMethod<[], Array<CarrierInfo>>,
  'getSupportedTokens' : ActorMethod<[], Array<TokenInfo>>,
  'getSystemSettings' : ActorMethod<
    [],
    {
      'maxListingPriceUSD' : bigint,
      'paymentTimeoutHours' : bigint,
      'allowedTokens' : Array<TradeToken>,
      'cyclesBalanceThreshold' : bigint,
      'minTradeAmountUSD' : bigint,
      'errorRateThreshold' : number,
    }
  >,
  'getTokenInfo' : ActorMethod<[TradeToken], [] | [TokenInfo]>,
  'getTrade' : ActorMethod<[TradeId], [] | [TradeView]>,
  'getTradeMessages' : ActorMethod<[TradeId, bigint, bigint], Array<Message>>,
  'getTradeNotifications' : ActorMethod<[], Array<NotificationEvent>>,
  'getTradePaymentStatus' : ActorMethod<[TradeId], [] | [TradePaymentStatus]>,
  'getTradesByListing' : ActorMethod<[ListingId], Array<TradeView>>,
  'getTradesPerDay' : ActorMethod<
    [bigint],
    Array<{ 'date' : string, 'count' : bigint }>
  >,
  'getTreasuryBalance' : ActorMethod<[], bigint>,
  'getTreasuryWithdrawals' : ActorMethod<[], Array<WithdrawalRecord>>,
  'getUkrposhtaOffices' : ActorMethod<
    [string, [] | [string], [] | [bigint]],
    Result_15
  >,
  'getUnifiedTrackingInfo' : ActorMethod<[TradeId], Result_14>,
  'getUnreadCount' : ActorMethod<[], Array<[TradeId, bigint]>>,
  'getUserFeedback' : ActorMethod<[UserId], Array<Feedback>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserReputationStats' : ActorMethod<[UserId], [] | [ReputationStats]>,
  'getVaultAddresses' : ActorMethod<[], Array<VaultAddressView>>,
  'getVaultBalance' : ActorMethod<[ChainType], [] | [BalanceView]>,
  'incrementListingView' : ActorMethod<[ListingId], undefined>,
  'initiateOnChainTrade' : ActorMethod<
    [ListingId, TradeToken, [] | [ShippingSelection]],
    Result_13
  >,
  'initiateTrade' : ActorMethod<
    [ListingId, TradeToken, [] | [ShippingSelection]],
    Result_13
  >,
  'isListingFavorite' : ActorMethod<[ListingId], boolean>,
  'leaveFeedback' : ActorMethod<[TradeId, UserId, bigint, string], Result_12>,
  'listCategories' : ActorMethod<[], Array<CategoryNode>>,
  'markAllNotificationsRead' : ActorMethod<[], Result>,
  'markNotificationRead' : ActorMethod<[bigint], Result>,
  'markTradeAsRead' : ActorMethod<[TradeId], undefined>,
  'openDigitalDispute' : ActorMethod<[TradeId, string], Result_11>,
  'openDispute' : ActorMethod<[TradeId, DisputeReason, string], Result_11>,
  'promoteToModerator' : ActorMethod<[UserId], undefined>,
  'proposeCancelTrade' : ActorMethod<[TradeId], Result_10>,
  'reactivateListing' : ActorMethod<[ListingId], Result>,
  'recordRequest' : ActorMethod<[string, bigint, bigint], undefined>,
  /**
   * / This canister's own principal — used as the escrow recipient in ICRC-2 transfers.
   */
  'recordTreasuryFee' : ActorMethod<[TradeId, bigint, TradeToken], undefined>,
  'refreshRates' : ActorMethod<[], bigint>,
  /**
   * / This canister's own principal — used as the escrow recipient in ICRC-2 transfers.
   */
  'refreshVaultBalance' : ActorMethod<[ChainType], BalanceView>,
  'registerAsJuror' : ActorMethod<[number], Result>,
  'removeFavorite' : ActorMethod<[ListingId], Result>,
  'removeListingByAdmin' : ActorMethod<[ListingId, string], undefined>,
  'reopenDispute' : ActorMethod<[DisputeId], Result>,
  'reportListing' : ActorMethod<[ListingId, string], Result>,
  'requestRefund' : ActorMethod<[TradeId], Result>,
  'resolveDispute' : ActorMethod<
    [DisputeId, ResolutionOutcome, string],
    Result
  >,
  'resolveDisputeEscrow' : ActorMethod<[DisputeId, ResolutionOutcome], Result>,
  'retryMeestTTNCreation' : ActorMethod<[TradeId], Result_9>,
  'retryTTNCreation' : ActorMethod<[TradeId], Result_9>,
  'retryUkrposhtaTTNCreation' : ActorMethod<[TradeId], Result_9>,
  'saveSearch' : ActorMethod<[string, string], Result_8>,
  'searchListings' : ActorMethod<
    [
      [] | [string],
      [] | [ListingCategory],
      [] | [CategoryId],
      [] | [bigint],
      [] | [bigint],
      [] | [string],
      [] | [ItemCondition],
      [] | [ShippingCarrier],
      bigint,
      bigint,
      [] | [TradeToken],
    ],
    Array<ListingCard>
  >,
  'sendListingInquiry' : ActorMethod<[ListingId, string], Result_7>,
  'sendListingInquiryReply' : ActorMethod<
    [ListingId, UserId, string],
    Result_7
  >,
  'sendMessage' : ActorMethod<
    [TradeId, string, Array<MediaAttachment>],
    Result_6
  >,
  'setAvalancheApiKey' : ActorMethod<[string], undefined>,
  'setBscScanApiKey' : ActorMethod<[string], undefined>,
  'setDisputeUnderReview' : ActorMethod<[DisputeId], Result>,
  'setInfuraApiKey' : ActorMethod<[string], undefined>,
  'setMeestApiKey' : ActorMethod<[string], undefined>,
  'setMyProfile' : ActorMethod<
    [string, string, string, [] | [string]],
    Result_5
  >,
  'setNovaPoshtaApiKey' : ActorMethod<[string], undefined>,
  'setPolygonApiKey' : ActorMethod<[string], undefined>,
  'setSolanaRpcUrl' : ActorMethod<[string], undefined>,
  'setTronGridApiKey' : ActorMethod<[string], undefined>,
  'setUkrPoshtaApiKey' : ActorMethod<[string], undefined>,
  'submitJurorVote' : ActorMethod<[DisputeId, JurorVoteChoice, string], Result>,
  'suspendUser' : ActorMethod<[UserId, Timestamp, string], undefined>,
  'trackMeestShipment' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'trackShipment' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'trackUkrPoshtaShipment' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'transformPaymentResponse' : ActorMethod<
    [{ 'context' : Uint8Array, 'response' : HttpResponse }],
    HttpResponse
  >,
  'unbanUser' : ActorMethod<[UserId], undefined>,
  'unregisterJuror' : ActorMethod<[], Result>,
  'updateListing' : ActorMethod<
    [
      ListingId,
      string,
      string,
      ListingCategory,
      [] | [CategoryId],
      bigint,
      TradeToken,
      ItemCondition,
      Array<string>,
      string,
      Array<ShippingMethod>,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [PackageDetails],
      [] | [NovaPoshtaConfig],
      [] | [UkrposhtaConfig],
      [] | [MeestConfig],
    ],
    Result
  >,
  /**
   * / Rolling request metrics log — FIFO, capacity 10 000.
   */
  'updateSystemSettings' : ActorMethod<
    [bigint, bigint, Array<TradeToken>, bigint, bigint, number],
    undefined
  >,
  'verifyEvmAddress' : ActorMethod<[string, string], Result_1>,
  'verifyPayment' : ActorMethod<[TradeId, string, TradeToken], Result_2>,
  'verifySolanaAddress' : ActorMethod<[string], Result_1>,
  'verifyTradePayment' : ActorMethod<[TradeId, string, string], Result_2>,
  'verifyTronAddress' : ActorMethod<[string], Result_1>,
  'voteOnProposal' : ActorMethod<[ProposalId, boolean], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];