/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserId = IDL.Principal;
  const DisputeId = IDL.Nat;
  const MediaAttachment = IDL.Record({
    'url' : IDL.Text,
    'mimeType' : IDL.Text,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
  });
  const Error = IDL.Variant({
    'insufficient_funds' : IDL.Null,
    'rate_limited' : IDL.Null,
    'dispute_already_open' : IDL.Null,
    'not_found' : IDL.Null,
    'banned' : IDL.Null,
    'invalid_input' : IDL.Text,
    'escrow_error' : IDL.Text,
    'already_exists' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const ListingId = IDL.Nat;
  const TradeToken = IDL.Variant({
    'USDT_ERC20' : IDL.Null,
    'USDT_AVAX' : IDL.Null,
    'USDC_ERC20' : IDL.Null,
    'USDT_BEP20' : IDL.Null,
    'USDC_AVAX' : IDL.Null,
    'ckUSDC' : IDL.Null,
    'ckUSDT' : IDL.Null,
    'USDC_SPL' : IDL.Null,
    'USDT_TRC20' : IDL.Null,
    'USDC_POLYGON' : IDL.Null,
    'USDT_POLYGON' : IDL.Null,
  });
  const AddressVerification = IDL.Record({
    'active' : IDL.Bool,
    'expiresAt' : IDL.Nat,
    'level' : IDL.Nat,
    'txCount' : IDL.Nat,
    'verifiedAt' : IDL.Nat,
  });
  const PaymentMethod = IDL.Record({
    'walletLinkId' : IDL.Nat,
    'token' : TradeToken,
    'addedAt' : IDL.Nat,
    'address' : IDL.Text,
    'verification' : IDL.Opt(AddressVerification),
  });
  const Result_37 = IDL.Variant({ 'ok' : PaymentMethod, 'err' : Error });
  const PayoutStatus = IDL.Variant({
    'pending_first_approval' : IDL.Null,
    'held_fraud_review' : IDL.Null,
    'denied' : IDL.Null,
    'pending_second_approval' : IDL.Null,
    'approved' : IDL.Null,
    'executed' : IDL.Null,
  });
  const CollusionSignal = IDL.Variant({
    'rapid_account_cycling' : IDL.Null,
    'reciprocal_trades' : IDL.Null,
    'shared_wallet' : IDL.Null,
    'repeated_claims' : IDL.Null,
  });
  const Timestamp = IDL.Nat;
  const TradeId = IDL.Nat;
  const FraudReviewRecord = IDL.Record({
    'decision' : IDL.Text,
    'reviewedAt' : Timestamp,
    'slaDueAt' : Timestamp,
    'rationale' : IDL.Text,
    'reviewer' : IDL.Principal,
    'evidenceHash' : IDL.Text,
  });
  const PayoutRequestView = IDL.Record({
    'id' : IDL.Nat,
    'status' : PayoutStatus,
    'liabilityId' : IDL.Nat,
    'token' : TradeToken,
    'collusionSignals' : IDL.Vec(CollusionSignal),
    'executedAt' : Timestamp,
    'beneficiary' : IDL.Principal,
    'unrecoveredLoss' : IDL.Nat,
    'firstApprover' : IDL.Opt(IDL.Principal),
    'tradeId' : TradeId,
    'fraudReview' : IDL.Opt(FraudReviewRecord),
    'secondApprover' : IDL.Opt(IDL.Principal),
    'approvedAmount' : IDL.Nat,
    'requestedAt' : Timestamp,
  });
  const Result_35 = IDL.Variant({ 'ok' : PayoutRequestView, 'err' : Error });
  const EscrowAccount = IDL.Record({
    'fee' : IDL.Nat,
    'sellerPrincipal' : UserId,
    'token' : TradeToken,
    'ledgerCanisterId' : IDL.Principal,
    'deadline' : IDL.Nat,
    'tradeId' : TradeId,
    'lockedAt' : IDL.Nat,
    'buyerPrincipal' : UserId,
    'amount' : IDL.Nat,
  });
  const TradeStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'payment_intent' : IDL.Null,
    'payment_verified' : IDL.Null,
    'fulfillment_pending' : IDL.Null,
    'cancelled' : IDL.Null,
    'disputed' : IDL.Null,
    'pending' : IDL.Null,
    'refunded' : IDL.Null,
    'dispute_l1' : IDL.Null,
    'dispute_l2' : IDL.Null,
    'payment_intent_expired' : IDL.Null,
    'funded' : IDL.Null,
    'buyer_confirmed' : IDL.Null,
    'complete' : IDL.Null,
    'digital_delivered' : IDL.Null,
    'awaiting_receipt' : IDL.Null,
    'awaiting_approval' : IDL.Null,
    'manual_payment_pending' : IDL.Null,
    'cancelled_buyer_pre_ship' : IDL.Null,
    'awaiting_seller_handshake' : IDL.Null,
    'cancelled_no_seller_response' : IDL.Null,
  });
  const BuyerCancelPenaltySplit = IDL.Record({
    'buyerRefund' : IDL.Nat,
    'platformFee' : IDL.Nat,
    'sellerCompensation' : IDL.Nat,
    'lockedAmount' : IDL.Nat,
  });
  const OnChainSettlementOp = IDL.Variant({
    'buyerCancelSplit' : BuyerCancelPenaltySplit,
    'releaseToSeller' : IDL.Null,
    'refundBuyer' : IDL.Record({ 'memo' : IDL.Text }),
    'disputeBuyerWins' : IDL.Null,
    'disputeSplit' : IDL.Record({ 'sellerHasNegativeRep' : IDL.Bool }),
    'disputeSellerWins' : IDL.Record({ 'sellerHasNegativeRep' : IDL.Bool }),
  });
  const PendingOnChainSettlementView = IDL.Record({
    'op' : OnChainSettlementOp,
    'queuedAt' : IDL.Nat,
    'attempts' : IDL.Nat,
    'lastError' : IDL.Opt(IDL.Text),
    'targetStatus' : TradeStatus,
  });
  const ShippingSelection = IDL.Record({
    'provider' : IDL.Text,
    'branchRef' : IDL.Opt(IDL.Text),
    'cost' : IDL.Nat,
    'deliveryType' : IDL.Text,
    'address' : IDL.Opt(IDL.Text),
  });
  const PaymentSettlementPath = IDL.Variant({
    'ck' : IDL.Null,
    'manual' : IDL.Null,
  });
  const PaymentIntent = IDL.Record({
    'token' : TradeToken,
    'createdAt' : IDL.Nat,
    'path' : PaymentSettlementPath,
    'recipient' : IDL.Text,
    'network' : IDL.Text,
    'expiry' : IDL.Nat,
    'exactAmount' : IDL.Nat,
  });
  const WalletChain = IDL.Variant({
    'tron' : IDL.Null,
    'evm_bsc' : IDL.Null,
    'evm_eth' : IDL.Null,
  });
  const PayoutWalletSnapshot = IDL.Record({
    'snapshottedAt' : IDL.Nat,
    'walletLinkId' : IDL.Nat,
    'token' : TradeToken,
    'chain' : WalletChain,
    'address' : IDL.Text,
  });
  const DigitalDeliveryView = IDL.Record({
    'inspectionDeadline' : IDL.Nat,
    'password' : IDL.Opt(IDL.Text),
    'deliveryRecordAt' : IDL.Nat,
    'mimeType' : IDL.Opt(IDL.Text),
    'fileHash' : IDL.Opt(IDL.Text),
    'dekHex' : IDL.Opt(IDL.Text),
    'fileVersionId' : IDL.Nat,
    'revealedAt' : IDL.Nat,
    'fileUrl' : IDL.Text,
  });
  const TTNStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Success' : IDL.Null,
    'InProgress' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const TradeView = IDL.Record({
    'id' : TradeId,
    'escrowAccount' : IDL.Opt(EscrowAccount),
    'status' : TradeStatus,
    'completedAt' : IDL.Nat,
    'listing' : ListingId,
    'pendingOnChainSettlement' : IDL.Opt(PendingOnChainSettlementView),
    'token' : TradeToken,
    'ttnNumber' : IDL.Opt(IDL.Text),
    'npDeliveredGraceEndsAt' : IDL.Nat,
    'createdAt' : IDL.Nat,
    'confirmedAt' : IDL.Nat,
    'deliveryRecordAt' : IDL.Nat,
    'seller' : UserId,
    'shippingSelection' : IDL.Opt(ShippingSelection),
    'sellerResponseDeadline' : IDL.Nat,
    'refundDeadline' : IDL.Nat,
    'shippedAt' : IDL.Nat,
    'payoutWalletHeld' : IDL.Bool,
    'fundedAt' : IDL.Nat,
    'shipByDeadline' : IDL.Nat,
    'paymentIntent' : IDL.Opt(PaymentIntent),
    'buyer' : UserId,
    'npDeliveredAt' : IDL.Nat,
    'amount' : IDL.Nat,
    'payoutWalletSnapshot' : IDL.Opt(PayoutWalletSnapshot),
    'digitalDelivery' : IDL.Opt(DigitalDeliveryView),
    'ttnCreationStatus' : TTNStatus,
  });
  const GateCChecklistView = IDL.Record({
    'securitySignOffRef' : IDL.Text,
    'rollbackTestsPassed' : IDL.Bool,
    'subaccountDesignReviewed' : IDL.Bool,
    'checklistComplete' : IDL.Bool,
    'trustlessEscrowEnabled' : IDL.Bool,
    'testnetE2ePassed' : IDL.Bool,
    'betaCapsConfigured' : IDL.Bool,
    'ckBetaCapUsdCents' : IDL.Nat,
  });
  const LiabilityStatus = IDL.Variant({
    'open' : IDL.Null,
    'cleared' : IDL.Null,
    'partial' : IDL.Null,
  });
  const LiabilityAuditAction = IDL.Variant({
    'created' : IDL.Null,
    'stake_applied' : IDL.Null,
    'partial_clear' : IDL.Null,
    'full_clear' : IDL.Null,
  });
  const LiabilityAuditEntry = IDL.Record({
    'action' : LiabilityAuditAction,
    'note' : IDL.Text,
    'performedBy' : IDL.Principal,
    'timestamp' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const LiabilityReason = IDL.Variant({
    'admin_adjustment' : IDL.Null,
    'cancellation_fee' : IDL.Null,
    'stake_seizure_residual' : IDL.Null,
    'seller_fault' : IDL.Null,
    'dispute_lost' : IDL.Null,
    'buyer_cancel_compensation' : IDL.Null,
  });
  const LiabilityRecordView = IDL.Record({
    'id' : IDL.Nat,
    'status' : LiabilityStatus,
    'originalAmount' : IDL.Nat,
    'initiator' : IDL.Principal,
    'userId' : UserId,
    'createdAt' : IDL.Nat,
    'updatedAt' : IDL.Nat,
    'tradeId' : IDL.Opt(TradeId),
    'remainingBalance' : IDL.Nat,
    'currency' : TradeToken,
    'auditTrail' : IDL.Vec(LiabilityAuditEntry),
    'reason' : LiabilityReason,
  });
  const Result_36 = IDL.Variant({
    'ok' : IDL.Vec(LiabilityRecordView),
    'err' : Error,
  });
  const KycTier = IDL.Variant({ 'verified' : IDL.Null, 'none' : IDL.Null });
  const Result_34 = IDL.Variant({
    'ok' : BuyerCancelPenaltySplit,
    'err' : Error,
  });
  const ShippingServiceType = IDL.Variant({
    'express' : IDL.Null,
    'standard' : IDL.Null,
  });
  const JurorVoteChoice = IDL.Variant({
    'sellerWins' : IDL.Null,
    'buyerWins' : IDL.Null,
  });
  const Result_15 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : Error });
  const ProposalId = IDL.Nat;
  const ProposalStatus = IDL.Variant({
    'active' : IDL.Null,
    'expired' : IDL.Null,
    'rejected' : IDL.Null,
    'executed' : IDL.Null,
    'passed' : IDL.Null,
  });
  const Result_33 = IDL.Variant({ 'ok' : ProposalStatus, 'err' : Error });
  const ListingCategory = IDL.Variant({
    'clothing' : IDL.Null,
    'other' : IDL.Null,
    'books' : IDL.Null,
    'digital' : IDL.Null,
    'services' : IDL.Null,
    'electronics' : IDL.Null,
  });
  const CategoryId = IDL.Nat;
  const ItemCondition = IDL.Variant({
    'new' : IDL.Null,
    'fair' : IDL.Null,
    'good' : IDL.Null,
    'poor' : IDL.Null,
    'likeNew' : IDL.Null,
  });
  const ShippingCarrier = IDL.Variant({
    'meest' : IDL.Null,
    'nova_poshta' : IDL.Null,
    'self_pickup' : IDL.Null,
    'digital' : IDL.Null,
    'ukrposhta' : IDL.Null,
  });
  const ShippingMethod = IDL.Record({
    'type' : ShippingServiceType,
    'estimatedDays' : IDL.Nat,
    'carrier' : ShippingCarrier,
  });
  const PackageDetails = IDL.Record({
    'weight' : IDL.Nat,
    'height' : IDL.Nat,
    'places' : IDL.Nat,
    'length' : IDL.Nat,
    'declaredValue' : IDL.Nat,
    'width' : IDL.Nat,
  });
  const NovaPoshtaConfig = IDL.Record({
    'enabled' : IDL.Bool,
    'senderBranchRef' : IDL.Text,
    'deliveryTypes' : IDL.Vec(IDL.Text),
  });
  const UkrposhtaConfig = IDL.Record({
    'enabled' : IDL.Bool,
    'senderOfficeRef' : IDL.Opt(IDL.Text),
    'deliveryTypes' : IDL.Vec(IDL.Text),
  });
  const MeestConfig = IDL.Record({
    'senderPudoRef' : IDL.Opt(IDL.Text),
    'enabled' : IDL.Bool,
    'deliveryTypes' : IDL.Vec(IDL.Text),
  });
  const CategoryAttributeValue = IDL.Record({
    'key' : IDL.Text,
    'value' : IDL.Text,
  });
  const ListingStatus = IDL.Variant({
    'active' : IDL.Null,
    'sold' : IDL.Null,
    'inactive' : IDL.Null,
    'draft' : IDL.Null,
    'removed' : IDL.Null,
  });
  const TrustLevel = IDL.Variant({
    'new' : IDL.Null,
    'bronze' : IDL.Null,
    'gold' : IDL.Null,
    'silver' : IDL.Null,
  });
  const ListingCard = IDL.Record({
    'id' : ListingId,
    'categoryId' : CategoryId,
    'status' : ListingStatus,
    'title' : IDL.Text,
    'sellerPrincipal' : UserId,
    'priceAmount' : IDL.Nat,
    'categorySlug' : IDL.Text,
    'shippingMethods' : IDL.Vec(ShippingMethod),
    'createdAt' : IDL.Nat,
    'description' : IDL.Text,
    'sellerTrustLevel' : TrustLevel,
    'isPromoted' : IDL.Bool,
    'sellerRating' : IDL.Int,
    'attributes' : IDL.Vec(CategoryAttributeValue),
    'priceToken' : TradeToken,
    'category' : ListingCategory,
    'sellerUsername' : IDL.Text,
    'location' : IDL.Text,
    'photos' : IDL.Vec(IDL.Text),
    'digitalFileUrl' : IDL.Text,
    'condition' : ItemCondition,
  });
  const Result_32 = IDL.Variant({ 'ok' : ListingCard, 'err' : Error });
  const Result_11 = IDL.Variant({ 'ok' : IDL.Text, 'err' : Error });
  const Result_31 = IDL.Variant({ 'ok' : PaymentIntent, 'err' : Error });
  const ProposalType = IDL.Variant({
    'TextResolution' : IDL.Record({ 'description' : IDL.Text }),
    'TreasuryTransfer' : IDL.Record({
      'recipient' : IDL.Principal,
      'amount' : IDL.Nat,
    }),
    'ParameterChange' : IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text }),
  });
  const Result_30 = IDL.Variant({ 'ok' : ProposalId, 'err' : Error });
  const SavedSearchId = IDL.Nat;
  const MessageId = IDL.Nat;
  const ExportInt = IDL.Int;
  const MediaAttachmentExport = IDL.Record({
    'url' : IDL.Text,
    'mimeType' : IDL.Text,
    'fileName' : IDL.Text,
    'fileSize' : ExportInt,
  });
  const AccountMessageExport = IDL.Record({
    'attachmentUrl' : IDL.Opt(IDL.Text),
    'content' : IDL.Text,
    'messageId' : MessageId,
    'sender' : UserId,
    'sentAt' : ExportInt,
    'tradeId' : TradeId,
    'attachments' : IDL.Vec(MediaAttachmentExport),
  });
  const ShippingMethodExport = IDL.Record({
    'type' : ShippingServiceType,
    'estimatedDays' : ExportInt,
    'carrier' : ShippingCarrier,
  });
  const ListingCardExport = IDL.Record({
    'id' : ListingId,
    'categoryId' : CategoryId,
    'title' : IDL.Text,
    'sellerPrincipal' : UserId,
    'priceAmount' : ExportInt,
    'categorySlug' : IDL.Text,
    'shippingMethods' : IDL.Vec(ShippingMethodExport),
    'createdAt' : ExportInt,
    'description' : IDL.Text,
    'sellerTrustLevel' : TrustLevel,
    'isPromoted' : IDL.Bool,
    'listingStatus' : ListingStatus,
    'sellerRating' : IDL.Int,
    'attributes' : IDL.Vec(CategoryAttributeValue),
    'priceToken' : TradeToken,
    'category' : ListingCategory,
    'sellerUsername' : IDL.Text,
    'location' : IDL.Text,
    'photos' : IDL.Vec(IDL.Text),
    'digitalFileUrl' : IDL.Text,
    'condition' : ItemCondition,
  });
  const EscrowAccountExport = IDL.Record({
    'fee' : ExportInt,
    'sellerPrincipal' : UserId,
    'token' : TradeToken,
    'ledgerCanisterId' : IDL.Principal,
    'deadline' : ExportInt,
    'tradeId' : TradeId,
    'lockedAt' : ExportInt,
    'buyerPrincipal' : UserId,
    'amount' : ExportInt,
  });
  const BuyerCancelPenaltySplitExport = IDL.Record({
    'buyerRefund' : ExportInt,
    'platformFee' : ExportInt,
    'sellerCompensation' : ExportInt,
    'lockedAmount' : ExportInt,
  });
  const OnChainSettlementOpExport = IDL.Variant({
    'buyerCancelSplit' : BuyerCancelPenaltySplitExport,
    'releaseToSeller' : IDL.Null,
    'refundBuyer' : IDL.Record({ 'memo' : IDL.Text }),
    'disputeBuyerWins' : IDL.Null,
    'disputeSplit' : IDL.Record({ 'sellerHasNegativeRep' : IDL.Bool }),
    'disputeSellerWins' : IDL.Record({ 'sellerHasNegativeRep' : IDL.Bool }),
  });
  const PendingOnChainSettlementExport = IDL.Record({
    'op' : OnChainSettlementOpExport,
    'queuedAt' : ExportInt,
    'attempts' : ExportInt,
    'lastError' : IDL.Opt(IDL.Text),
    'targetStatus' : TradeStatus,
  });
  const ShippingSelectionExport = IDL.Record({
    'provider' : IDL.Text,
    'branchRef' : IDL.Opt(IDL.Text),
    'cost' : ExportInt,
    'deliveryType' : IDL.Text,
    'address' : IDL.Opt(IDL.Text),
  });
  const PaymentIntentExport = IDL.Record({
    'token' : TradeToken,
    'createdAt' : ExportInt,
    'path' : PaymentSettlementPath,
    'recipient' : IDL.Text,
    'network' : IDL.Text,
    'expiry' : ExportInt,
    'exactAmount' : ExportInt,
  });
  const PayoutWalletSnapshotExport = IDL.Record({
    'snapshottedAt' : ExportInt,
    'walletLinkId' : ExportInt,
    'token' : TradeToken,
    'chain' : WalletChain,
    'address' : IDL.Text,
  });
  const DigitalDeliveryViewExport = IDL.Record({
    'inspectionDeadline' : ExportInt,
    'password' : IDL.Opt(IDL.Text),
    'deliveryRecordAt' : ExportInt,
    'mimeType' : IDL.Opt(IDL.Text),
    'fileHash' : IDL.Opt(IDL.Text),
    'dekHex' : IDL.Opt(IDL.Text),
    'fileVersionId' : ExportInt,
    'revealedAt' : ExportInt,
    'fileUrl' : IDL.Text,
  });
  const TradeViewExport = IDL.Record({
    'id' : TradeId,
    'escrowAccount' : IDL.Opt(EscrowAccountExport),
    'completedAt' : ExportInt,
    'listing' : ListingId,
    'pendingOnChainSettlement' : IDL.Opt(PendingOnChainSettlementExport),
    'token' : TradeToken,
    'ttnNumber' : IDL.Opt(IDL.Text),
    'npDeliveredGraceEndsAt' : ExportInt,
    'createdAt' : ExportInt,
    'confirmedAt' : ExportInt,
    'deliveryRecordAt' : ExportInt,
    'seller' : UserId,
    'shippingSelection' : IDL.Opt(ShippingSelectionExport),
    'sellerResponseDeadline' : ExportInt,
    'refundDeadline' : ExportInt,
    'shippedAt' : ExportInt,
    'payoutWalletHeld' : IDL.Bool,
    'fundedAt' : ExportInt,
    'shipByDeadline' : ExportInt,
    'paymentIntent' : IDL.Opt(PaymentIntentExport),
    'buyer' : UserId,
    'npDeliveredAt' : ExportInt,
    'amount' : ExportInt,
    'payoutWalletSnapshot' : IDL.Opt(PayoutWalletSnapshotExport),
    'digitalDelivery' : IDL.Opt(DigitalDeliveryViewExport),
    'tradeStatus' : TradeStatus,
    'ttnCreationStatus' : TTNStatus,
  });
  const FeedbackId = IDL.Nat;
  const FeedbackExport = IDL.Record({
    'id' : FeedbackId,
    'trade' : TradeId,
    'createdAt' : ExportInt,
    'comment' : IDL.Text,
    'rating' : ExportInt,
    'reviewed' : UserId,
    'reviewer' : UserId,
  });
  const SavedSearchExport = IDL.Record({
    'id' : SavedSearchId,
    'alertsEnabled' : IDL.Bool,
    'owner' : UserId,
    'paramsJson' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : ExportInt,
  });
  const WalletLinkPurpose = IDL.Variant({
    'stake' : IDL.Null,
    'payment' : IDL.Null,
    'payout' : IDL.Null,
  });
  const LinkedExternalWalletExport = IDL.Record({
    'id' : ExportInt,
    'linkedAt' : ExportInt,
    'chain' : WalletChain,
    'messageHash' : IDL.Text,
    'address' : IDL.Text,
    'sessionId' : IDL.Text,
    'purpose' : WalletLinkPurpose,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'moderator' : IDL.Null,
    'user' : IDL.Null,
  });
  const LiabilityEventExport = IDL.Record({
    'liabilityId' : ExportInt,
    'tradeId' : ExportInt,
    'timestamp' : ExportInt,
    'amount' : IDL.Int,
    'reason' : IDL.Text,
  });
  const AddressVerificationExport = IDL.Record({
    'active' : IDL.Bool,
    'expiresAt' : ExportInt,
    'level' : ExportInt,
    'txCount' : ExportInt,
    'verifiedAt' : ExportInt,
  });
  const PaymentMethodExport = IDL.Record({
    'walletLinkId' : ExportInt,
    'token' : TradeToken,
    'addedAt' : ExportInt,
    'address' : IDL.Text,
    'verification' : IDL.Opt(AddressVerificationExport),
  });
  const UserProfileExport = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'reputationScore' : IDL.Int,
    'linkedWallets' : IDL.Vec(LinkedExternalWalletExport),
    'buyerScore' : IDL.Int,
    'username' : IDL.Text,
    'createdAt' : ExportInt,
    'trustLevel' : TrustLevel,
    'role' : UserRole,
    'liabilityBalance' : IDL.Int,
    'avatarUrl' : IDL.Text,
    'liabilityHistory' : IDL.Vec(LiabilityEventExport),
    'isBanned' : IDL.Bool,
    'accountClosedAt' : ExportInt,
    'suspendedUntil' : ExportInt,
    'sellerScore' : IDL.Int,
    'paymentMethods' : IDL.Vec(PaymentMethodExport),
    'kycTier' : KycTier,
  });
  const AccountExportBundle = IDL.Record({
    'favoriteListingIds' : IDL.Vec(ListingId),
    'principal' : UserId,
    'messages' : IDL.Vec(AccountMessageExport),
    'listings' : IDL.Vec(ListingCardExport),
    'trades' : IDL.Vec(TradeViewExport),
    'feedback' : IDL.Vec(FeedbackExport),
    'exportedAt' : ExportInt,
    'hasProfile' : IDL.Bool,
    'savedSearches' : IDL.Vec(SavedSearchExport),
    'profile' : UserProfileExport,
  });
  const UserFilter = IDL.Record({
    'roleFilter' : IDL.Opt(UserRole),
    'bannedFilter' : IDL.Opt(IDL.Bool),
  });
  const LinkedExternalWallet = IDL.Record({
    'id' : IDL.Nat,
    'linkedAt' : IDL.Nat,
    'chain' : WalletChain,
    'messageHash' : IDL.Text,
    'address' : IDL.Text,
    'sessionId' : IDL.Text,
    'purpose' : WalletLinkPurpose,
  });
  const LiabilityEvent = IDL.Record({
    'liabilityId' : IDL.Nat,
    'tradeId' : IDL.Nat,
    'timestamp' : IDL.Nat,
    'amount' : IDL.Int,
    'reason' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'reputationScore' : IDL.Int,
    'linkedWallets' : IDL.Vec(LinkedExternalWallet),
    'buyerScore' : IDL.Int,
    'username' : IDL.Text,
    'createdAt' : IDL.Nat,
    'trustLevel' : TrustLevel,
    'role' : UserRole,
    'liabilityBalance' : IDL.Int,
    'avatarUrl' : IDL.Text,
    'liabilityHistory' : IDL.Vec(LiabilityEvent),
    'isBanned' : IDL.Bool,
    'accountClosedAt' : IDL.Nat,
    'suspendedUntil' : IDL.Nat,
    'sellerScore' : IDL.Int,
    'paymentMethods' : IDL.Vec(PaymentMethod),
    'kycTier' : KycTier,
  });
  const PagedResult_1 = IDL.Record({
    'page' : IDL.Nat,
    'totalCount' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(UserProfile),
  });
  const AuditFilter = IDL.Record({
    'targetFilter' : IDL.Opt(IDL.Text),
    'actionFilter' : IDL.Opt(IDL.Text),
    'actorFilter' : IDL.Opt(IDL.Principal),
  });
  const AuditEntry = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'actorId' : IDL.Principal,
    'timestamp' : Timestamp,
    'details' : IDL.Text,
    'targetId' : IDL.Opt(IDL.Text),
  });
  const PagedResult = IDL.Record({
    'page' : IDL.Nat,
    'totalCount' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(AuditEntry),
  });
  const RateCacheEntry = IDL.Record({
    'rateInCents' : IDL.Nat,
    'fetchedAt' : IDL.Int,
  });
  const CategoryAttributeField = IDL.Record({
    'key' : IDL.Text,
    'labelEn' : IDL.Text,
    'labelUk' : IDL.Text,
    'required' : IDL.Bool,
    'fieldType' : IDL.Variant({ 'text' : IDL.Null, 'number' : IDL.Null }),
  });
  const ComplianceNote = IDL.Record({
    'id' : IDL.Nat,
    'note' : IDL.Text,
    'actorId' : IDL.Principal,
    'timestamp' : Timestamp,
  });
  const CyclesStatus = IDL.Record({
    'isWarning' : IDL.Bool,
    'currentBalance' : IDL.Nat,
    'warningThreshold' : IDL.Nat,
    'estimatedDailyBurn' : IDL.Nat,
  });
  const PlatformMetrics__1 = IDL.Record({
    'totalTrades' : IDL.Nat,
    'activeUsersLast24h' : IDL.Nat,
    'totalVolume' : IDL.Float64,
    'monthlyActiveUsers' : IDL.Nat,
    'completedTrades' : IDL.Nat,
    'avgSettlementTimeMin' : IDL.Float64,
    'disputeRate' : IDL.Float64,
    'swapSuccessRate' : IDL.Float64,
  });
  const Result_29 = IDL.Variant({ 'ok' : DigitalDeliveryView, 'err' : Error });
  const DisputeStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'opened' : IDL.Null,
    'escalated_to_admin' : IDL.Null,
    'l2_queued' : IDL.Null,
    'under_review' : IDL.Null,
    'draft' : IDL.Null,
  });
  const DisputeTradeKind = IDL.Variant({
    'physical' : IDL.Null,
    'digital' : IDL.Null,
  });
  const JurorVote = IDL.Record({
    'vote' : JurorVoteChoice,
    'reasoning' : IDL.Text,
    'timestamp' : IDL.Int,
    'jurorPrincipal' : IDL.Principal,
  });
  const JuryView = IDL.Record({
    'jurors' : IDL.Vec(IDL.Principal),
    'votes' : IDL.Vec(JurorVote),
    'deadline' : IDL.Nat,
  });
  const ResolutionOutcome = IDL.Variant({
    'buyer_wins' : IDL.Null,
    'split' : IDL.Null,
    'seller_wins' : IDL.Null,
  });
  const DisputeResolution = IDL.Record({
    'notes' : IDL.Text,
    'outcome' : ResolutionOutcome,
    'resolvedBy' : UserId,
  });
  const DisputeLevel = IDL.Variant({ 'l1' : IDL.Null, 'l2' : IDL.Null });
  const DisputeSlaFlags = IDL.Record({
    'l2TriageOverdue' : IDL.Bool,
    'l2DecisionOverdue' : IDL.Bool,
    'l1SlaOverdue' : IDL.Bool,
  });
  const DisputeReason = IDL.Variant({
    'other' : IDL.Null,
    'item_damaged' : IDL.Null,
    'seller_unresponsive' : IDL.Null,
    'item_differs' : IDL.Null,
    'item_not_received' : IDL.Null,
  });
  const DisputeEvidencePack = IDL.Record({
    'chatThreadLink' : IDL.Opt(IDL.Text),
    'packagePhotoUrls' : IDL.Vec(IDL.Text),
    'fileHash' : IDL.Opt(IDL.Text),
    'downloadTimestamp' : IDL.Nat,
    'ttnScreenshotUrl' : IDL.Opt(IDL.Text),
  });
  const DisputeView = IDL.Record({
    'id' : DisputeId,
    'evidenceUrls' : IDL.Vec(IDL.Text),
    'status' : DisputeStatus,
    'l1SlaDeadline' : IDL.Nat,
    'trade' : TradeId,
    'evidenceAttachments' : IDL.Vec(MediaAttachment),
    'tradeKind' : DisputeTradeKind,
    'initiator' : UserId,
    'jury' : IDL.Opt(JuryView),
    'createdAt' : IDL.Nat,
    'description' : IDL.Text,
    'resolution' : IDL.Opt(DisputeResolution),
    'l2QueuedAt' : IDL.Nat,
    'level' : DisputeLevel,
    'l2DecisionDeadline' : IDL.Nat,
    'slaFlags' : DisputeSlaFlags,
    'l2TriageDeadline' : IDL.Nat,
    'moderatorNotes' : IDL.Vec(IDL.Text),
    'resolvedAt' : IDL.Nat,
    'reason' : DisputeReason,
    'evidencePack' : DisputeEvidencePack,
  });
  const ErrorSeverity = IDL.Variant({
    'warning' : IDL.Null,
    'info' : IDL.Null,
    'error' : IDL.Null,
    'critical' : IDL.Null,
  });
  const ErrorLogEntry = IDL.Record({
    'id' : IDL.Nat,
    'functionName' : IDL.Text,
    'moduleName' : IDL.Text,
    'errorMessage' : IDL.Text,
    'userPrincipal' : IDL.Opt(IDL.Principal),
    'timestamp' : IDL.Int,
    'severity' : ErrorSeverity,
  });
  const ProposalView = IDL.Record({
    'id' : ProposalId,
    'status' : ProposalStatus,
    'noVotes' : IDL.Nat,
    'executedAt' : IDL.Opt(Timestamp),
    'yesVotes' : IDL.Nat,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'deadline' : Timestamp,
    'proposalType' : ProposalType,
    'proposer' : UserId,
    'voterCount' : IDL.Nat,
  });
  const Feedback = IDL.Record({
    'id' : FeedbackId,
    'trade' : TradeId,
    'createdAt' : IDL.Nat,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
    'reviewed' : UserId,
    'reviewer' : UserId,
  });
  const InsuranceCopyTier = IDL.Variant({
    'stake_only' : IDL.Null,
    'capped_reserve' : IDL.Null,
    'no_guarantee' : IDL.Null,
  });
  const ProtectionView = IDL.Record({
    'maxPayoutE8s' : IDL.Nat,
    'tier' : InsuranceCopyTier,
    'dailyRemainingE8s' : IDL.Nat,
    'insuranceOffered' : IDL.Bool,
    'liquidBalanceE8s' : IDL.Nat,
    'tradeAmountUsdCents' : IDL.Nat,
  });
  const ReserveLedgerView = IDL.Record({
    'pendingPayouts' : IDL.Nat,
    'liquidBalanceE8s' : IDL.Nat,
    'accrualCount' : IDL.Nat,
  });
  const JurorDashboardEntry = IDL.Record({
    'deadline' : IDL.Nat,
    'tradeId' : TradeId,
    'sellerVotes' : IDL.Nat,
    'hasVoted' : IDL.Bool,
    'totalJurors' : IDL.Nat,
    'buyerVotes' : IDL.Nat,
    'reason' : DisputeReason,
    'disputeId' : DisputeId,
  });
  const JurorStats = IDL.Record({
    'principal' : IDL.Principal,
    'successRate' : IDL.Float64,
    'activeCount' : IDL.Nat,
    'stakedAmount' : IDL.Float64,
    'registeredAt' : IDL.Nat,
    'resolvedCount' : IDL.Nat,
  });
  const Result_28 = IDL.Variant({ 'ok' : IDL.Vec(JurorStats), 'err' : Error });
  const LinkPreview = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Opt(IDL.Text),
    'fetchedAt' : IDL.Nat,
    'description' : IDL.Opt(IDL.Text),
    'siteName' : IDL.Opt(IDL.Text),
    'imageUrl' : IDL.Opt(IDL.Text),
  });
  const Result_27 = IDL.Variant({ 'ok' : LinkPreview, 'err' : Error });
  const ListingInquiryMessageId = IDL.Nat;
  const ListingInquiryId = IDL.Nat;
  const ListingInquiryMessage = IDL.Record({
    'id' : ListingInquiryMessageId,
    'content' : IDL.Text,
    'createdAt' : IDL.Nat,
    'sender' : UserId,
    'inquiryId' : ListingInquiryId,
  });
  const Result_26 = IDL.Variant({
    'ok' : IDL.Vec(ListingInquiryMessage),
    'err' : Error,
  });
  const ListingStakeStatus = IDL.Variant({
    'locked' : IDL.Null,
    'seized' : IDL.Null,
    'released' : IDL.Null,
  });
  const ListingStakeView = IDL.Record({
    'status' : ListingStakeStatus,
    'token' : TradeToken,
    'listingId' : ListingId,
    'seller' : UserId,
    'lockedAt' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const Result_25 = IDL.Variant({
    'ok' : IDL.Vec(
      IDL.Record({
        'id' : IDL.Text,
        'name' : IDL.Text,
        'type' : IDL.Text,
        'address' : IDL.Text,
      })
    ),
    'err' : Error,
  });
  const MetricsSummary = IDL.Record({
    'totalTrades' : IDL.Nat,
    'totalVolume' : IDL.Nat,
    'p95LatencyMs' : IDL.Nat,
    'errorRate' : IDL.Float64,
    'memoryUsage' : IDL.Nat,
    'activeTrades' : IDL.Nat,
    'avgTradeValue' : IDL.Nat,
    'disputeRate' : IDL.Float64,
    'totalRevenue' : IDL.Nat,
    'cyclesBalance' : IDL.Nat,
  });
  const Message = IDL.Record({
    'id' : MessageId,
    'attachmentUrl' : IDL.Opt(IDL.Text),
    'trade' : TradeId,
    'content' : IDL.Text,
    'sender' : UserId,
    'sentAt' : IDL.Nat,
    'attachments' : IDL.Vec(MediaAttachment),
  });
  const ModuleMetricsView = IDL.Record({
    'memoryUsedBytes' : IDL.Nat,
    'cyclesConsumed' : IDL.Nat,
    'moduleName' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'errorCount' : IDL.Nat,
    'requestCount' : IDL.Nat,
  });
  const Result_24 = IDL.Variant({
    'ok' : IDL.Vec(JurorDashboardEntry),
    'err' : Error,
  });
  const StakeBalanceView = IDL.Record({
    'locked' : IDL.Nat,
    'available' : IDL.Nat,
  });
  const TxHistoryFilter = IDL.Record({
    'to' : IDL.Opt(Timestamp),
    'status' : IDL.Opt(TradeStatus),
    'token' : IDL.Opt(TradeToken),
    'from' : IDL.Opt(Timestamp),
  });
  const Page = IDL.Record({
    'totalCount' : IDL.Nat,
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
    'items' : IDL.Vec(TradeView),
  });
  const NovaPoshtaBranch = IDL.Record({
    'ref' : IDL.Text,
    'cityRef' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'schedule' : IDL.Opt(IDL.Text),
  });
  const Result_23 = IDL.Variant({
    'ok' : IDL.Vec(NovaPoshtaBranch),
    'err' : Error,
  });
  const Result_22 = IDL.Variant({ 'ok' : IDL.Vec(DisputeView), 'err' : Error });
  const PaymentVerificationStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'failed' : IDL.Null,
  });
  const PaymentVerificationResult = IDL.Record({
    'status' : PaymentVerificationStatus,
    'blockNumber' : IDL.Nat,
    'confirmedAmount' : IDL.Float64,
    'confirmedRecipient' : IDL.Text,
    'txHash' : IDL.Text,
    'errorReason' : IDL.Opt(IDL.Text),
  });
  const PlatformMetrics = IDL.Record({
    'totalTrades' : IDL.Nat,
    'activeUsersLast30d' : IDL.Nat,
    'avgTradeCompletionMs' : IDL.Nat,
    'totalListings' : IDL.Nat,
    'tradesByToken' : IDL.Vec(IDL.Tuple(TradeToken, IDL.Nat)),
    'disputeRatePct' : IDL.Nat,
  });
  const SavedSearch = IDL.Record({
    'id' : SavedSearchId,
    'alertsEnabled' : IDL.Bool,
    'owner' : UserId,
    'paramsJson' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Nat,
  });
  const SettlementPath = IDL.Variant({
    'on_chain_ck' : IDL.Null,
    'manual' : IDL.Null,
  });
  const SettlementCopyTier = IDL.Variant({
    'on_chain_recovery' : IDL.Null,
    'partial_recovery' : IDL.Null,
    'manual_restriction_only' : IDL.Null,
  });
  const SellerFaultSettlementView = IDL.Record({
    'liabilityId' : IDL.Opt(IDL.Nat),
    'buyerObligationCents' : IDL.Nat,
    'residualCents' : IDL.Nat,
    'path' : SettlementPath,
    'insurancePayoutId' : IDL.Opt(IDL.Nat),
    'stakeSeizedCents' : IDL.Nat,
    'tradeId' : TradeId,
    'onChainRefundExpected' : IDL.Bool,
    'copyTier' : SettlementCopyTier,
  });
  const Result_21 = IDL.Variant({ 'ok' : IDL.Int, 'err' : Error });
  const ShippingOption = IDL.Record({
    'cost' : IDL.Float64,
    'deliveryDays' : IDL.Nat,
    'available' : IDL.Bool,
    'carrier' : ShippingCarrier,
    'costNat' : IDL.Nat,
  });
  const CarrierInfo = IDL.Record({
    'displayName' : IDL.Text,
    'description' : IDL.Text,
    'carrier' : ShippingCarrier,
  });
  const TokenInfo = IDL.Record({
    'decimals' : IDL.Nat,
    'token' : TradeToken,
    'name' : IDL.Text,
    'network' : IDL.Text,
    'isNative' : IDL.Bool,
    'priority' : IDL.Nat,
    'symbol' : IDL.Text,
  });
  const TradeFeeQuote = IDL.Record({
    'usesDefaultFeeBps' : IDL.Bool,
    'token' : TradeToken,
    'totalBuyerAmount' : IDL.Nat,
    'platformFeeAmount' : IDL.Nat,
    'platformFeeBps' : IDL.Nat,
    'itemPrice' : IDL.Nat,
  });
  const NotificationEvent = IDL.Record({
    'id' : IDL.Nat,
    'read' : IDL.Bool,
    'tradeId' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : IDL.Nat,
    'eventType' : IDL.Text,
  });
  const TradePaymentStatus = IDL.Record({
    'status' : TradeStatus,
    'isManual' : IDL.Bool,
    'token' : TradeToken,
    'formattedAmount' : IDL.Text,
    'tradeId' : TradeId,
    'tokenInfo' : IDL.Opt(TokenInfo),
    'amount' : IDL.Nat,
    'verificationResult' : IDL.Opt(PaymentVerificationResult),
  });
  const WithdrawalRecord = IDL.Record({
    'id' : IDL.Nat,
    'executedAt' : Timestamp,
    'recipient' : IDL.Principal,
    'amount' : IDL.Nat,
    'proposalId' : IDL.Nat,
  });
  const Result_20 = IDL.Variant({
    'ok' : IDL.Vec(
      IDL.Record({
        'name' : IDL.Text,
        'address' : IDL.Text,
        'index' : IDL.Text,
      })
    ),
    'err' : Error,
  });
  const Result_19 = IDL.Variant({
    'ok' : IDL.Record({
      'status' : IDL.Text,
      'trackingNumber' : IDL.Text,
      'estimatedDelivery' : IDL.Opt(IDL.Text),
      'statusHistory' : IDL.Vec(
        IDL.Record({ 'status' : IDL.Text, 'timestamp' : IDL.Int })
      ),
      'isDelivered' : IDL.Bool,
      'carrier' : IDL.Text,
    }),
    'err' : Error,
  });
  const ReputationStats = IDL.Record({
    'reputationScore' : IDL.Int,
    'buyerScore' : IDL.Int,
    'trustLevel' : TrustLevel,
    'averageRating' : IDL.Float64,
    'completedTrades' : IDL.Nat,
    'disputeRate' : IDL.Float64,
    'sellerScore' : IDL.Int,
  });
  const ChainType = IDL.Variant({
    'SPL' : IDL.Null,
    'BEP20' : IDL.Null,
    'TRC20' : IDL.Null,
    'Polygon' : IDL.Null,
    'ERC20' : IDL.Null,
    'Avalanche' : IDL.Null,
  });
  const VaultAddressView = IDL.Record({
    'chain' : ChainType,
    'network' : IDL.Text,
    'tokenSymbol' : IDL.Text,
    'address' : IDL.Text,
    'derivedAt' : IDL.Int,
  });
  const BalanceView = IDL.Record({
    'chain' : ChainType,
    'error' : IDL.Opt(IDL.Text),
    'usdtBalance' : IDL.Nat,
    'usdcBalance' : IDL.Nat,
    'lastChecked' : IDL.Int,
  });
  const Result_18 = IDL.Variant({ 'ok' : TradeId, 'err' : Error });
  const Result_17 = IDL.Variant({ 'ok' : FeedbackId, 'err' : Error });
  const Result_14 = IDL.Variant({ 'ok' : LinkedExternalWallet, 'err' : Error });
  const CategoryNode = IDL.Record({
    'id' : CategoryId,
    'labelEn' : IDL.Text,
    'labelUk' : IDL.Text,
    'slug' : IDL.Text,
    'legacyCategory' : ListingCategory,
    'parentId' : IDL.Opt(CategoryId),
  });
  const Result_16 = IDL.Variant({ 'ok' : DisputeId, 'err' : Error });
  const DigitalFileAsset = IDL.Record({
    'contentHash' : IDL.Opt(IDL.Text),
    'mimeType' : IDL.Text,
    'blobHash' : IDL.Text,
    'blobUrlEncrypted' : IDL.Text,
    'fileVersionId' : IDL.Nat,
    'sizeBytes' : IDL.Nat,
    'registeredAt' : IDL.Nat,
    'dekEncrypted' : IDL.Text,
  });
  const Result_13 = IDL.Variant({ 'ok' : DigitalFileAsset, 'err' : Error });
  const Result_9 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : Error });
  const WalletLinkChallengeView = IDL.Record({
    'expiresAt' : IDL.Nat,
    'chain' : WalletChain,
    'challengeId' : IDL.Nat,
    'message' : IDL.Text,
    'address' : IDL.Text,
    'sessionId' : IDL.Text,
    'purpose' : WalletLinkPurpose,
  });
  const Result_12 = IDL.Variant({
    'ok' : WalletLinkChallengeView,
    'err' : Error,
  });
  const Result_10 = IDL.Variant({ 'ok' : SavedSearch, 'err' : Error });
  const Result_8 = IDL.Variant({ 'ok' : ListingInquiryMessage, 'err' : Error });
  const Result_7 = IDL.Variant({ 'ok' : Message, 'err' : Error });
  const Result_6 = IDL.Variant({ 'ok' : UserProfile, 'err' : Error });
  const Result_5 = IDL.Variant({ 'ok' : PayoutWalletSnapshot, 'err' : Error });
  const TradeCapTier = IDL.Variant({
    'high_value_ck' : IDL.Null,
    'rejected' : IDL.Null,
    'elevated' : IDL.Null,
    'standard' : IDL.Null,
  });
  const TradeCapTierCheck = IDL.Record({
    'sellerVerifiedTierOk' : IDL.Bool,
    'tier' : TradeCapTier,
    'elevatedStakeRequired' : IDL.Nat,
    'allowed' : IDL.Bool,
    'sellerStakeOk' : IDL.Bool,
    'ckOnlyRequired' : IDL.Bool,
    'blockReason' : IDL.Opt(IDL.Text),
    'usdCents' : IDL.Nat,
    'gateCRequired' : IDL.Bool,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpResponse = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const ShipHttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const ShipHttpResponse = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(ShipHttpHeader),
  });
  const VaultHttpResponse = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })),
  });
  const Result_1 = IDL.Variant({
    'ok' : IDL.Record({
      'active' : IDL.Bool,
      'txCount' : IDL.Nat,
      'verifiedAt' : Timestamp,
    }),
    'err' : Error,
  });
  const Result_2 = IDL.Variant({
    'ok' : PaymentVerificationResult,
    'err' : Error,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_transformResponse' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : IDL.Record({
              'status' : IDL.Nat,
              'body' : IDL.Vec(IDL.Nat8),
              'headers' : IDL.Vec(
                IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
              ),
            }),
          }),
        ],
        [
          IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        ],
        ['query'],
      ),
    'addComplianceNote' : IDL.Func([UserId, IDL.Text], [], []),
    'addEvidence' : IDL.Func(
        [DisputeId, IDL.Vec(MediaAttachment)],
        [Result],
        [],
      ),
    'addFavorite' : IDL.Func([ListingId], [Result], []),
    'addModeratorNote' : IDL.Func([DisputeId, IDL.Text], [Result], []),
    'addPaymentMethod' : IDL.Func(
        [TradeToken, IDL.Text, IDL.Bool],
        [Result_37],
        [],
      ),
    'adminApproveInsurancePayout' : IDL.Func([IDL.Nat], [Result_35], []),
    'adminClearUserLiability' : IDL.Func([UserId, IDL.Text], [Result], []),
    'adminGetAllTrades' : IDL.Func([], [IDL.Vec(TradeView)], ['query']),
    'adminGetGateCChecklist' : IDL.Func([], [GateCChecklistView], ['query']),
    'adminListLiabilities' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [Result_36],
        ['query'],
      ),
    'adminPartialClearLiability' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [Result],
        [],
      ),
    'adminPromoteListing' : IDL.Func([ListingId], [Result], []),
    'adminRemoveListing' : IDL.Func([ListingId, IDL.Text], [Result], []),
    'adminRequestInsurancePayout' : IDL.Func(
        [TradeId, IDL.Principal, IDL.Nat, IDL.Nat, TradeToken],
        [Result_35],
        [],
      ),
    'adminResolveInsuranceFraudReview' : IDL.Func(
        [IDL.Nat, IDL.Bool, IDL.Text, IDL.Text],
        [Result_35],
        [],
      ),
    'adminSetTrustlessEscrowEnabled' : IDL.Func(
        [IDL.Bool, IDL.Text],
        [Result],
        [],
      ),
    'adminSetUserKycTier' : IDL.Func([UserId, KycTier], [Result], []),
    'adminUpdateGateCChecklist' : IDL.Func(
        [
          IDL.Opt(IDL.Bool),
          IDL.Opt(IDL.Bool),
          IDL.Opt(IDL.Bool),
          IDL.Opt(IDL.Bool),
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
    'appealDispute' : IDL.Func([DisputeId, IDL.Text], [Result], []),
    'assignJurors' : IDL.Func([DisputeId], [Result], []),
    'banUser' : IDL.Func([UserId, IDL.Text], [], []),
    'bumpListing' : IDL.Func([ListingId], [Result], []),
    'buyerCancelBeforeShipment' : IDL.Func([TradeId], [Result_34], []),
    'calculateShippingCost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, ShippingServiceType],
        [
          IDL.Variant({
            'ok' : IDL.Record({ 'transitDays' : IDL.Nat, 'costUAH' : IDL.Nat }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'canConfirmDelivery' : IDL.Func([TradeId], [IDL.Bool], []),
    'castJurorVote' : IDL.Func(
        [DisputeId, JurorVoteChoice, IDL.Text],
        [Result],
        [],
      ),
    'checkAndExpireTimeouts' : IDL.Func([], [IDL.Nat], []),
    'checkAndReleaseListingStakeAfterClaim' : IDL.Func(
        [ListingId, TradeId],
        [Result_15],
        [],
      ),
    'checkDigitalInspectionDeadline' : IDL.Func([TradeId], [Result_15], []),
    'checkFulfillmentDeadlines' : IDL.Func(
        [],
        [
          IDL.Record({
            'disputeL1Escalations' : IDL.Nat,
            'digitalAutoCompletions' : IDL.Nat,
            'autoCompletions' : IDL.Nat,
            'shipByEscalations' : IDL.Nat,
          }),
        ],
        [],
      ),
    'checkHandshakeTimeouts' : IDL.Func([], [IDL.Nat], []),
    'checkJuryDeadlines' : IDL.Func([], [IDL.Nat], []),
    'checkPaymentIntentExpiry' : IDL.Func([], [IDL.Nat], []),
    'cleanupResolvedListings' : IDL.Func(
        [],
        [
          IDL.Record({
            'deletedCount' : IDL.Nat,
            'skippedByDispute' : IDL.Nat,
            'photosToDelete' : IDL.Vec(IDL.Text),
          }),
        ],
        [],
      ),
    'closeProposal' : IDL.Func([ProposalId], [Result_33], []),
    'confirmBuyerReceipt' : IDL.Func([TradeId], [Result], []),
    'confirmPaymentReceived' : IDL.Func([TradeId], [Result], []),
    'confirmPaymentSent' : IDL.Func([TradeId], [Result], []),
    'confirmSellerHandshake' : IDL.Func([TradeId], [Result], []),
    'createListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ListingCategory,
          IDL.Opt(CategoryId),
          IDL.Nat,
          TradeToken,
          ItemCondition,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(ShippingMethod),
          IDL.Bool,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(PackageDetails),
          IDL.Opt(NovaPoshtaConfig),
          IDL.Opt(UkrposhtaConfig),
          IDL.Opt(MeestConfig),
          IDL.Vec(CategoryAttributeValue),
        ],
        [Result_32],
        [],
      ),
    'createMeestTTN' : IDL.Func([TradeId], [Result_11], []),
    'createMeestWaybill' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createNovaPoshtaTTN' : IDL.Func([TradeId], [Result_11], []),
    'createPaymentIntent' : IDL.Func(
        [TradeId, IDL.Opt(IDL.Nat), PaymentSettlementPath],
        [Result_31],
        [],
      ),
    'createProposal' : IDL.Func([ProposalType, IDL.Text], [Result_30], []),
    'createUkrPoshtaWaybill' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createUkrposhtaTTN' : IDL.Func([TradeId], [Result_11], []),
    'createWaybill' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Nat,
          ShippingServiceType,
        ],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deactivateListing' : IDL.Func([ListingId], [Result], []),
    'declineSellerHandshake' : IDL.Func([TradeId], [Result], []),
    'deleteMyAccount' : IDL.Func([IDL.Text], [Result], []),
    'deleteSavedSearch' : IDL.Func([SavedSearchId], [Result], []),
    'demoteFromModerator' : IDL.Func([UserId], [], []),
    'depositStake' : IDL.Func([TradeToken, IDL.Nat], [Result], []),
    'escalateDisputeToL2' : IDL.Func([DisputeId], [Result], []),
    'estimateTokenAmount' : IDL.Func(
        [IDL.Nat, TradeToken],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'executeProposal' : IDL.Func([ProposalId], [Result], []),
    'exportMyAccountData' : IDL.Func([], [AccountExportBundle], ['query']),
    'getAllUsers' : IDL.Func(
        [IDL.Nat, IDL.Nat, UserFilter],
        [PagedResult_1],
        [],
      ),
    'getAuditLog' : IDL.Func(
        [IDL.Nat, IDL.Nat, AuditFilter],
        [PagedResult],
        ['query'],
      ),
    'getCachedRate' : IDL.Func(
        [TradeToken],
        [IDL.Opt(RateCacheEntry)],
        ['query'],
      ),
    'getCategoryAttributeSchema' : IDL.Func(
        [CategoryId],
        [IDL.Vec(CategoryAttributeField)],
        ['query'],
      ),
    'getComplianceNotes' : IDL.Func(
        [UserId],
        [IDL.Vec(ComplianceNote)],
        ['query'],
      ),
    'getCyclesStatus' : IDL.Func([], [CyclesStatus], ['query']),
    'getDashboardMetrics' : IDL.Func([], [PlatformMetrics__1], ['query']),
    'getDigitalDelivery' : IDL.Func([TradeId], [Result_29], []),
    'getDispute' : IDL.Func([DisputeId], [IDL.Opt(DisputeView)], ['query']),
    'getDisputeJurors' : IDL.Func([DisputeId], [IDL.Opt(JuryView)], ['query']),
    'getDisputesByTrade' : IDL.Func(
        [TradeId],
        [IDL.Vec(DisputeView)],
        ['query'],
      ),
    'getEndpointErrorRate' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Float64],
        ['query'],
      ),
    'getErrorLog' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Vec(ErrorLogEntry)],
        ['query'],
      ),
    'getExecutionHistory' : IDL.Func([], [IDL.Vec(ProposalView)], ['query']),
    'getExpiredListings' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ListingCard)],
        ['query'],
      ),
    'getExplorerApiKeyStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'bscScanConfigured' : IDL.Bool,
            'infuraConfigured' : IDL.Bool,
            'tronGridConfigured' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getFavoriteListings' : IDL.Func([], [IDL.Vec(ListingCard)], ['query']),
    'getFeedbackForTrade' : IDL.Func([TradeId], [IDL.Vec(Feedback)], ['query']),
    'getInsurancePayoutRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PayoutRequestView)],
        ['query'],
      ),
    'getInsuranceProtectionView' : IDL.Func(
        [IDL.Nat, TradeToken],
        [ProtectionView],
        ['query'],
      ),
    'getInsuranceReserveLedger' : IDL.Func([], [ReserveLedgerView], ['query']),
    'getJurorDashboard' : IDL.Func(
        [],
        [IDL.Vec(JurorDashboardEntry)],
        ['query'],
      ),
    'getJuryPool' : IDL.Func([], [Result_28], ['query']),
    'getLinkPreview' : IDL.Func([IDL.Text], [Result_27], []),
    'getLinkedWallets' : IDL.Func(
        [],
        [IDL.Vec(LinkedExternalWallet)],
        ['query'],
      ),
    'getLinkedWalletsForToken' : IDL.Func(
        [TradeToken],
        [IDL.Vec(LinkedExternalWallet)],
        ['query'],
      ),
    'getListing' : IDL.Func([ListingId], [IDL.Opt(ListingCard)], ['query']),
    'getListingInquiryMessages' : IDL.Func(
        [ListingId, UserId],
        [Result_26],
        ['query'],
      ),
    'getListingStake' : IDL.Func(
        [ListingId],
        [IDL.Opt(ListingStakeView)],
        ['query'],
      ),
    'getListingsByUser' : IDL.Func(
        [UserId, IDL.Nat, IDL.Nat],
        [IDL.Vec(ListingCard)],
        ['query'],
      ),
    'getMeestPUDOs' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [Result_25],
        [],
      ),
    'getMetricsSummary' : IDL.Func([], [MetricsSummary], ['query']),
    'getModeratorThread' : IDL.Func([TradeId], [IDL.Vec(Message)], ['query']),
    'getModuleMetrics' : IDL.Func([], [IDL.Vec(ModuleMetricsView)], ['query']),
    'getMyDisputes' : IDL.Func([], [IDL.Vec(DisputeView)], ['query']),
    'getMyFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getMyJurorDashboard' : IDL.Func([], [Result_24], ['query']),
    'getMyListings' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ListingCard)],
        ['query'],
      ),
    'getMyPaymentMethods' : IDL.Func([], [IDL.Vec(PaymentMethod)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMyStakeBalance' : IDL.Func([TradeToken], [StakeBalanceView], ['query']),
    'getMyTrades' : IDL.Func(
        [
          IDL.Variant({
            'all' : IDL.Null,
            'seller' : IDL.Null,
            'buyer' : IDL.Null,
          }),
        ],
        [IDL.Vec(TradeView)],
        ['query'],
      ),
    'getMyTransactionHistory' : IDL.Func(
        [TxHistoryFilter, IDL.Nat, IDL.Nat],
        [Page],
        ['query'],
      ),
    'getNovaPoshtaBranches' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [Result_23],
        [],
      ),
    'getNovaPoshtaCityRef' : IDL.Func([IDL.Text], [Result_11], []),
    'getOpenDisputeQueue' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [Result_22],
        ['query'],
      ),
    'getP95Latency' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], ['query']),
    'getPaymentMethods' : IDL.Func([], [IDL.Vec(PaymentMethod)], ['query']),
    'getPaymentVerificationStatus' : IDL.Func(
        [TradeId],
        [IDL.Opt(PaymentVerificationResult)],
        ['query'],
      ),
    'getPlatformFlags' : IDL.Func(
        [],
        [
          IDL.Record({
            'ckUsdcLedgerId' : IDL.Text,
            'ckUsdtLedgerId' : IDL.Text,
            'trustlessEscrowEnabled' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getPlatformMetrics' : IDL.Func([], [PlatformMetrics], ['query']),
    'getProposal' : IDL.Func([ProposalId], [IDL.Opt(ProposalView)], ['query']),
    'getProposals' : IDL.Func(
        [IDL.Opt(ProposalStatus)],
        [IDL.Vec(ProposalView)],
        ['query'],
      ),
    'getPublicListingsByUser' : IDL.Func(
        [UserId, IDL.Nat, IDL.Nat],
        [IDL.Vec(ListingCard)],
        ['query'],
      ),
    'getRequestRate' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], ['query']),
    'getRequiredListingStake' : IDL.Func(
        [IDL.Nat, TradeToken],
        [IDL.Nat],
        ['query'],
      ),
    'getSavedSearches' : IDL.Func([], [IDL.Vec(SavedSearch)], ['query']),
    'getSellerFaultSettlementView' : IDL.Func(
        [TradeId],
        [IDL.Opt(SellerFaultSettlementView)],
        ['query'],
      ),
    'getSellerLiability' : IDL.Func([IDL.Principal], [Result_21], ['query']),
    'getSellerPaymentMethodsForTrade' : IDL.Func(
        [TradeId],
        [IDL.Vec(PaymentMethod)],
        ['query'],
      ),
    'getShippingOptions' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(ShippingOption), 'err' : IDL.Text })],
        [],
      ),
    'getStakeOnChainEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'getSupportedCarriers' : IDL.Func([], [IDL.Vec(CarrierInfo)], ['query']),
    'getSupportedTokens' : IDL.Func([], [IDL.Vec(TokenInfo)], ['query']),
    'getSystemSettings' : IDL.Func(
        [],
        [
          IDL.Record({
            'maxListingPriceUSD' : IDL.Nat,
            'paymentTimeoutHours' : IDL.Nat,
            'allowedTokens' : IDL.Vec(TradeToken),
            'cyclesBalanceThreshold' : IDL.Nat,
            'minTradeAmountUSD' : IDL.Nat,
            'errorRateThreshold' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getTokenInfo' : IDL.Func([TradeToken], [IDL.Opt(TokenInfo)], ['query']),
    'getTrade' : IDL.Func([TradeId], [IDL.Opt(TradeView)], ['query']),
    'getTradeFeeQuote' : IDL.Func(
        [ListingId],
        [IDL.Opt(TradeFeeQuote)],
        ['query'],
      ),
    'getTradeMessages' : IDL.Func(
        [TradeId, IDL.Nat, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getTradeNotifications' : IDL.Func(
        [],
        [IDL.Vec(NotificationEvent)],
        ['query'],
      ),
    'getTradePaymentStatus' : IDL.Func(
        [TradeId],
        [IDL.Opt(TradePaymentStatus)],
        ['query'],
      ),
    'getTradesByListing' : IDL.Func(
        [ListingId],
        [IDL.Vec(TradeView)],
        ['query'],
      ),
    'getTradesPerDay' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat }))],
        ['query'],
      ),
    'getTreasuryBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getTreasuryWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRecord)],
        ['query'],
      ),
    'getUkrposhtaOffices' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [Result_20],
        [],
      ),
    'getUnifiedTrackingInfo' : IDL.Func([TradeId], [Result_19], []),
    'getUnreadCount' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(TradeId, IDL.Nat))],
        ['query'],
      ),
    'getUserFeedback' : IDL.Func([UserId], [IDL.Vec(Feedback)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserReputationStats' : IDL.Func(
        [UserId],
        [IDL.Opt(ReputationStats)],
        ['query'],
      ),
    'getVaultAddresses' : IDL.Func([], [IDL.Vec(VaultAddressView)], []),
    'getVaultBalance' : IDL.Func(
        [ChainType],
        [IDL.Opt(BalanceView)],
        ['query'],
      ),
    'incrementListingView' : IDL.Func([ListingId], [], []),
    'initiateOnChainTrade' : IDL.Func([TradeId], [Result_18], []),
    'initiateTrade' : IDL.Func(
        [ListingId, TradeToken, IDL.Opt(ShippingSelection)],
        [Result_18],
        [],
      ),
    'isListingFavorite' : IDL.Func([ListingId], [IDL.Bool], ['query']),
    'leaveFeedback' : IDL.Func(
        [TradeId, UserId, IDL.Nat, IDL.Text],
        [Result_17],
        [],
      ),
    'linkExternalWallet' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [Result_14],
        [],
      ),
    'listCategories' : IDL.Func([], [IDL.Vec(CategoryNode)], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [Result], []),
    'markNotificationRead' : IDL.Func([IDL.Nat], [Result], []),
    'markShipped' : IDL.Func([TradeId, IDL.Text], [Result], []),
    'markTradeAsRead' : IDL.Func([TradeId], [], []),
    'openDigitalDispute' : IDL.Func([TradeId, IDL.Text], [Result_16], []),
    'openDispute' : IDL.Func(
        [TradeId, DisputeReason, IDL.Text, DisputeEvidencePack],
        [Result_16],
        [],
      ),
    'platformFeeBps' : IDL.Func([], [IDL.Nat], ['query']),
    'processDisputeSlaEscalations' : IDL.Func([], [IDL.Nat], []),
    'promoteToModerator' : IDL.Func([UserId], [], []),
    'proposeCancelTrade' : IDL.Func([TradeId], [Result_15], []),
    'publishListing' : IDL.Func([ListingId], [Result], []),
    'reactivateListing' : IDL.Func([ListingId], [Result], []),
    'recordRequest' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], ['oneway']),
    'recordTreasuryFee' : IDL.Func([TradeId, IDL.Nat, TradeToken], [], []),
    'recoverWalletLink' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [Result_14],
        [],
      ),
    'refreshRates' : IDL.Func([], [IDL.Nat], []),
    'refreshVaultBalance' : IDL.Func([ChainType], [BalanceView], []),
    'registerAsJuror' : IDL.Func([IDL.Float64], [Result], []),
    'registerDigitalFile' : IDL.Func(
        [
          ListingId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [Result_13],
        [],
      ),
    'releaseListingStake' : IDL.Func([ListingId], [Result_9], []),
    'removeFavorite' : IDL.Func([ListingId], [Result], []),
    'removeListingByAdmin' : IDL.Func([ListingId, IDL.Text], [], []),
    'reopenDispute' : IDL.Func([DisputeId], [Result], []),
    'reportListing' : IDL.Func([ListingId, IDL.Text], [Result], []),
    'requestRefund' : IDL.Func([TradeId], [Result], []),
    'requestWalletLinkNonce' : IDL.Func(
        [WalletChain, IDL.Text, WalletLinkPurpose, IDL.Text],
        [Result_12],
        [],
      ),
    'resolveDispute' : IDL.Func(
        [DisputeId, ResolutionOutcome, IDL.Text],
        [Result],
        [],
      ),
    'resolveDisputeEscrow' : IDL.Func(
        [DisputeId, ResolutionOutcome],
        [Result],
        [],
      ),
    'retryMeestTTNCreation' : IDL.Func([TradeId], [Result_11], []),
    'retryPendingOnChainSettlements' : IDL.Func(
        [],
        [
          IDL.Record({
            'attempted' : IDL.Nat,
            'failed' : IDL.Nat,
            'succeeded' : IDL.Nat,
          }),
        ],
        [],
      ),
    'retryTTNCreation' : IDL.Func([TradeId], [Result_11], []),
    'retryUkrposhtaTTNCreation' : IDL.Func([TradeId], [Result_11], []),
    'saveSearch' : IDL.Func([IDL.Text, IDL.Text], [Result_10], []),
    'searchListings' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(ListingCategory),
          IDL.Opt(CategoryId),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(ItemCondition),
          IDL.Opt(ShippingCarrier),
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(TradeToken),
        ],
        [IDL.Vec(ListingCard)],
        ['query'],
      ),
    'seizeListingStake' : IDL.Func(
        [ListingId, IDL.Opt(IDL.Text)],
        [Result_9],
        [],
      ),
    'sendListingInquiry' : IDL.Func([ListingId, IDL.Text], [Result_8], []),
    'sendListingInquiryReply' : IDL.Func(
        [ListingId, UserId, IDL.Text],
        [Result_8],
        [],
      ),
    'sendMessage' : IDL.Func(
        [TradeId, IDL.Text, IDL.Vec(MediaAttachment)],
        [Result_7],
        [],
      ),
    'setAvalancheApiKey' : IDL.Func([IDL.Text], [], []),
    'setBscScanApiKey' : IDL.Func([IDL.Text], [], []),
    'setDisputeUnderReview' : IDL.Func([DisputeId], [Result], []),
    'setInfuraApiKey' : IDL.Func([IDL.Text], [], []),
    'setMeestApiKey' : IDL.Func([IDL.Text], [], []),
    'setMyProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Result_6],
        [],
      ),
    'setNovaPoshtaApiKey' : IDL.Func([IDL.Text], [], []),
    'setPolygonApiKey' : IDL.Func([IDL.Text], [], []),
    'setSavedSearchAlerts' : IDL.Func([SavedSearchId, IDL.Bool], [Result], []),
    'setSolanaRpcUrl' : IDL.Func([IDL.Text], [], []),
    'setTronGridApiKey' : IDL.Func([IDL.Text], [], []),
    'setUkrPoshtaApiKey' : IDL.Func([IDL.Text], [], []),
    'snapshotPayoutWallet' : IDL.Func([TradeId, IDL.Nat], [Result_5], []),
    'submitJurorVote' : IDL.Func(
        [DisputeId, JurorVoteChoice, IDL.Text],
        [Result],
        [],
      ),
    'suspendUser' : IDL.Func([UserId, Timestamp, IDL.Text], [], []),
    'trackMeestShipment' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'trackShipment' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'trackUkrPoshtaShipment' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'tradeCapTierCheck' : IDL.Func(
        [ListingId, TradeToken],
        [TradeCapTierCheck],
        ['query'],
      ),
    'transformJsonRpcResponse' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : HttpResponse,
          }),
        ],
        [HttpResponse],
        ['query'],
      ),
    'transformPaymentResponse' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : HttpResponse,
          }),
        ],
        [HttpResponse],
        ['query'],
      ),
    'transformShippingResponse' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : ShipHttpResponse,
          }),
        ],
        [ShipHttpResponse],
        ['query'],
      ),
    'transformVaultResponse' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : VaultHttpResponse,
          }),
        ],
        [VaultHttpResponse],
        ['query'],
      ),
    'unbanUser' : IDL.Func([UserId], [], []),
    'unlinkExternalWallet' : IDL.Func([IDL.Nat], [Result], []),
    'unregisterJuror' : IDL.Func([], [Result], []),
    'updateListing' : IDL.Func(
        [
          ListingId,
          IDL.Text,
          IDL.Text,
          ListingCategory,
          IDL.Opt(CategoryId),
          IDL.Nat,
          TradeToken,
          ItemCondition,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(ShippingMethod),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(PackageDetails),
          IDL.Opt(NovaPoshtaConfig),
          IDL.Opt(UkrposhtaConfig),
          IDL.Opt(MeestConfig),
          IDL.Vec(CategoryAttributeValue),
        ],
        [Result],
        [],
      ),
    'updateSystemSettings' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Vec(TradeToken), IDL.Nat, IDL.Nat, IDL.Float64],
        [],
        [],
      ),
    'verifyEvmAddress' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'verifyPayment' : IDL.Func([TradeId, IDL.Text, TradeToken], [Result_2], []),
    'verifySolanaAddress' : IDL.Func([IDL.Text], [Result_1], []),
    'verifyTradePayment' : IDL.Func(
        [TradeId, IDL.Text, IDL.Text],
        [Result_2],
        [],
      ),
    'verifyTradePaymentExplorer' : IDL.Func(
        [TradeId, IDL.Text, TradeToken],
        [Result_2],
        [],
      ),
    'verifyTronAddress' : IDL.Func([IDL.Text], [Result_1], []),
    'voteOnProposal' : IDL.Func([ProposalId, IDL.Bool], [Result], []),
    'withdrawStake' : IDL.Func([TradeToken, IDL.Nat], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };