/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccountExportBundle {
  'favoriteListingIds' : Array<ListingId>,
  'principal' : UserId,
  'messages' : Array<AccountMessageExport>,
  'listings' : Array<ListingCardExport>,
  'trades' : Array<TradeViewExport>,
  'feedback' : Array<FeedbackExport>,
  'exportedAt' : ExportInt,
  'hasProfile' : boolean,
  'savedSearches' : Array<SavedSearchExport>,
  'profile' : UserProfileExport,
}
export interface AccountMessageExport {
  'attachmentUrl' : [] | [string],
  'content' : string,
  'messageId' : MessageId,
  'sender' : UserId,
  'sentAt' : ExportInt,
  'tradeId' : TradeId,
  'attachments' : Array<MediaAttachmentExport>,
}
export interface AddressVerification {
  'active' : boolean,
  'expiresAt' : bigint,
  'level' : bigint,
  'txCount' : bigint,
  'verifiedAt' : bigint,
}
export interface AddressVerificationExport {
  'active' : boolean,
  'expiresAt' : ExportInt,
  'level' : ExportInt,
  'txCount' : ExportInt,
  'verifiedAt' : ExportInt,
}
export interface AuditEntry {
  'id' : bigint,
  'action' : string,
  'actorId' : Principal,
  'timestamp' : Timestamp,
  'details' : string,
  'targetId' : [] | [string],
}
export interface AuditFilter {
  'targetFilter' : [] | [string],
  'actionFilter' : [] | [string],
  'actorFilter' : [] | [Principal],
}
export interface BalanceView {
  'chain' : ChainType,
  'error' : [] | [string],
  'usdtBalance' : bigint,
  'usdcBalance' : bigint,
  'lastChecked' : bigint,
}
export interface BuyerCancelPenaltySplit {
  'buyerRefund' : bigint,
  'platformFee' : bigint,
  'sellerCompensation' : bigint,
  'lockedAmount' : bigint,
}
export interface BuyerCancelPenaltySplitExport {
  'buyerRefund' : ExportInt,
  'platformFee' : ExportInt,
  'sellerCompensation' : ExportInt,
  'lockedAmount' : ExportInt,
}
export interface CarrierInfo {
  'displayName' : string,
  'description' : string,
  'carrier' : ShippingCarrier,
}
export interface CategoryAttributeField {
  'key' : string,
  'labelEn' : string,
  'labelUk' : string,
  'required' : boolean,
  'fieldType' : { 'text' : null } |
    { 'number' : null },
}
export interface CategoryAttributeValue { 'key' : string, 'value' : string }
export type CategoryId = bigint;
export interface CategoryNode {
  'id' : CategoryId,
  'labelEn' : string,
  'labelUk' : string,
  'slug' : string,
  'legacyCategory' : ListingCategory,
  'parentId' : [] | [CategoryId],
}
export type ChainType = { 'SPL' : null } |
  { 'BEP20' : null } |
  { 'TRC20' : null } |
  { 'Polygon' : null } |
  { 'ERC20' : null } |
  { 'Avalanche' : null };
export type CollusionSignal = { 'rapid_account_cycling' : null } |
  { 'reciprocal_trades' : null } |
  { 'shared_wallet' : null } |
  { 'repeated_claims' : null };
export interface ComplianceNote {
  'id' : bigint,
  'note' : string,
  'actorId' : Principal,
  'timestamp' : Timestamp,
}
export interface CyclesStatus {
  'isWarning' : boolean,
  'currentBalance' : bigint,
  'warningThreshold' : bigint,
  'estimatedDailyBurn' : bigint,
}
export interface DigitalDeliveryView {
  'inspectionDeadline' : bigint,
  'password' : [] | [string],
  'deliveryRecordAt' : bigint,
  'mimeType' : [] | [string],
  'fileHash' : [] | [string],
  'dekHex' : [] | [string],
  'fileVersionId' : bigint,
  'revealedAt' : bigint,
  'fileUrl' : string,
}
export interface DigitalDeliveryViewExport {
  'inspectionDeadline' : ExportInt,
  'password' : [] | [string],
  'deliveryRecordAt' : ExportInt,
  'mimeType' : [] | [string],
  'fileHash' : [] | [string],
  'dekHex' : [] | [string],
  'fileVersionId' : ExportInt,
  'revealedAt' : ExportInt,
  'fileUrl' : string,
}
export interface DigitalFileAsset {
  'contentHash' : [] | [string],
  'mimeType' : string,
  'blobHash' : string,
  'blobUrlEncrypted' : string,
  'fileVersionId' : bigint,
  'sizeBytes' : bigint,
  'registeredAt' : bigint,
  'dekEncrypted' : string,
}
export interface DisputeEvidencePack {
  'chatThreadLink' : [] | [string],
  'packagePhotoUrls' : Array<string>,
  'fileHash' : [] | [string],
  'downloadTimestamp' : bigint,
  'ttnScreenshotUrl' : [] | [string],
}
export type DisputeId = bigint;
export type DisputeLevel = { 'l1' : null } |
  { 'l2' : null };
export type DisputeReason = { 'other' : null } |
  { 'item_damaged' : null } |
  { 'seller_unresponsive' : null } |
  { 'item_differs' : null } |
  { 'item_not_received' : null };
export interface DisputeResolution {
  'notes' : string,
  'outcome' : ResolutionOutcome,
  'resolvedBy' : UserId,
}
export interface DisputeSlaFlags {
  'l2TriageOverdue' : boolean,
  'l2DecisionOverdue' : boolean,
  'l1SlaOverdue' : boolean,
}
export type DisputeStatus = { 'resolved' : null } |
  { 'opened' : null } |
  { 'escalated_to_admin' : null } |
  { 'l2_queued' : null } |
  { 'under_review' : null } |
  { 'draft' : null };
export type DisputeTradeKind = { 'physical' : null } |
  { 'digital' : null };
export interface DisputeView {
  'id' : DisputeId,
  'evidenceUrls' : Array<string>,
  'status' : DisputeStatus,
  'l1SlaDeadline' : bigint,
  'trade' : TradeId,
  'evidenceAttachments' : Array<MediaAttachment>,
  'tradeKind' : DisputeTradeKind,
  'initiator' : UserId,
  'jury' : [] | [JuryView],
  'createdAt' : bigint,
  'description' : string,
  'resolution' : [] | [DisputeResolution],
  'l2QueuedAt' : bigint,
  'level' : DisputeLevel,
  'l2DecisionDeadline' : bigint,
  'slaFlags' : DisputeSlaFlags,
  'l2TriageDeadline' : bigint,
  'moderatorNotes' : Array<string>,
  'resolvedAt' : bigint,
  'reason' : DisputeReason,
  'evidencePack' : DisputeEvidencePack,
}
export type Error = { 'insufficient_funds' : null } |
  { 'rate_limited' : null } |
  { 'dispute_already_open' : null } |
  { 'not_found' : null } |
  { 'banned' : null } |
  { 'invalid_input' : string } |
  { 'escrow_error' : string } |
  { 'already_exists' : null } |
  { 'unauthorized' : null };
export interface ErrorLogEntry {
  'id' : bigint,
  'functionName' : string,
  'moduleName' : string,
  'errorMessage' : string,
  'userPrincipal' : [] | [Principal],
  'timestamp' : bigint,
  'severity' : ErrorSeverity,
}
export type ErrorSeverity = { 'warning' : null } |
  { 'info' : null } |
  { 'error' : null } |
  { 'critical' : null };
export interface EscrowAccount {
  'fee' : bigint,
  'sellerPrincipal' : UserId,
  'token' : TradeToken,
  'ledgerCanisterId' : Principal,
  'deadline' : bigint,
  'tradeId' : TradeId,
  'lockedAt' : bigint,
  'buyerPrincipal' : UserId,
  'amount' : bigint,
}
export interface EscrowAccountExport {
  'fee' : ExportInt,
  'sellerPrincipal' : UserId,
  'token' : TradeToken,
  'ledgerCanisterId' : Principal,
  'deadline' : ExportInt,
  'tradeId' : TradeId,
  'lockedAt' : ExportInt,
  'buyerPrincipal' : UserId,
  'amount' : ExportInt,
}
export type ExportInt = bigint;
export interface Feedback {
  'id' : FeedbackId,
  'trade' : TradeId,
  'createdAt' : bigint,
  'comment' : string,
  'rating' : bigint,
  'reviewed' : UserId,
  'reviewer' : UserId,
}
export interface FeedbackExport {
  'id' : FeedbackId,
  'trade' : TradeId,
  'createdAt' : ExportInt,
  'comment' : string,
  'rating' : ExportInt,
  'reviewed' : UserId,
  'reviewer' : UserId,
}
export type FeedbackId = bigint;
export interface FraudReviewRecord {
  'decision' : string,
  'reviewedAt' : Timestamp,
  'slaDueAt' : Timestamp,
  'rationale' : string,
  'reviewer' : Principal,
  'evidenceHash' : string,
}
export interface GateCChecklistView {
  'securitySignOffRef' : string,
  'rollbackTestsPassed' : boolean,
  'subaccountDesignReviewed' : boolean,
  'checklistComplete' : boolean,
  'trustlessEscrowEnabled' : boolean,
  'testnetE2ePassed' : boolean,
  'betaCapsConfigured' : boolean,
  'ckBetaCapUsdCents' : bigint,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpResponse {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type InsuranceCopyTier = { 'stake_only' : null } |
  { 'capped_reserve' : null } |
  { 'no_guarantee' : null };
export type ItemCondition = { 'new' : null } |
  { 'fair' : null } |
  { 'good' : null } |
  { 'poor' : null } |
  { 'likeNew' : null };
export interface JurorDashboardEntry {
  'deadline' : bigint,
  'tradeId' : TradeId,
  'sellerVotes' : bigint,
  'hasVoted' : boolean,
  'totalJurors' : bigint,
  'buyerVotes' : bigint,
  'reason' : DisputeReason,
  'disputeId' : DisputeId,
}
export interface JurorStats {
  'principal' : Principal,
  'successRate' : number,
  'activeCount' : bigint,
  'stakedAmount' : number,
  'registeredAt' : bigint,
  'resolvedCount' : bigint,
}
export interface JurorVote {
  'vote' : JurorVoteChoice,
  'reasoning' : string,
  'timestamp' : bigint,
  'jurorPrincipal' : Principal,
}
export type JurorVoteChoice = { 'sellerWins' : null } |
  { 'buyerWins' : null };
export interface JuryView {
  'jurors' : Array<Principal>,
  'votes' : Array<JurorVote>,
  'deadline' : bigint,
}
export type KycTier = { 'verified' : null } |
  { 'none' : null };
export type LiabilityAuditAction = { 'created' : null } |
  { 'stake_applied' : null } |
  { 'partial_clear' : null } |
  { 'full_clear' : null };
export interface LiabilityAuditEntry {
  'action' : LiabilityAuditAction,
  'note' : string,
  'performedBy' : Principal,
  'timestamp' : bigint,
  'amount' : bigint,
}
export interface LiabilityEvent {
  'liabilityId' : bigint,
  'tradeId' : bigint,
  'timestamp' : bigint,
  'amount' : bigint,
  'reason' : string,
}
export interface LiabilityEventExport {
  'liabilityId' : ExportInt,
  'tradeId' : ExportInt,
  'timestamp' : ExportInt,
  'amount' : bigint,
  'reason' : string,
}
export type LiabilityReason = { 'admin_adjustment' : null } |
  { 'cancellation_fee' : null } |
  { 'stake_seizure_residual' : null } |
  { 'seller_fault' : null } |
  { 'dispute_lost' : null } |
  { 'buyer_cancel_compensation' : null };
export interface LiabilityRecordView {
  'id' : bigint,
  'status' : LiabilityStatus,
  'originalAmount' : bigint,
  'initiator' : Principal,
  'userId' : UserId,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'tradeId' : [] | [TradeId],
  'remainingBalance' : bigint,
  'currency' : TradeToken,
  'auditTrail' : Array<LiabilityAuditEntry>,
  'reason' : LiabilityReason,
}
export type LiabilityStatus = { 'open' : null } |
  { 'cleared' : null } |
  { 'partial' : null };
export interface LinkPreview {
  'url' : string,
  'title' : [] | [string],
  'fetchedAt' : bigint,
  'description' : [] | [string],
  'siteName' : [] | [string],
  'imageUrl' : [] | [string],
}
export interface LinkedExternalWallet {
  'id' : bigint,
  'linkedAt' : bigint,
  'chain' : WalletChain,
  'messageHash' : string,
  'address' : string,
  'sessionId' : string,
  'purpose' : WalletLinkPurpose,
}
export interface LinkedExternalWalletExport {
  'id' : ExportInt,
  'linkedAt' : ExportInt,
  'chain' : WalletChain,
  'messageHash' : string,
  'address' : string,
  'sessionId' : string,
  'purpose' : WalletLinkPurpose,
}
export interface ListingCard {
  'id' : ListingId,
  'categoryId' : CategoryId,
  'status' : ListingStatus,
  'title' : string,
  'sellerPrincipal' : UserId,
  'priceAmount' : bigint,
  'categorySlug' : string,
  'shippingMethods' : Array<ShippingMethod>,
  'createdAt' : bigint,
  'description' : string,
  'sellerTrustLevel' : TrustLevel,
  'isPromoted' : boolean,
  'sellerRating' : bigint,
  'attributes' : Array<CategoryAttributeValue>,
  'priceToken' : TradeToken,
  'category' : ListingCategory,
  'sellerUsername' : string,
  'location' : string,
  'photos' : Array<string>,
  'digitalFileUrl' : string,
  'condition' : ItemCondition,
}
export interface ListingCardExport {
  'id' : ListingId,
  'categoryId' : CategoryId,
  'title' : string,
  'sellerPrincipal' : UserId,
  'priceAmount' : ExportInt,
  'categorySlug' : string,
  'shippingMethods' : Array<ShippingMethodExport>,
  'createdAt' : ExportInt,
  'description' : string,
  'sellerTrustLevel' : TrustLevel,
  'isPromoted' : boolean,
  'listingStatus' : ListingStatus,
  'sellerRating' : bigint,
  'attributes' : Array<CategoryAttributeValue>,
  'priceToken' : TradeToken,
  'category' : ListingCategory,
  'sellerUsername' : string,
  'location' : string,
  'photos' : Array<string>,
  'digitalFileUrl' : string,
  'condition' : ItemCondition,
}
export type ListingCategory = { 'clothing' : null } |
  { 'other' : null } |
  { 'books' : null } |
  { 'digital' : null } |
  { 'services' : null } |
  { 'electronics' : null };
export type ListingId = bigint;
export type ListingInquiryId = bigint;
export interface ListingInquiryMessage {
  'id' : ListingInquiryMessageId,
  'content' : string,
  'createdAt' : bigint,
  'sender' : UserId,
  'inquiryId' : ListingInquiryId,
}
export type ListingInquiryMessageId = bigint;
export type ListingStakeStatus = { 'locked' : null } |
  { 'seized' : null } |
  { 'released' : null };
export interface ListingStakeView {
  'status' : ListingStakeStatus,
  'token' : TradeToken,
  'listingId' : ListingId,
  'seller' : UserId,
  'lockedAt' : bigint,
  'amount' : bigint,
}
export type ListingStatus = { 'active' : null } |
  { 'sold' : null } |
  { 'inactive' : null } |
  { 'draft' : null } |
  { 'removed' : null };
export interface MediaAttachment {
  'url' : string,
  'mimeType' : string,
  'fileName' : string,
  'fileSize' : bigint,
}
export interface MediaAttachmentExport {
  'url' : string,
  'mimeType' : string,
  'fileName' : string,
  'fileSize' : ExportInt,
}
export interface MeestConfig {
  'senderPudoRef' : [] | [string],
  'enabled' : boolean,
  'deliveryTypes' : Array<string>,
}
export interface Message {
  'id' : MessageId,
  'attachmentUrl' : [] | [string],
  'trade' : TradeId,
  'content' : string,
  'sender' : UserId,
  'sentAt' : bigint,
  'attachments' : Array<MediaAttachment>,
}
export type MessageId = bigint;
export interface MetricsSummary {
  'totalTrades' : bigint,
  'totalVolume' : bigint,
  'p95LatencyMs' : bigint,
  'errorRate' : number,
  'memoryUsage' : bigint,
  'activeTrades' : bigint,
  'avgTradeValue' : bigint,
  'disputeRate' : number,
  'totalRevenue' : bigint,
  'cyclesBalance' : bigint,
}
export interface ModuleMetricsView {
  'memoryUsedBytes' : bigint,
  'cyclesConsumed' : bigint,
  'moduleName' : string,
  'lastUpdated' : bigint,
  'errorCount' : bigint,
  'requestCount' : bigint,
}
export interface NotificationEvent {
  'id' : bigint,
  'read' : boolean,
  'tradeId' : bigint,
  'message' : string,
  'timestamp' : bigint,
  'eventType' : string,
}
export interface NovaPoshtaBranch {
  'ref' : string,
  'cityRef' : string,
  'name' : string,
  'address' : string,
  'schedule' : [] | [string],
}
export interface NovaPoshtaConfig {
  'enabled' : boolean,
  'senderBranchRef' : string,
  'deliveryTypes' : Array<string>,
}
export type OnChainSettlementOp = {
    'buyerCancelSplit' : BuyerCancelPenaltySplit
  } |
  { 'releaseToSeller' : null } |
  { 'refundBuyer' : { 'memo' : string } } |
  { 'disputeBuyerWins' : null } |
  { 'disputeSplit' : { 'sellerHasNegativeRep' : boolean } } |
  { 'disputeSellerWins' : { 'sellerHasNegativeRep' : boolean } };
export type OnChainSettlementOpExport = {
    'buyerCancelSplit' : BuyerCancelPenaltySplitExport
  } |
  { 'releaseToSeller' : null } |
  { 'refundBuyer' : { 'memo' : string } } |
  { 'disputeBuyerWins' : null } |
  { 'disputeSplit' : { 'sellerHasNegativeRep' : boolean } } |
  { 'disputeSellerWins' : { 'sellerHasNegativeRep' : boolean } };
export interface PackageDetails {
  'weight' : bigint,
  'height' : bigint,
  'places' : bigint,
  'length' : bigint,
  'declaredValue' : bigint,
  'width' : bigint,
}
export interface Page {
  'totalCount' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<TradeView>,
}
export interface PagedResult {
  'page' : bigint,
  'totalCount' : bigint,
  'pageSize' : bigint,
  'items' : Array<AuditEntry>,
}
export interface PagedResult_1 {
  'page' : bigint,
  'totalCount' : bigint,
  'pageSize' : bigint,
  'items' : Array<UserProfile>,
}
export interface PaymentIntent {
  'token' : TradeToken,
  'createdAt' : bigint,
  'path' : PaymentSettlementPath,
  'recipient' : string,
  'network' : string,
  'expiry' : bigint,
  'exactAmount' : bigint,
}
export interface PaymentIntentExport {
  'token' : TradeToken,
  'createdAt' : ExportInt,
  'path' : PaymentSettlementPath,
  'recipient' : string,
  'network' : string,
  'expiry' : ExportInt,
  'exactAmount' : ExportInt,
}
export interface PaymentMethod {
  'walletLinkId' : bigint,
  'token' : TradeToken,
  'addedAt' : bigint,
  'address' : string,
  'verification' : [] | [AddressVerification],
}
export interface PaymentMethodExport {
  'walletLinkId' : ExportInt,
  'token' : TradeToken,
  'addedAt' : ExportInt,
  'address' : string,
  'verification' : [] | [AddressVerificationExport],
}
export type PaymentSettlementPath = { 'ck' : null } |
  { 'manual' : null };
export interface PaymentVerificationResult {
  'status' : PaymentVerificationStatus,
  'blockNumber' : bigint,
  'confirmedAmount' : number,
  'confirmedRecipient' : string,
  'txHash' : string,
  'errorReason' : [] | [string],
}
export type PaymentVerificationStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'failed' : null };
export interface PayoutRequestView {
  'id' : bigint,
  'status' : PayoutStatus,
  'liabilityId' : bigint,
  'token' : TradeToken,
  'collusionSignals' : Array<CollusionSignal>,
  'executedAt' : Timestamp,
  'beneficiary' : Principal,
  'unrecoveredLoss' : bigint,
  'firstApprover' : [] | [Principal],
  'tradeId' : TradeId,
  'fraudReview' : [] | [FraudReviewRecord],
  'secondApprover' : [] | [Principal],
  'approvedAmount' : bigint,
  'requestedAt' : Timestamp,
}
export type PayoutStatus = { 'pending_first_approval' : null } |
  { 'held_fraud_review' : null } |
  { 'denied' : null } |
  { 'pending_second_approval' : null } |
  { 'approved' : null } |
  { 'executed' : null };
export interface PayoutWalletSnapshot {
  'snapshottedAt' : bigint,
  'walletLinkId' : bigint,
  'token' : TradeToken,
  'chain' : WalletChain,
  'address' : string,
}
export interface PayoutWalletSnapshotExport {
  'snapshottedAt' : ExportInt,
  'walletLinkId' : ExportInt,
  'token' : TradeToken,
  'chain' : WalletChain,
  'address' : string,
}
export interface PendingOnChainSettlementExport {
  'op' : OnChainSettlementOpExport,
  'queuedAt' : ExportInt,
  'attempts' : ExportInt,
  'lastError' : [] | [string],
  'targetStatus' : TradeStatus,
}
export interface PendingOnChainSettlementView {
  'op' : OnChainSettlementOp,
  'queuedAt' : bigint,
  'attempts' : bigint,
  'lastError' : [] | [string],
  'targetStatus' : TradeStatus,
}
export interface PlatformMetrics {
  'totalTrades' : bigint,
  'activeUsersLast30d' : bigint,
  'avgTradeCompletionMs' : bigint,
  'totalListings' : bigint,
  'tradesByToken' : Array<[TradeToken, bigint]>,
  'disputeRatePct' : bigint,
}
export interface PlatformMetrics__1 {
  'totalTrades' : bigint,
  'activeUsersLast24h' : bigint,
  'totalVolume' : number,
  'monthlyActiveUsers' : bigint,
  'completedTrades' : bigint,
  'avgSettlementTimeMin' : number,
  'disputeRate' : number,
  'swapSuccessRate' : number,
}
export type ProposalId = bigint;
export type ProposalStatus = { 'active' : null } |
  { 'expired' : null } |
  { 'rejected' : null } |
  { 'executed' : null } |
  { 'passed' : null };
export type ProposalType = { 'TextResolution' : { 'description' : string } } |
  { 'TreasuryTransfer' : { 'recipient' : Principal, 'amount' : bigint } } |
  { 'ParameterChange' : { 'key' : string, 'value' : string } };
export interface ProposalView {
  'id' : ProposalId,
  'status' : ProposalStatus,
  'noVotes' : bigint,
  'executedAt' : [] | [Timestamp],
  'yesVotes' : bigint,
  'createdAt' : Timestamp,
  'description' : string,
  'deadline' : Timestamp,
  'proposalType' : ProposalType,
  'proposer' : UserId,
  'voterCount' : bigint,
}
export interface ProtectionView {
  'maxPayoutE8s' : bigint,
  'tier' : InsuranceCopyTier,
  'dailyRemainingE8s' : bigint,
  'insuranceOffered' : boolean,
  'liquidBalanceE8s' : bigint,
  'tradeAmountUsdCents' : bigint,
}
export interface RateCacheEntry { 'rateInCents' : bigint, 'fetchedAt' : bigint }
export interface ReputationStats {
  'reputationScore' : bigint,
  'buyerScore' : bigint,
  'trustLevel' : TrustLevel,
  'averageRating' : number,
  'completedTrades' : bigint,
  'disputeRate' : number,
  'sellerScore' : bigint,
}
export interface ReserveLedgerView {
  'pendingPayouts' : bigint,
  'liquidBalanceE8s' : bigint,
  'accrualCount' : bigint,
}
export type ResolutionOutcome = { 'buyer_wins' : null } |
  { 'split' : null } |
  { 'seller_wins' : null };
export type Result = { 'ok' : null } |
  { 'err' : Error };
export type Result_1 = {
    'ok' : { 'active' : boolean, 'txCount' : bigint, 'verifiedAt' : Timestamp }
  } |
  { 'err' : Error };
export type Result_10 = { 'ok' : SavedSearch } |
  { 'err' : Error };
export type Result_11 = { 'ok' : string } |
  { 'err' : Error };
export type Result_12 = { 'ok' : WalletLinkChallengeView } |
  { 'err' : Error };
export type Result_13 = { 'ok' : DigitalFileAsset } |
  { 'err' : Error };
export type Result_14 = { 'ok' : LinkedExternalWallet } |
  { 'err' : Error };
export type Result_15 = { 'ok' : boolean } |
  { 'err' : Error };
export type Result_16 = { 'ok' : DisputeId } |
  { 'err' : Error };
export type Result_17 = { 'ok' : FeedbackId } |
  { 'err' : Error };
export type Result_18 = { 'ok' : TradeId } |
  { 'err' : Error };
export type Result_19 = {
    'ok' : {
      'status' : string,
      'trackingNumber' : string,
      'estimatedDelivery' : [] | [string],
      'statusHistory' : Array<{ 'status' : string, 'timestamp' : bigint }>,
      'isDelivered' : boolean,
      'carrier' : string,
    }
  } |
  { 'err' : Error };
export type Result_2 = { 'ok' : PaymentVerificationResult } |
  { 'err' : Error };
export type Result_20 = {
    'ok' : Array<{ 'name' : string, 'address' : string, 'index' : string }>
  } |
  { 'err' : Error };
export type Result_21 = { 'ok' : bigint } |
  { 'err' : Error };
export type Result_22 = { 'ok' : Array<DisputeView> } |
  { 'err' : Error };
export type Result_23 = { 'ok' : Array<NovaPoshtaBranch> } |
  { 'err' : Error };
export type Result_24 = { 'ok' : Array<JurorDashboardEntry> } |
  { 'err' : Error };
export type Result_25 = {
    'ok' : Array<
      { 'id' : string, 'name' : string, 'type' : string, 'address' : string }
    >
  } |
  { 'err' : Error };
export type Result_26 = { 'ok' : Array<ListingInquiryMessage> } |
  { 'err' : Error };
export type Result_27 = { 'ok' : LinkPreview } |
  { 'err' : Error };
export type Result_28 = { 'ok' : Array<JurorStats> } |
  { 'err' : Error };
export type Result_29 = { 'ok' : DigitalDeliveryView } |
  { 'err' : Error };
export type Result_30 = { 'ok' : ProposalId } |
  { 'err' : Error };
export type Result_31 = { 'ok' : PaymentIntent } |
  { 'err' : Error };
export type Result_32 = { 'ok' : ListingCard } |
  { 'err' : Error };
export type Result_33 = { 'ok' : ProposalStatus } |
  { 'err' : Error };
export type Result_34 = { 'ok' : BuyerCancelPenaltySplit } |
  { 'err' : Error };
export type Result_35 = { 'ok' : PayoutRequestView } |
  { 'err' : Error };
export type Result_36 = { 'ok' : Array<LiabilityRecordView> } |
  { 'err' : Error };
export type Result_37 = { 'ok' : PaymentMethod } |
  { 'err' : Error };
export type Result_5 = { 'ok' : PayoutWalletSnapshot } |
  { 'err' : Error };
export type Result_6 = { 'ok' : UserProfile } |
  { 'err' : Error };
export type Result_7 = { 'ok' : Message } |
  { 'err' : Error };
export type Result_8 = { 'ok' : ListingInquiryMessage } |
  { 'err' : Error };
export type Result_9 = { 'ok' : bigint } |
  { 'err' : Error };
export interface SavedSearch {
  'id' : SavedSearchId,
  'alertsEnabled' : boolean,
  'owner' : UserId,
  'paramsJson' : string,
  'name' : string,
  'createdAt' : bigint,
}
export interface SavedSearchExport {
  'id' : SavedSearchId,
  'alertsEnabled' : boolean,
  'owner' : UserId,
  'paramsJson' : string,
  'name' : string,
  'createdAt' : ExportInt,
}
export type SavedSearchId = bigint;
export interface SellerFaultSettlementView {
  'liabilityId' : [] | [bigint],
  'buyerObligationCents' : bigint,
  'residualCents' : bigint,
  'path' : SettlementPath,
  'insurancePayoutId' : [] | [bigint],
  'stakeSeizedCents' : bigint,
  'tradeId' : TradeId,
  'onChainRefundExpected' : boolean,
  'copyTier' : SettlementCopyTier,
}
export type SettlementCopyTier = { 'on_chain_recovery' : null } |
  { 'partial_recovery' : null } |
  { 'manual_restriction_only' : null };
export type SettlementPath = { 'on_chain_ck' : null } |
  { 'manual' : null };
export interface ShipHttpHeader { 'value' : string, 'name' : string }
export interface ShipHttpResponse {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<ShipHttpHeader>,
}
export type ShippingCarrier = { 'meest' : null } |
  { 'nova_poshta' : null } |
  { 'self_pickup' : null } |
  { 'digital' : null } |
  { 'ukrposhta' : null };
export interface ShippingMethod {
  'type' : ShippingServiceType,
  'estimatedDays' : bigint,
  'carrier' : ShippingCarrier,
}
export interface ShippingMethodExport {
  'type' : ShippingServiceType,
  'estimatedDays' : ExportInt,
  'carrier' : ShippingCarrier,
}
export interface ShippingOption {
  'cost' : number,
  'deliveryDays' : bigint,
  'available' : boolean,
  'carrier' : ShippingCarrier,
  'costNat' : bigint,
}
export interface ShippingSelection {
  'provider' : string,
  'branchRef' : [] | [string],
  'cost' : bigint,
  'deliveryType' : string,
  'address' : [] | [string],
}
export interface ShippingSelectionExport {
  'provider' : string,
  'branchRef' : [] | [string],
  'cost' : ExportInt,
  'deliveryType' : string,
  'address' : [] | [string],
}
export type ShippingServiceType = { 'express' : null } |
  { 'standard' : null };
export interface StakeBalanceView { 'locked' : bigint, 'available' : bigint }
export type TTNStatus = { 'Failed' : null } |
  { 'Success' : null } |
  { 'InProgress' : null } |
  { 'Pending' : null };
export type Timestamp = bigint;
export interface TokenInfo {
  'decimals' : bigint,
  'token' : TradeToken,
  'name' : string,
  'network' : string,
  'isNative' : boolean,
  'priority' : bigint,
  'symbol' : string,
}
export type TradeCapTier = { 'high_value_ck' : null } |
  { 'rejected' : null } |
  { 'elevated' : null } |
  { 'standard' : null };
export interface TradeCapTierCheck {
  'sellerVerifiedTierOk' : boolean,
  'tier' : TradeCapTier,
  'elevatedStakeRequired' : bigint,
  'allowed' : boolean,
  'sellerStakeOk' : boolean,
  'ckOnlyRequired' : boolean,
  'blockReason' : [] | [string],
  'usdCents' : bigint,
  'gateCRequired' : boolean,
}
export interface TradeFeeQuote {
  'usesDefaultFeeBps' : boolean,
  'token' : TradeToken,
  'totalBuyerAmount' : bigint,
  'platformFeeAmount' : bigint,
  'platformFeeBps' : bigint,
  'itemPrice' : bigint,
}
export type TradeId = bigint;
export interface TradePaymentStatus {
  'status' : TradeStatus,
  'isManual' : boolean,
  'token' : TradeToken,
  'formattedAmount' : string,
  'tradeId' : TradeId,
  'tokenInfo' : [] | [TokenInfo],
  'amount' : bigint,
  'verificationResult' : [] | [PaymentVerificationResult],
}
export type TradeStatus = { 'shipped' : null } |
  { 'payment_intent' : null } |
  { 'payment_verified' : null } |
  { 'fulfillment_pending' : null } |
  { 'cancelled' : null } |
  { 'disputed' : null } |
  { 'pending' : null } |
  { 'refunded' : null } |
  { 'dispute_l1' : null } |
  { 'dispute_l2' : null } |
  { 'payment_intent_expired' : null } |
  { 'funded' : null } |
  { 'buyer_confirmed' : null } |
  { 'complete' : null } |
  { 'digital_delivered' : null } |
  { 'awaiting_receipt' : null } |
  { 'awaiting_approval' : null } |
  { 'manual_payment_pending' : null } |
  { 'cancelled_buyer_pre_ship' : null } |
  { 'awaiting_seller_handshake' : null } |
  { 'cancelled_no_seller_response' : null };
export type TradeToken = { 'USDT_ERC20' : null } |
  { 'USDT_AVAX' : null } |
  { 'USDC_ERC20' : null } |
  { 'USDT_BEP20' : null } |
  { 'USDC_AVAX' : null } |
  { 'ckUSDC' : null } |
  { 'ckUSDT' : null } |
  { 'USDC_SPL' : null } |
  { 'USDT_TRC20' : null } |
  { 'USDC_POLYGON' : null } |
  { 'USDT_POLYGON' : null };
export interface TradeView {
  'id' : TradeId,
  'escrowAccount' : [] | [EscrowAccount],
  'status' : TradeStatus,
  'completedAt' : bigint,
  'listing' : ListingId,
  'pendingOnChainSettlement' : [] | [PendingOnChainSettlementView],
  'token' : TradeToken,
  'ttnNumber' : [] | [string],
  'npDeliveredGraceEndsAt' : bigint,
  'createdAt' : bigint,
  'confirmedAt' : bigint,
  'deliveryRecordAt' : bigint,
  'seller' : UserId,
  'shippingSelection' : [] | [ShippingSelection],
  'sellerResponseDeadline' : bigint,
  'refundDeadline' : bigint,
  'shippedAt' : bigint,
  'payoutWalletHeld' : boolean,
  'fundedAt' : bigint,
  'shipByDeadline' : bigint,
  'paymentIntent' : [] | [PaymentIntent],
  'buyer' : UserId,
  'npDeliveredAt' : bigint,
  'amount' : bigint,
  'payoutWalletSnapshot' : [] | [PayoutWalletSnapshot],
  'digitalDelivery' : [] | [DigitalDeliveryView],
  'ttnCreationStatus' : TTNStatus,
}
export interface TradeViewExport {
  'id' : TradeId,
  'escrowAccount' : [] | [EscrowAccountExport],
  'completedAt' : ExportInt,
  'listing' : ListingId,
  'pendingOnChainSettlement' : [] | [PendingOnChainSettlementExport],
  'token' : TradeToken,
  'ttnNumber' : [] | [string],
  'npDeliveredGraceEndsAt' : ExportInt,
  'createdAt' : ExportInt,
  'confirmedAt' : ExportInt,
  'deliveryRecordAt' : ExportInt,
  'seller' : UserId,
  'shippingSelection' : [] | [ShippingSelectionExport],
  'sellerResponseDeadline' : ExportInt,
  'refundDeadline' : ExportInt,
  'shippedAt' : ExportInt,
  'payoutWalletHeld' : boolean,
  'fundedAt' : ExportInt,
  'shipByDeadline' : ExportInt,
  'paymentIntent' : [] | [PaymentIntentExport],
  'buyer' : UserId,
  'npDeliveredAt' : ExportInt,
  'amount' : ExportInt,
  'payoutWalletSnapshot' : [] | [PayoutWalletSnapshotExport],
  'digitalDelivery' : [] | [DigitalDeliveryViewExport],
  'tradeStatus' : TradeStatus,
  'ttnCreationStatus' : TTNStatus,
}
export type TrustLevel = { 'new' : null } |
  { 'bronze' : null } |
  { 'gold' : null } |
  { 'silver' : null };
export interface TxHistoryFilter {
  'to' : [] | [Timestamp],
  'status' : [] | [TradeStatus],
  'token' : [] | [TradeToken],
  'from' : [] | [Timestamp],
}
export interface UkrposhtaConfig {
  'enabled' : boolean,
  'senderOfficeRef' : [] | [string],
  'deliveryTypes' : Array<string>,
}
export interface UserFilter {
  'roleFilter' : [] | [UserRole],
  'bannedFilter' : [] | [boolean],
}
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'bio' : string,
  'reputationScore' : bigint,
  'linkedWallets' : Array<LinkedExternalWallet>,
  'buyerScore' : bigint,
  'username' : string,
  'createdAt' : bigint,
  'trustLevel' : TrustLevel,
  'role' : UserRole,
  'liabilityBalance' : bigint,
  'avatarUrl' : string,
  'liabilityHistory' : Array<LiabilityEvent>,
  'isBanned' : boolean,
  'accountClosedAt' : bigint,
  'suspendedUntil' : bigint,
  'sellerScore' : bigint,
  'paymentMethods' : Array<PaymentMethod>,
  'kycTier' : KycTier,
}
export interface UserProfileExport {
  'id' : UserId,
  'bio' : string,
  'reputationScore' : bigint,
  'linkedWallets' : Array<LinkedExternalWalletExport>,
  'buyerScore' : bigint,
  'username' : string,
  'createdAt' : ExportInt,
  'trustLevel' : TrustLevel,
  'role' : UserRole,
  'liabilityBalance' : bigint,
  'avatarUrl' : string,
  'liabilityHistory' : Array<LiabilityEventExport>,
  'isBanned' : boolean,
  'accountClosedAt' : ExportInt,
  'suspendedUntil' : ExportInt,
  'sellerScore' : bigint,
  'paymentMethods' : Array<PaymentMethodExport>,
  'kycTier' : KycTier,
}
export type UserRole = { 'admin' : null } |
  { 'moderator' : null } |
  { 'user' : null };
export interface VaultAddressView {
  'chain' : ChainType,
  'network' : string,
  'tokenSymbol' : string,
  'address' : string,
  'derivedAt' : bigint,
}
export interface VaultHttpResponse {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<{ 'value' : string, 'name' : string }>,
}
export type WalletChain = { 'tron' : null } |
  { 'evm_bsc' : null } |
  { 'evm_eth' : null };
export interface WalletLinkChallengeView {
  'expiresAt' : bigint,
  'chain' : WalletChain,
  'challengeId' : bigint,
  'message' : string,
  'address' : string,
  'sessionId' : string,
  'purpose' : WalletLinkPurpose,
}
export type WalletLinkPurpose = { 'stake' : null } |
  { 'payment' : null } |
  { 'payout' : null };
export interface WithdrawalRecord {
  'id' : bigint,
  'executedAt' : Timestamp,
  'recipient' : Principal,
  'amount' : bigint,
  'proposalId' : bigint,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_transformResponse' : ActorMethod<
    [
      {
        'context' : Uint8Array,
        'response' : {
          'status' : bigint,
          'body' : Uint8Array,
          'headers' : Array<{ 'value' : string, 'name' : string }>,
        },
      },
    ],
    {
      'status' : bigint,
      'body' : Uint8Array,
      'headers' : Array<{ 'value' : string, 'name' : string }>,
    }
  >,
  'addComplianceNote' : ActorMethod<[UserId, string], undefined>,
  'addEvidence' : ActorMethod<[DisputeId, Array<MediaAttachment>], Result>,
  'addFavorite' : ActorMethod<[ListingId], Result>,
  'addModeratorNote' : ActorMethod<[DisputeId, string], Result>,
  'addPaymentMethod' : ActorMethod<[TradeToken, string, boolean], Result_37>,
  'adminApproveInsurancePayout' : ActorMethod<[bigint], Result_35>,
  'adminClearUserLiability' : ActorMethod<[UserId, string], Result>,
  'adminGetAllTrades' : ActorMethod<[], Array<TradeView>>,
  'adminGetGateCChecklist' : ActorMethod<[], GateCChecklistView>,
  'adminListLiabilities' : ActorMethod<[bigint, bigint], Result_36>,
  'adminPartialClearLiability' : ActorMethod<[bigint, bigint, string], Result>,
  'adminPromoteListing' : ActorMethod<[ListingId], Result>,
  'adminRemoveListing' : ActorMethod<[ListingId, string], Result>,
  'adminRequestInsurancePayout' : ActorMethod<
    [TradeId, Principal, bigint, bigint, TradeToken],
    Result_35
  >,
  'adminResolveInsuranceFraudReview' : ActorMethod<
    [bigint, boolean, string, string],
    Result_35
  >,
  'adminSetTrustlessEscrowEnabled' : ActorMethod<[boolean, string], Result>,
  'adminSetUserKycTier' : ActorMethod<[UserId, KycTier], Result>,
  'adminUpdateGateCChecklist' : ActorMethod<
    [
      [] | [boolean],
      [] | [boolean],
      [] | [boolean],
      [] | [boolean],
      [] | [bigint],
    ],
    undefined
  >,
  'appealDispute' : ActorMethod<[DisputeId, string], Result>,
  'assignJurors' : ActorMethod<[DisputeId], Result>,
  'banUser' : ActorMethod<[UserId, string], undefined>,
  'bumpListing' : ActorMethod<[ListingId], Result>,
  'buyerCancelBeforeShipment' : ActorMethod<[TradeId], Result_34>,
  'calculateShippingCost' : ActorMethod<
    [string, string, number, ShippingServiceType],
    { 'ok' : { 'transitDays' : bigint, 'costUAH' : bigint } } |
      { 'err' : string }
  >,
  'canConfirmDelivery' : ActorMethod<[TradeId], boolean>,
  'castJurorVote' : ActorMethod<[DisputeId, JurorVoteChoice, string], Result>,
  'checkAndExpireTimeouts' : ActorMethod<[], bigint>,
  'checkAndReleaseListingStakeAfterClaim' : ActorMethod<
    [ListingId, TradeId],
    Result_15
  >,
  'checkDigitalInspectionDeadline' : ActorMethod<[TradeId], Result_15>,
  'checkFulfillmentDeadlines' : ActorMethod<
    [],
    {
      'disputeL1Escalations' : bigint,
      'digitalAutoCompletions' : bigint,
      'autoCompletions' : bigint,
      'shipByEscalations' : bigint,
    }
  >,
  'checkHandshakeTimeouts' : ActorMethod<[], bigint>,
  'checkJuryDeadlines' : ActorMethod<[], bigint>,
  'checkPaymentIntentExpiry' : ActorMethod<[], bigint>,
  'cleanupResolvedListings' : ActorMethod<
    [],
    {
      'deletedCount' : bigint,
      'skippedByDispute' : bigint,
      'photosToDelete' : Array<string>,
    }
  >,
  'closeProposal' : ActorMethod<[ProposalId], Result_33>,
  'confirmBuyerReceipt' : ActorMethod<[TradeId], Result>,
  'confirmPaymentReceived' : ActorMethod<[TradeId], Result>,
  'confirmPaymentSent' : ActorMethod<[TradeId], Result>,
  'confirmSellerHandshake' : ActorMethod<[TradeId], Result>,
  'createListing' : ActorMethod<
    [
      string,
      string,
      ListingCategory,
      [] | [CategoryId],
      bigint,
      TradeToken,
      ItemCondition,
      Array<string>,
      string,
      Array<ShippingMethod>,
      boolean,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [PackageDetails],
      [] | [NovaPoshtaConfig],
      [] | [UkrposhtaConfig],
      [] | [MeestConfig],
      Array<CategoryAttributeValue>,
    ],
    Result_32
  >,
  'createMeestTTN' : ActorMethod<[TradeId], Result_11>,
  'createMeestWaybill' : ActorMethod<
    [string, string, number, string, bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createNovaPoshtaTTN' : ActorMethod<[TradeId], Result_11>,
  'createPaymentIntent' : ActorMethod<
    [TradeId, [] | [bigint], PaymentSettlementPath],
    Result_31
  >,
  'createProposal' : ActorMethod<[ProposalType, string], Result_30>,
  'createUkrPoshtaWaybill' : ActorMethod<
    [string, string, number, string, bigint],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'createUkrposhtaTTN' : ActorMethod<[TradeId], Result_11>,
  'createWaybill' : ActorMethod<
    [string, string, number, string, bigint, ShippingServiceType],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deactivateListing' : ActorMethod<[ListingId], Result>,
  'declineSellerHandshake' : ActorMethod<[TradeId], Result>,
  'deleteMyAccount' : ActorMethod<[string], Result>,
  'deleteSavedSearch' : ActorMethod<[SavedSearchId], Result>,
  'demoteFromModerator' : ActorMethod<[UserId], undefined>,
  'depositStake' : ActorMethod<[TradeToken, bigint], Result>,
  'escalateDisputeToL2' : ActorMethod<[DisputeId], Result>,
  'estimateTokenAmount' : ActorMethod<[bigint, TradeToken], [] | [bigint]>,
  'executeProposal' : ActorMethod<[ProposalId], Result>,
  'exportMyAccountData' : ActorMethod<[], AccountExportBundle>,
  'getAllUsers' : ActorMethod<[bigint, bigint, UserFilter], PagedResult_1>,
  'getAuditLog' : ActorMethod<[bigint, bigint, AuditFilter], PagedResult>,
  'getCachedRate' : ActorMethod<[TradeToken], [] | [RateCacheEntry]>,
  'getCategoryAttributeSchema' : ActorMethod<
    [CategoryId],
    Array<CategoryAttributeField>
  >,
  'getComplianceNotes' : ActorMethod<[UserId], Array<ComplianceNote>>,
  'getCyclesStatus' : ActorMethod<[], CyclesStatus>,
  'getDashboardMetrics' : ActorMethod<[], PlatformMetrics__1>,
  'getDigitalDelivery' : ActorMethod<[TradeId], Result_29>,
  'getDispute' : ActorMethod<[DisputeId], [] | [DisputeView]>,
  'getDisputeJurors' : ActorMethod<[DisputeId], [] | [JuryView]>,
  'getDisputesByTrade' : ActorMethod<[TradeId], Array<DisputeView>>,
  'getEndpointErrorRate' : ActorMethod<[string, bigint], number>,
  'getErrorLog' : ActorMethod<[bigint, [] | [string]], Array<ErrorLogEntry>>,
  'getExecutionHistory' : ActorMethod<[], Array<ProposalView>>,
  'getExpiredListings' : ActorMethod<[bigint, bigint], Array<ListingCard>>,
  'getExplorerApiKeyStatus' : ActorMethod<
    [],
    {
      'bscScanConfigured' : boolean,
      'infuraConfigured' : boolean,
      'tronGridConfigured' : boolean,
    }
  >,
  'getFavoriteListings' : ActorMethod<[], Array<ListingCard>>,
  'getFeedbackForTrade' : ActorMethod<[TradeId], Array<Feedback>>,
  'getInsurancePayoutRequest' : ActorMethod<[bigint], [] | [PayoutRequestView]>,
  'getInsuranceProtectionView' : ActorMethod<
    [bigint, TradeToken],
    ProtectionView
  >,
  'getInsuranceReserveLedger' : ActorMethod<[], ReserveLedgerView>,
  'getJurorDashboard' : ActorMethod<[], Array<JurorDashboardEntry>>,
  'getJuryPool' : ActorMethod<[], Result_28>,
  'getLinkPreview' : ActorMethod<[string], Result_27>,
  'getLinkedWallets' : ActorMethod<[], Array<LinkedExternalWallet>>,
  'getLinkedWalletsForToken' : ActorMethod<
    [TradeToken],
    Array<LinkedExternalWallet>
  >,
  'getListing' : ActorMethod<[ListingId], [] | [ListingCard]>,
  'getListingInquiryMessages' : ActorMethod<[ListingId, UserId], Result_26>,
  'getListingStake' : ActorMethod<[ListingId], [] | [ListingStakeView]>,
  'getListingsByUser' : ActorMethod<
    [UserId, bigint, bigint],
    Array<ListingCard>
  >,
  'getMeestPUDOs' : ActorMethod<
    [string, [] | [string], [] | [bigint]],
    Result_25
  >,
  'getMetricsSummary' : ActorMethod<[], MetricsSummary>,
  'getModeratorThread' : ActorMethod<[TradeId], Array<Message>>,
  'getModuleMetrics' : ActorMethod<[], Array<ModuleMetricsView>>,
  'getMyDisputes' : ActorMethod<[], Array<DisputeView>>,
  'getMyFeedback' : ActorMethod<[], Array<Feedback>>,
  'getMyJurorDashboard' : ActorMethod<[], Result_24>,
  'getMyListings' : ActorMethod<[bigint, bigint], Array<ListingCard>>,
  'getMyPaymentMethods' : ActorMethod<[], Array<PaymentMethod>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMyStakeBalance' : ActorMethod<[TradeToken], StakeBalanceView>,
  'getMyTrades' : ActorMethod<
    [{ 'all' : null } | { 'seller' : null } | { 'buyer' : null }],
    Array<TradeView>
  >,
  'getMyTransactionHistory' : ActorMethod<
    [TxHistoryFilter, bigint, bigint],
    Page
  >,
  'getNovaPoshtaBranches' : ActorMethod<
    [string, [] | [string], [] | [bigint]],
    Result_23
  >,
  'getNovaPoshtaCityRef' : ActorMethod<[string], Result_11>,
  'getOpenDisputeQueue' : ActorMethod<[bigint, bigint], Result_22>,
  'getP95Latency' : ActorMethod<[string, bigint], bigint>,
  'getPaymentMethods' : ActorMethod<[], Array<PaymentMethod>>,
  'getPaymentVerificationStatus' : ActorMethod<
    [TradeId],
    [] | [PaymentVerificationResult]
  >,
  'getPlatformFlags' : ActorMethod<
    [],
    {
      'ckUsdcLedgerId' : string,
      'ckUsdtLedgerId' : string,
      'trustlessEscrowEnabled' : boolean,
    }
  >,
  'getPlatformMetrics' : ActorMethod<[], PlatformMetrics>,
  'getProposal' : ActorMethod<[ProposalId], [] | [ProposalView]>,
  'getProposals' : ActorMethod<[[] | [ProposalStatus]], Array<ProposalView>>,
  'getPublicListingsByUser' : ActorMethod<
    [UserId, bigint, bigint],
    Array<ListingCard>
  >,
  'getRequestRate' : ActorMethod<[string, bigint], bigint>,
  'getRequiredListingStake' : ActorMethod<[bigint, TradeToken], bigint>,
  'getSavedSearches' : ActorMethod<[], Array<SavedSearch>>,
  'getSellerFaultSettlementView' : ActorMethod<
    [TradeId],
    [] | [SellerFaultSettlementView]
  >,
  'getSellerLiability' : ActorMethod<[Principal], Result_21>,
  'getSellerPaymentMethodsForTrade' : ActorMethod<
    [TradeId],
    Array<PaymentMethod>
  >,
  'getShippingOptions' : ActorMethod<
    [number, string, string],
    { 'ok' : Array<ShippingOption> } |
      { 'err' : string }
  >,
  'getStakeOnChainEnabled' : ActorMethod<[], boolean>,
  'getSupportedCarriers' : ActorMethod<[], Array<CarrierInfo>>,
  'getSupportedTokens' : ActorMethod<[], Array<TokenInfo>>,
  'getSystemSettings' : ActorMethod<
    [],
    {
      'maxListingPriceUSD' : bigint,
      'paymentTimeoutHours' : bigint,
      'allowedTokens' : Array<TradeToken>,
      'cyclesBalanceThreshold' : bigint,
      'minTradeAmountUSD' : bigint,
      'errorRateThreshold' : number,
    }
  >,
  'getTokenInfo' : ActorMethod<[TradeToken], [] | [TokenInfo]>,
  'getTrade' : ActorMethod<[TradeId], [] | [TradeView]>,
  'getTradeFeeQuote' : ActorMethod<[ListingId], [] | [TradeFeeQuote]>,
  'getTradeMessages' : ActorMethod<[TradeId, bigint, bigint], Array<Message>>,
  'getTradeNotifications' : ActorMethod<[], Array<NotificationEvent>>,
  'getTradePaymentStatus' : ActorMethod<[TradeId], [] | [TradePaymentStatus]>,
  'getTradesByListing' : ActorMethod<[ListingId], Array<TradeView>>,
  'getTradesPerDay' : ActorMethod<
    [bigint],
    Array<{ 'date' : string, 'count' : bigint }>
  >,
  'getTreasuryBalance' : ActorMethod<[], bigint>,
  'getTreasuryWithdrawals' : ActorMethod<[], Array<WithdrawalRecord>>,
  'getUkrposhtaOffices' : ActorMethod<
    [string, [] | [string], [] | [bigint]],
    Result_20
  >,
  'getUnifiedTrackingInfo' : ActorMethod<[TradeId], Result_19>,
  'getUnreadCount' : ActorMethod<[], Array<[TradeId, bigint]>>,
  'getUserFeedback' : ActorMethod<[UserId], Array<Feedback>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserReputationStats' : ActorMethod<[UserId], [] | [ReputationStats]>,
  'getVaultAddresses' : ActorMethod<[], Array<VaultAddressView>>,
  'getVaultBalance' : ActorMethod<[ChainType], [] | [BalanceView]>,
  'incrementListingView' : ActorMethod<[ListingId], undefined>,
  'initiateOnChainTrade' : ActorMethod<[TradeId], Result_18>,
  'initiateTrade' : ActorMethod<
    [ListingId, TradeToken, [] | [ShippingSelection]],
    Result_18
  >,
  'isListingFavorite' : ActorMethod<[ListingId], boolean>,
  'leaveFeedback' : ActorMethod<[TradeId, UserId, bigint, string], Result_17>,
  'linkExternalWallet' : ActorMethod<[bigint, string, string], Result_14>,
  'listCategories' : ActorMethod<[], Array<CategoryNode>>,
  'markAllNotificationsRead' : ActorMethod<[], Result>,
  'markNotificationRead' : ActorMethod<[bigint], Result>,
  'markShipped' : ActorMethod<[TradeId, string], Result>,
  'markTradeAsRead' : ActorMethod<[TradeId], undefined>,
  'openDigitalDispute' : ActorMethod<[TradeId, string], Result_16>,
  'openDispute' : ActorMethod<
    [TradeId, DisputeReason, string, DisputeEvidencePack],
    Result_16
  >,
  'platformFeeBps' : ActorMethod<[], bigint>,
  'processDisputeSlaEscalations' : ActorMethod<[], bigint>,
  'promoteToModerator' : ActorMethod<[UserId], undefined>,
  'proposeCancelTrade' : ActorMethod<[TradeId], Result_15>,
  'publishListing' : ActorMethod<[ListingId], Result>,
  'reactivateListing' : ActorMethod<[ListingId], Result>,
  'recordRequest' : ActorMethod<[string, bigint, bigint], undefined>,
  'recordTreasuryFee' : ActorMethod<[TradeId, bigint, TradeToken], undefined>,
  'recoverWalletLink' : ActorMethod<[bigint, string, string], Result_14>,
  'refreshRates' : ActorMethod<[], bigint>,
  'refreshVaultBalance' : ActorMethod<[ChainType], BalanceView>,
  'registerAsJuror' : ActorMethod<[number], Result>,
  'registerDigitalFile' : ActorMethod<
    [ListingId, string, string, bigint, string, string, [] | [string]],
    Result_13
  >,
  'releaseListingStake' : ActorMethod<[ListingId], Result_9>,
  'removeFavorite' : ActorMethod<[ListingId], Result>,
  'removeListingByAdmin' : ActorMethod<[ListingId, string], undefined>,
  'reopenDispute' : ActorMethod<[DisputeId], Result>,
  'reportListing' : ActorMethod<[ListingId, string], Result>,
  'requestRefund' : ActorMethod<[TradeId], Result>,
  'requestWalletLinkNonce' : ActorMethod<
    [WalletChain, string, WalletLinkPurpose, string],
    Result_12
  >,
  'resolveDispute' : ActorMethod<
    [DisputeId, ResolutionOutcome, string],
    Result
  >,
  'resolveDisputeEscrow' : ActorMethod<[DisputeId, ResolutionOutcome], Result>,
  'retryMeestTTNCreation' : ActorMethod<[TradeId], Result_11>,
  'retryPendingOnChainSettlements' : ActorMethod<
    [],
    { 'attempted' : bigint, 'failed' : bigint, 'succeeded' : bigint }
  >,
  'retryTTNCreation' : ActorMethod<[TradeId], Result_11>,
  'retryUkrposhtaTTNCreation' : ActorMethod<[TradeId], Result_11>,
  /**
   * / This canister's own principal — used as the escrow recipient in ICRC-2 transfers.
   */
  'saveSearch' : ActorMethod<[string, string], Result_10>,
  'searchListings' : ActorMethod<
    [
      [] | [string],
      [] | [ListingCategory],
      [] | [CategoryId],
      [] | [bigint],
      [] | [bigint],
      [] | [string],
      [] | [ItemCondition],
      [] | [ShippingCarrier],
      bigint,
      bigint,
      [] | [TradeToken],
    ],
    Array<ListingCard>
  >,
  'seizeListingStake' : ActorMethod<[ListingId, [] | [string]], Result_9>,
  'sendListingInquiry' : ActorMethod<[ListingId, string], Result_8>,
  'sendListingInquiryReply' : ActorMethod<
    [ListingId, UserId, string],
    Result_8
  >,
  'sendMessage' : ActorMethod<
    [TradeId, string, Array<MediaAttachment>],
    Result_7
  >,
  'setAvalancheApiKey' : ActorMethod<[string], undefined>,
  'setBscScanApiKey' : ActorMethod<[string], undefined>,
  'setDisputeUnderReview' : ActorMethod<[DisputeId], Result>,
  'setInfuraApiKey' : ActorMethod<[string], undefined>,
  'setMeestApiKey' : ActorMethod<[string], undefined>,
  'setMyProfile' : ActorMethod<
    [string, string, string, [] | [string]],
    Result_6
  >,
  'setNovaPoshtaApiKey' : ActorMethod<[string], undefined>,
  'setPolygonApiKey' : ActorMethod<[string], undefined>,
  'setSavedSearchAlerts' : ActorMethod<[SavedSearchId, boolean], Result>,
  'setSolanaRpcUrl' : ActorMethod<[string], undefined>,
  'setTronGridApiKey' : ActorMethod<[string], undefined>,
  'setUkrPoshtaApiKey' : ActorMethod<[string], undefined>,
  'snapshotPayoutWallet' : ActorMethod<[TradeId, bigint], Result_5>,
  'submitJurorVote' : ActorMethod<[DisputeId, JurorVoteChoice, string], Result>,
  'suspendUser' : ActorMethod<[UserId, Timestamp, string], undefined>,
  'trackMeestShipment' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'trackShipment' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'trackUkrPoshtaShipment' : ActorMethod<
    [string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'tradeCapTierCheck' : ActorMethod<[ListingId, TradeToken], TradeCapTierCheck>,
  'transformJsonRpcResponse' : ActorMethod<
    [{ 'context' : Uint8Array, 'response' : HttpResponse }],
    HttpResponse
  >,
  'transformPaymentResponse' : ActorMethod<
    [{ 'context' : Uint8Array, 'response' : HttpResponse }],
    HttpResponse
  >,
  'transformShippingResponse' : ActorMethod<
    [{ 'context' : Uint8Array, 'response' : ShipHttpResponse }],
    ShipHttpResponse
  >,
  'transformVaultResponse' : ActorMethod<
    [{ 'context' : Uint8Array, 'response' : VaultHttpResponse }],
    VaultHttpResponse
  >,
  'unbanUser' : ActorMethod<[UserId], undefined>,
  'unlinkExternalWallet' : ActorMethod<[bigint], Result>,
  'unregisterJuror' : ActorMethod<[], Result>,
  'updateListing' : ActorMethod<
    [
      ListingId,
      string,
      string,
      ListingCategory,
      [] | [CategoryId],
      bigint,
      TradeToken,
      ItemCondition,
      Array<string>,
      string,
      Array<ShippingMethod>,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [PackageDetails],
      [] | [NovaPoshtaConfig],
      [] | [UkrposhtaConfig],
      [] | [MeestConfig],
      Array<CategoryAttributeValue>,
    ],
    Result
  >,
  'updateSystemSettings' : ActorMethod<
    [bigint, bigint, Array<TradeToken>, bigint, bigint, number],
    undefined
  >,
  'verifyEvmAddress' : ActorMethod<[string, string], Result_1>,
  'verifyPayment' : ActorMethod<[TradeId, string, TradeToken], Result_2>,
  'verifySolanaAddress' : ActorMethod<[string], Result_1>,
  'verifyTradePayment' : ActorMethod<[TradeId, string, string], Result_2>,
  'verifyTradePaymentExplorer' : ActorMethod<
    [TradeId, string, TradeToken],
    Result_2
  >,
  'verifyTronAddress' : ActorMethod<[string], Result_1>,
  'voteOnProposal' : ActorMethod<[ProposalId, boolean], Result>,
  'withdrawStake' : ActorMethod<[TradeToken, bigint], Result>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];