/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const DisputeId = IDL.Nat;
export const MediaAttachment = IDL.Record({
  'url' : IDL.Text,
  'mimeType' : IDL.Text,
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
});
export const Error = IDL.Variant({
  'insufficient_funds' : IDL.Null,
  'rate_limited' : IDL.Null,
  'dispute_already_open' : IDL.Null,
  'not_found' : IDL.Null,
  'banned' : IDL.Null,
  'invalid_input' : IDL.Text,
  'escrow_error' : IDL.Text,
  'already_exists' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const TradeToken = IDL.Variant({
  'USDT_ERC20' : IDL.Null,
  'USDT_AVAX' : IDL.Null,
  'USDC_ERC20' : IDL.Null,
  'USDT_BEP20' : IDL.Null,
  'USDC_AVAX' : IDL.Null,
  'ckUSDC' : IDL.Null,
  'ckUSDT' : IDL.Null,
  'USDC_SPL' : IDL.Null,
  'USDT_TRC20' : IDL.Null,
  'USDC_POLYGON' : IDL.Null,
  'USDT_POLYGON' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const AddressVerification = IDL.Record({
  'active' : IDL.Bool,
  'expiresAt' : Timestamp,
  'level' : IDL.Nat,
  'txCount' : IDL.Nat,
  'verifiedAt' : Timestamp,
});
export const PaymentMethod = IDL.Record({
  'token' : TradeToken,
  'addedAt' : Timestamp,
  'address' : IDL.Text,
  'verification' : IDL.Opt(AddressVerification),
});
export const Result_25 = IDL.Variant({ 'ok' : PaymentMethod, 'err' : Error });
export const TradeId = IDL.Nat;
export const EscrowAccount = IDL.Record({
  'fee' : IDL.Nat,
  'sellerPrincipal' : UserId,
  'token' : TradeToken,
  'ledgerCanisterId' : IDL.Principal,
  'deadline' : Timestamp,
  'tradeId' : TradeId,
  'lockedAt' : Timestamp,
  'buyerPrincipal' : UserId,
  'amount' : IDL.Nat,
});
export const TradeStatus = IDL.Variant({
  'payment_verified' : IDL.Null,
  'cancelled' : IDL.Null,
  'disputed' : IDL.Null,
  'pending' : IDL.Null,
  'refunded' : IDL.Null,
  'funded' : IDL.Null,
  'buyer_confirmed' : IDL.Null,
  'complete' : IDL.Null,
  'awaiting_approval' : IDL.Null,
});
export const ListingId = IDL.Nat;
export const ShippingSelection = IDL.Record({
  'provider' : IDL.Text,
  'branchRef' : IDL.Opt(IDL.Text),
  'cost' : IDL.Nat,
  'deliveryType' : IDL.Text,
  'address' : IDL.Opt(IDL.Text),
});
export const DigitalDelivery = IDL.Record({
  'inspectionDeadline' : IDL.Opt(Timestamp),
  'password' : IDL.Opt(IDL.Text),
  'fileHash' : IDL.Opt(IDL.Text),
  'revealedAt' : IDL.Opt(Timestamp),
  'fileUrl' : IDL.Text,
});
export const TTNStatus = IDL.Variant({
  'Failed' : IDL.Null,
  'Success' : IDL.Null,
  'InProgress' : IDL.Null,
  'Pending' : IDL.Null,
});
export const TradeView = IDL.Record({
  'id' : TradeId,
  'escrowAccount' : IDL.Opt(EscrowAccount),
  'status' : TradeStatus,
  'completedAt' : IDL.Opt(Timestamp),
  'listing' : ListingId,
  'token' : TradeToken,
  'ttnNumber' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'confirmedAt' : IDL.Opt(Timestamp),
  'seller' : UserId,
  'shippingSelection' : IDL.Opt(ShippingSelection),
  'refundDeadline' : IDL.Opt(Timestamp),
  'fundedAt' : IDL.Opt(Timestamp),
  'buyer' : UserId,
  'amount' : IDL.Nat,
  'digitalDelivery' : IDL.Opt(DigitalDelivery),
  'ttnCreationStatus' : TTNStatus,
});
export const ShippingServiceType = IDL.Variant({
  'express' : IDL.Null,
  'standard' : IDL.Null,
});
export const JurorVoteChoice = IDL.Variant({
  'sellerWins' : IDL.Null,
  'buyerWins' : IDL.Null,
});
export const Result_8 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : Error });
export const ProposalId = IDL.Nat;
export const ProposalStatus = IDL.Variant({
  'active' : IDL.Null,
  'expired' : IDL.Null,
  'rejected' : IDL.Null,
  'executed' : IDL.Null,
  'passed' : IDL.Null,
});
export const Result_24 = IDL.Variant({ 'ok' : ProposalStatus, 'err' : Error });
export const ListingCategory = IDL.Variant({
  'clothing' : IDL.Null,
  'other' : IDL.Null,
  'books' : IDL.Null,
  'digital' : IDL.Null,
  'services' : IDL.Null,
  'electronics' : IDL.Null,
});
export const ItemCondition = IDL.Variant({
  'new' : IDL.Null,
  'fair' : IDL.Null,
  'good' : IDL.Null,
  'poor' : IDL.Null,
  'likeNew' : IDL.Null,
});
export const ShippingCarrier = IDL.Variant({
  'meest' : IDL.Null,
  'nova_poshta' : IDL.Null,
  'self_pickup' : IDL.Null,
  'digital' : IDL.Null,
  'ukrposhta' : IDL.Null,
});
export const ShippingMethod = IDL.Record({
  'type' : ShippingServiceType,
  'estimatedDays' : IDL.Nat,
  'carrier' : ShippingCarrier,
});
export const PackageDetails = IDL.Record({
  'weight' : IDL.Nat,
  'height' : IDL.Nat,
  'places' : IDL.Nat,
  'length' : IDL.Nat,
  'declaredValue' : IDL.Nat,
  'width' : IDL.Nat,
});
export const NovaPoshtaConfig = IDL.Record({
  'enabled' : IDL.Bool,
  'senderBranchRef' : IDL.Text,
  'deliveryTypes' : IDL.Vec(IDL.Text),
});
export const UkrposhtaConfig = IDL.Record({
  'enabled' : IDL.Bool,
  'senderOfficeRef' : IDL.Opt(IDL.Text),
  'deliveryTypes' : IDL.Vec(IDL.Text),
});
export const MeestConfig = IDL.Record({
  'senderPudoRef' : IDL.Opt(IDL.Text),
  'enabled' : IDL.Bool,
  'deliveryTypes' : IDL.Vec(IDL.Text),
});
export const TrustLevel = IDL.Variant({
  'new' : IDL.Null,
  'bronze' : IDL.Null,
  'gold' : IDL.Null,
  'silver' : IDL.Null,
});
export const ListingCard = IDL.Record({
  'id' : ListingId,
  'title' : IDL.Text,
  'sellerPrincipal' : UserId,
  'priceAmount' : IDL.Nat,
  'shippingMethods' : IDL.Vec(ShippingMethod),
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'sellerTrustLevel' : TrustLevel,
  'sellerRating' : IDL.Int,
  'priceToken' : TradeToken,
  'category' : ListingCategory,
  'sellerUsername' : IDL.Text,
  'location' : IDL.Text,
  'photos' : IDL.Vec(IDL.Text),
  'digitalFileUrl' : IDL.Text,
  'condition' : ItemCondition,
});
export const Result_23 = IDL.Variant({ 'ok' : ListingCard, 'err' : Error });
export const Result_7 = IDL.Variant({ 'ok' : IDL.Text, 'err' : Error });
export const ProposalType = IDL.Variant({
  'TextResolution' : IDL.Record({ 'description' : IDL.Text }),
  'TreasuryTransfer' : IDL.Record({
    'recipient' : IDL.Principal,
    'amount' : IDL.Nat,
  }),
  'ParameterChange' : IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text }),
});
export const Result_22 = IDL.Variant({ 'ok' : ProposalId, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'moderator' : IDL.Null,
  'user' : IDL.Null,
});
export const UserFilter = IDL.Record({
  'roleFilter' : IDL.Opt(UserRole),
  'bannedFilter' : IDL.Opt(IDL.Bool),
});
export const LiabilityEvent = IDL.Record({
  'tradeId' : IDL.Opt(IDL.Nat),
  'timestamp' : Timestamp,
  'amount' : IDL.Int,
  'reason' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'reputationScore' : IDL.Int,
  'username' : IDL.Text,
  'createdAt' : Timestamp,
  'trustLevel' : TrustLevel,
  'role' : UserRole,
  'liabilityBalance' : IDL.Int,
  'avatarUrl' : IDL.Text,
  'liabilityHistory' : IDL.Vec(LiabilityEvent),
  'isBanned' : IDL.Bool,
  'suspendedUntil' : IDL.Opt(Timestamp),
  'paymentMethods' : IDL.Vec(PaymentMethod),
});
export const PagedResult_1 = IDL.Record({
  'page' : IDL.Nat,
  'totalCount' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(UserProfile),
});
export const AuditFilter = IDL.Record({
  'targetFilter' : IDL.Opt(IDL.Text),
  'actionFilter' : IDL.Opt(IDL.Text),
  'actorFilter' : IDL.Opt(IDL.Principal),
});
export const AuditEntry = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'actorId' : IDL.Principal,
  'timestamp' : Timestamp,
  'details' : IDL.Text,
  'targetId' : IDL.Opt(IDL.Text),
});
export const PagedResult = IDL.Record({
  'page' : IDL.Nat,
  'totalCount' : IDL.Nat,
  'pageSize' : IDL.Nat,
  'items' : IDL.Vec(AuditEntry),
});
export const RateCacheEntry = IDL.Record({
  'rateInCents' : IDL.Nat,
  'fetchedAt' : IDL.Int,
});
export const ComplianceNote = IDL.Record({
  'id' : IDL.Nat,
  'note' : IDL.Text,
  'actorId' : IDL.Principal,
  'timestamp' : Timestamp,
});
export const CyclesStatus = IDL.Record({
  'isWarning' : IDL.Bool,
  'currentBalance' : IDL.Nat,
  'warningThreshold' : IDL.Nat,
  'estimatedDailyBurn' : IDL.Nat,
});
export const PlatformMetrics__1 = IDL.Record({
  'totalTrades' : IDL.Nat,
  'activeUsersLast24h' : IDL.Nat,
  'totalVolume' : IDL.Float64,
  'monthlyActiveUsers' : IDL.Nat,
  'completedTrades' : IDL.Nat,
  'avgSettlementTimeMin' : IDL.Float64,
  'disputeRate' : IDL.Float64,
  'swapSuccessRate' : IDL.Float64,
});
export const Result_21 = IDL.Variant({ 'ok' : DigitalDelivery, 'err' : Error });
export const DisputeStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'opened' : IDL.Null,
  'escalated_to_admin' : IDL.Null,
  'under_review' : IDL.Null,
});
export const JurorVote = IDL.Record({
  'vote' : JurorVoteChoice,
  'reasoning' : IDL.Text,
  'timestamp' : IDL.Int,
  'jurorPrincipal' : IDL.Principal,
});
export const JuryView = IDL.Record({
  'jurors' : IDL.Vec(IDL.Principal),
  'votes' : IDL.Vec(JurorVote),
  'deadline' : Timestamp,
});
export const ResolutionOutcome = IDL.Variant({
  'buyer_wins' : IDL.Null,
  'split' : IDL.Null,
  'seller_wins' : IDL.Null,
});
export const DisputeResolution = IDL.Record({
  'notes' : IDL.Text,
  'outcome' : ResolutionOutcome,
  'resolvedBy' : UserId,
});
export const DisputeReason = IDL.Variant({
  'other' : IDL.Null,
  'item_damaged' : IDL.Null,
  'seller_unresponsive' : IDL.Null,
  'item_differs' : IDL.Null,
  'item_not_received' : IDL.Null,
});
export const DisputeView = IDL.Record({
  'id' : DisputeId,
  'evidenceUrls' : IDL.Vec(IDL.Text),
  'status' : DisputeStatus,
  'trade' : TradeId,
  'evidenceAttachments' : IDL.Vec(MediaAttachment),
  'initiator' : UserId,
  'jury' : IDL.Opt(JuryView),
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'resolution' : IDL.Opt(DisputeResolution),
  'moderatorNotes' : IDL.Vec(IDL.Text),
  'resolvedAt' : IDL.Opt(Timestamp),
  'reason' : DisputeReason,
});
export const ErrorSeverity = IDL.Variant({
  'warning' : IDL.Null,
  'info' : IDL.Null,
  'error' : IDL.Null,
  'critical' : IDL.Null,
});
export const ErrorLogEntry = IDL.Record({
  'id' : IDL.Nat,
  'functionName' : IDL.Text,
  'moduleName' : IDL.Text,
  'errorMessage' : IDL.Text,
  'userPrincipal' : IDL.Opt(IDL.Principal),
  'timestamp' : IDL.Int,
  'severity' : ErrorSeverity,
});
export const ProposalView = IDL.Record({
  'id' : ProposalId,
  'status' : ProposalStatus,
  'noVotes' : IDL.Nat,
  'executedAt' : IDL.Opt(Timestamp),
  'yesVotes' : IDL.Nat,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'deadline' : Timestamp,
  'proposalType' : ProposalType,
  'proposer' : UserId,
  'voterCount' : IDL.Nat,
});
export const FeedbackId = IDL.Nat;
export const Feedback = IDL.Record({
  'id' : FeedbackId,
  'trade' : TradeId,
  'createdAt' : Timestamp,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
  'reviewed' : UserId,
  'reviewer' : UserId,
});
export const JurorDashboardEntry = IDL.Record({
  'deadline' : Timestamp,
  'tradeId' : TradeId,
  'sellerVotes' : IDL.Nat,
  'hasVoted' : IDL.Bool,
  'totalJurors' : IDL.Nat,
  'buyerVotes' : IDL.Nat,
  'reason' : DisputeReason,
  'disputeId' : DisputeId,
});
export const JurorStats = IDL.Record({
  'principal' : IDL.Principal,
  'successRate' : IDL.Float64,
  'activeCount' : IDL.Nat,
  'stakedAmount' : IDL.Float64,
  'registeredAt' : Timestamp,
  'resolvedCount' : IDL.Nat,
});
export const Result_20 = IDL.Variant({
  'ok' : IDL.Vec(JurorStats),
  'err' : Error,
});
export const LinkPreview = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Opt(IDL.Text),
  'fetchedAt' : Timestamp,
  'description' : IDL.Opt(IDL.Text),
  'siteName' : IDL.Opt(IDL.Text),
  'imageUrl' : IDL.Opt(IDL.Text),
});
export const Result_19 = IDL.Variant({ 'ok' : LinkPreview, 'err' : Error });
export const Result_18 = IDL.Variant({
  'ok' : IDL.Vec(
    IDL.Record({
      'id' : IDL.Text,
      'name' : IDL.Text,
      'type' : IDL.Text,
      'address' : IDL.Text,
    })
  ),
  'err' : Error,
});
export const MetricsSummary = IDL.Record({
  'totalTrades' : IDL.Nat,
  'totalVolume' : IDL.Nat,
  'p95LatencyMs' : IDL.Nat,
  'errorRate' : IDL.Float64,
  'memoryUsage' : IDL.Nat,
  'activeTrades' : IDL.Nat,
  'avgTradeValue' : IDL.Nat,
  'disputeRate' : IDL.Float64,
  'totalRevenue' : IDL.Nat,
  'cyclesBalance' : IDL.Nat,
});
export const MessageId = IDL.Nat;
export const Message = IDL.Record({
  'id' : MessageId,
  'attachmentUrl' : IDL.Opt(IDL.Text),
  'trade' : TradeId,
  'content' : IDL.Text,
  'sender' : UserId,
  'sentAt' : Timestamp,
  'attachments' : IDL.Vec(MediaAttachment),
});
export const ModuleMetricsView = IDL.Record({
  'memoryUsedBytes' : IDL.Nat,
  'cyclesConsumed' : IDL.Nat,
  'moduleName' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'errorCount' : IDL.Nat,
  'requestCount' : IDL.Nat,
});
export const Result_17 = IDL.Variant({
  'ok' : IDL.Vec(JurorDashboardEntry),
  'err' : Error,
});
export const TxHistoryFilter = IDL.Record({
  'to' : IDL.Opt(Timestamp),
  'status' : IDL.Opt(TradeStatus),
  'token' : IDL.Opt(TradeToken),
  'from' : IDL.Opt(Timestamp),
});
export const Page = IDL.Record({
  'totalCount' : IDL.Nat,
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
  'items' : IDL.Vec(TradeView),
});
export const NovaPoshtaBranch = IDL.Record({
  'ref' : IDL.Text,
  'cityRef' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'schedule' : IDL.Opt(IDL.Text),
});
export const Result_16 = IDL.Variant({
  'ok' : IDL.Vec(NovaPoshtaBranch),
  'err' : Error,
});
export const Result_15 = IDL.Variant({
  'ok' : IDL.Vec(DisputeView),
  'err' : Error,
});
export const PaymentVerificationStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'failed' : IDL.Null,
});
export const PaymentVerificationResult = IDL.Record({
  'status' : PaymentVerificationStatus,
  'blockNumber' : IDL.Nat,
  'confirmedAmount' : IDL.Float64,
  'confirmedRecipient' : IDL.Text,
  'txHash' : IDL.Text,
  'errorReason' : IDL.Opt(IDL.Text),
});
export const PlatformMetrics = IDL.Record({
  'totalTrades' : IDL.Nat,
  'activeUsersLast30d' : IDL.Nat,
  'avgTradeCompletionMs' : IDL.Nat,
  'totalListings' : IDL.Nat,
  'tradesByToken' : IDL.Vec(IDL.Tuple(TradeToken, IDL.Nat)),
  'disputeRatePct' : IDL.Nat,
});
export const Result_14 = IDL.Variant({ 'ok' : IDL.Int, 'err' : Error });
export const ShippingOption = IDL.Record({
  'cost' : IDL.Float64,
  'deliveryDays' : IDL.Nat,
  'available' : IDL.Bool,
  'carrier' : ShippingCarrier,
  'costNat' : IDL.Nat,
});
export const CarrierInfo = IDL.Record({
  'displayName' : IDL.Text,
  'description' : IDL.Text,
  'carrier' : ShippingCarrier,
});
export const TokenInfo = IDL.Record({
  'decimals' : IDL.Nat,
  'token' : TradeToken,
  'name' : IDL.Text,
  'network' : IDL.Text,
  'isNative' : IDL.Bool,
  'priority' : IDL.Nat,
  'symbol' : IDL.Text,
});
export const NotificationEvent = IDL.Record({
  'id' : IDL.Nat,
  'read' : IDL.Bool,
  'tradeId' : IDL.Nat,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'eventType' : IDL.Text,
});
export const TradePaymentStatus = IDL.Record({
  'status' : TradeStatus,
  'isManual' : IDL.Bool,
  'token' : TradeToken,
  'formattedAmount' : IDL.Text,
  'tradeId' : TradeId,
  'tokenInfo' : IDL.Opt(TokenInfo),
  'amount' : IDL.Nat,
  'verificationResult' : IDL.Opt(PaymentVerificationResult),
});
export const WithdrawalRecord = IDL.Record({
  'id' : IDL.Nat,
  'executedAt' : Timestamp,
  'recipient' : IDL.Principal,
  'amount' : IDL.Nat,
  'proposalId' : IDL.Nat,
});
export const Result_13 = IDL.Variant({
  'ok' : IDL.Vec(
    IDL.Record({ 'name' : IDL.Text, 'address' : IDL.Text, 'index' : IDL.Text })
  ),
  'err' : Error,
});
export const Result_12 = IDL.Variant({
  'ok' : IDL.Record({
    'status' : IDL.Text,
    'trackingNumber' : IDL.Text,
    'estimatedDelivery' : IDL.Opt(IDL.Text),
    'statusHistory' : IDL.Vec(
      IDL.Record({ 'status' : IDL.Text, 'timestamp' : IDL.Int })
    ),
    'isDelivered' : IDL.Bool,
    'carrier' : IDL.Text,
  }),
  'err' : Error,
});
export const ReputationStats = IDL.Record({
  'reputationScore' : IDL.Int,
  'trustLevel' : TrustLevel,
  'averageRating' : IDL.Float64,
  'completedTrades' : IDL.Nat,
  'disputeRate' : IDL.Float64,
});
export const ChainType = IDL.Variant({
  'SPL' : IDL.Null,
  'BEP20' : IDL.Null,
  'TRC20' : IDL.Null,
  'Polygon' : IDL.Null,
  'ERC20' : IDL.Null,
  'Avalanche' : IDL.Null,
});
export const VaultAddressView = IDL.Record({
  'chain' : ChainType,
  'network' : IDL.Text,
  'tokenSymbol' : IDL.Text,
  'address' : IDL.Text,
  'derivedAt' : IDL.Int,
});
export const BalanceView = IDL.Record({
  'chain' : ChainType,
  'error' : IDL.Opt(IDL.Text),
  'usdtBalance' : IDL.Nat,
  'usdcBalance' : IDL.Nat,
  'lastChecked' : IDL.Int,
});
export const Result_11 = IDL.Variant({ 'ok' : TradeId, 'err' : Error });
export const Result_10 = IDL.Variant({ 'ok' : FeedbackId, 'err' : Error });
export const Result_9 = IDL.Variant({ 'ok' : DisputeId, 'err' : Error });
export const Result_6 = IDL.Variant({ 'ok' : Message, 'err' : Error });
export const Result_5 = IDL.Variant({ 'ok' : UserProfile, 'err' : Error });
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpResponse = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const Result_1 = IDL.Variant({
  'ok' : IDL.Record({
    'active' : IDL.Bool,
    'txCount' : IDL.Nat,
    'verifiedAt' : Timestamp,
  }),
  'err' : Error,
});
export const Result_2 = IDL.Variant({
  'ok' : PaymentVerificationResult,
  'err' : Error,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func([IDL.Text], [], []),
  '_transformResponse' : IDL.Func(
      [
        IDL.Record({
          'context' : IDL.Vec(IDL.Nat8),
          'response' : IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        }),
      ],
      [
        IDL.Record({
          'status' : IDL.Nat,
          'body' : IDL.Vec(IDL.Nat8),
          'headers' : IDL.Vec(
            IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
          ),
        }),
      ],
      ['query'],
    ),
  'addComplianceNote' : IDL.Func([UserId, IDL.Text], [], []),
  'addEvidence' : IDL.Func([DisputeId, IDL.Vec(MediaAttachment)], [Result], []),
  'addModeratorNote' : IDL.Func([DisputeId, IDL.Text], [Result], []),
  'addPaymentMethod' : IDL.Func(
      [TradeToken, IDL.Text, IDL.Bool],
      [Result_25],
      [],
    ),
  'adminGetAllTrades' : IDL.Func([], [IDL.Vec(TradeView)], ['query']),
  'adminRemoveListing' : IDL.Func([ListingId, IDL.Text], [Result], []),
  'appealDispute' : IDL.Func([DisputeId, IDL.Text], [Result], []),
  'assignJurors' : IDL.Func([DisputeId], [Result], []),
  'banUser' : IDL.Func([UserId, IDL.Text], [], []),
  'calculateShippingCost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, ShippingServiceType],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'transitDays' : IDL.Nat, 'costUAH' : IDL.Nat }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'canConfirmDelivery' : IDL.Func([TradeId], [IDL.Bool], []),
  'castJurorVote' : IDL.Func(
      [DisputeId, JurorVoteChoice, IDL.Text],
      [Result],
      [],
    ),
  'checkAndExpireTimeouts' : IDL.Func([], [IDL.Nat], []),
  'checkDigitalInspectionDeadline' : IDL.Func([TradeId], [Result_8], []),
  'checkJuryDeadlines' : IDL.Func([], [IDL.Nat], []),
  'cleanupResolvedListings' : IDL.Func(
      [],
      [
        IDL.Record({
          'deletedCount' : IDL.Nat,
          'skippedByDispute' : IDL.Nat,
          'photosToDelete' : IDL.Vec(IDL.Text),
        }),
      ],
      [],
    ),
  'closeProposal' : IDL.Func([ProposalId], [Result_24], []),
  'confirmPaymentReceived' : IDL.Func([TradeId], [Result], []),
  'confirmPaymentSent' : IDL.Func([TradeId], [Result], []),
  'createListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ListingCategory,
        IDL.Nat,
        TradeToken,
        ItemCondition,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(ShippingMethod),
        IDL.Bool,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(PackageDetails),
        IDL.Opt(NovaPoshtaConfig),
        IDL.Opt(UkrposhtaConfig),
        IDL.Opt(MeestConfig),
      ],
      [Result_23],
      [],
    ),
  'createMeestTTN' : IDL.Func([TradeId], [Result_7], []),
  'createMeestWaybill' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'createNovaPoshtaTTN' : IDL.Func([TradeId], [Result_7], []),
  'createProposal' : IDL.Func([ProposalType, IDL.Text], [Result_22], []),
  'createUkrPoshtaWaybill' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'createUkrposhtaTTN' : IDL.Func([TradeId], [Result_7], []),
  'createWaybill' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Nat, ShippingServiceType],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deactivateListing' : IDL.Func([ListingId], [Result], []),
  'debugGetCertifiedData' : IDL.Func(
      [],
      [IDL.Opt(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  'demoteFromModerator' : IDL.Func([UserId], [], []),
  'estimateTokenAmount' : IDL.Func(
      [IDL.Nat, TradeToken],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'executeProposal' : IDL.Func([ProposalId], [Result], []),
  'getAllUsers' : IDL.Func([IDL.Nat, IDL.Nat, UserFilter], [PagedResult_1], []),
  'getAuditLog' : IDL.Func(
      [IDL.Nat, IDL.Nat, AuditFilter],
      [PagedResult],
      ['query'],
    ),
  'getCachedRate' : IDL.Func(
      [TradeToken],
      [IDL.Opt(RateCacheEntry)],
      ['query'],
    ),
  'getComplianceNotes' : IDL.Func(
      [UserId],
      [IDL.Vec(ComplianceNote)],
      ['query'],
    ),
  'getCyclesStatus' : IDL.Func([], [CyclesStatus], ['query']),
  'getDashboardMetrics' : IDL.Func([], [PlatformMetrics__1], ['query']),
  'getDigitalDelivery' : IDL.Func([TradeId], [Result_21], []),
  'getDispute' : IDL.Func([DisputeId], [IDL.Opt(DisputeView)], ['query']),
  'getDisputeJurors' : IDL.Func([DisputeId], [IDL.Opt(JuryView)], ['query']),
  'getDisputesByTrade' : IDL.Func([TradeId], [IDL.Vec(DisputeView)], ['query']),
  'getEndpointErrorRate' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Float64],
      ['query'],
    ),
  'getErrorLog' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Vec(ErrorLogEntry)],
      ['query'],
    ),
  'getExecutionHistory' : IDL.Func([], [IDL.Vec(ProposalView)], ['query']),
  'getExpiredListings' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ListingCard)],
      ['query'],
    ),
  'getFeedbackForTrade' : IDL.Func([TradeId], [IDL.Vec(Feedback)], ['query']),
  'getJurorDashboard' : IDL.Func([], [IDL.Vec(JurorDashboardEntry)], ['query']),
  'getJuryPool' : IDL.Func([], [Result_20], ['query']),
  'getLinkPreview' : IDL.Func([IDL.Text], [Result_19], []),
  'getListing' : IDL.Func([ListingId], [IDL.Opt(ListingCard)], ['query']),
  'getListingsByUser' : IDL.Func(
      [UserId, IDL.Nat, IDL.Nat],
      [IDL.Vec(ListingCard)],
      ['query'],
    ),
  'getMeestPUDOs' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [Result_18],
      [],
    ),
  'getMetricsSummary' : IDL.Func([], [MetricsSummary], ['query']),
  'getModeratorThread' : IDL.Func([TradeId], [IDL.Vec(Message)], ['query']),
  'getModuleMetrics' : IDL.Func([], [IDL.Vec(ModuleMetricsView)], ['query']),
  'getMyDisputes' : IDL.Func([], [IDL.Vec(DisputeView)], ['query']),
  'getMyFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getMyJurorDashboard' : IDL.Func([], [Result_17], ['query']),
  'getMyListings' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ListingCard)],
      ['query'],
    ),
  'getMyPaymentMethods' : IDL.Func([], [IDL.Vec(PaymentMethod)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMyTrades' : IDL.Func(
      [
        IDL.Variant({
          'all' : IDL.Null,
          'seller' : IDL.Null,
          'buyer' : IDL.Null,
        }),
      ],
      [IDL.Vec(TradeView)],
      ['query'],
    ),
  'getMyTransactionHistory' : IDL.Func(
      [TxHistoryFilter, IDL.Nat, IDL.Nat],
      [Page],
      ['query'],
    ),
  'getNovaPoshtaBranches' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [Result_16],
      [],
    ),
  'getNovaPoshtaCityRef' : IDL.Func([IDL.Text], [Result_7], []),
  'getOpenDisputeQueue' : IDL.Func([IDL.Nat, IDL.Nat], [Result_15], ['query']),
  'getP95Latency' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], ['query']),
  'getPaymentMethods' : IDL.Func([], [IDL.Vec(PaymentMethod)], ['query']),
  'getPaymentVerificationStatus' : IDL.Func(
      [TradeId],
      [IDL.Opt(PaymentVerificationResult)],
      ['query'],
    ),
  'getPlatformMetrics' : IDL.Func([], [PlatformMetrics], ['query']),
  'getProposal' : IDL.Func([ProposalId], [IDL.Opt(ProposalView)], ['query']),
  'getProposals' : IDL.Func(
      [IDL.Opt(ProposalStatus)],
      [IDL.Vec(ProposalView)],
      ['query'],
    ),
  'getRequestRate' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], ['query']),
  'getSellerLiability' : IDL.Func([IDL.Principal], [Result_14], ['query']),
  'getShippingOptions' : IDL.Func(
      [IDL.Float64, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(ShippingOption), 'err' : IDL.Text })],
      [],
    ),
  'getSupportedCarriers' : IDL.Func([], [IDL.Vec(CarrierInfo)], ['query']),
  'getSupportedTokens' : IDL.Func([], [IDL.Vec(TokenInfo)], ['query']),
  'getSystemSettings' : IDL.Func(
      [],
      [
        IDL.Record({
          'maxListingPriceUSD' : IDL.Nat,
          'paymentTimeoutHours' : IDL.Nat,
          'allowedTokens' : IDL.Vec(TradeToken),
          'cyclesBalanceThreshold' : IDL.Nat,
          'minTradeAmountUSD' : IDL.Nat,
          'errorRateThreshold' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getTokenInfo' : IDL.Func([TradeToken], [IDL.Opt(TokenInfo)], ['query']),
  'getTrade' : IDL.Func([TradeId], [IDL.Opt(TradeView)], ['query']),
  'getTradeMessages' : IDL.Func(
      [TradeId, IDL.Nat, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getTradeNotifications' : IDL.Func(
      [],
      [IDL.Vec(NotificationEvent)],
      ['query'],
    ),
  'getTradePaymentStatus' : IDL.Func(
      [TradeId],
      [IDL.Opt(TradePaymentStatus)],
      ['query'],
    ),
  'getTradesByListing' : IDL.Func([ListingId], [IDL.Vec(TradeView)], ['query']),
  'getTradesPerDay' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat }))],
      ['query'],
    ),
  'getTreasuryBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getTreasuryWithdrawals' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRecord)],
      ['query'],
    ),
  'getUkrposhtaOffices' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [Result_13],
      [],
    ),
  'getUnifiedTrackingInfo' : IDL.Func([TradeId], [Result_12], []),
  'getUnreadCount' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(TradeId, IDL.Nat))],
      ['query'],
    ),
  'getUserFeedback' : IDL.Func([UserId], [IDL.Vec(Feedback)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserReputationStats' : IDL.Func(
      [UserId],
      [IDL.Opt(ReputationStats)],
      ['query'],
    ),
  'getVaultAddresses' : IDL.Func([], [IDL.Vec(VaultAddressView)], []),
  'getVaultBalance' : IDL.Func([ChainType], [IDL.Opt(BalanceView)], ['query']),
  'incrementListingView' : IDL.Func([ListingId], [], []),
  'initiateOnChainTrade' : IDL.Func(
      [ListingId, TradeToken, IDL.Opt(ShippingSelection)],
      [Result_11],
      [],
    ),
  'initiateTrade' : IDL.Func(
      [ListingId, TradeToken, IDL.Opt(ShippingSelection)],
      [Result_11],
      [],
    ),
  'leaveFeedback' : IDL.Func(
      [TradeId, UserId, IDL.Nat, IDL.Text],
      [Result_10],
      [],
    ),
  'markAllNotificationsRead' : IDL.Func([], [Result], []),
  'markNotificationRead' : IDL.Func([IDL.Nat], [Result], []),
  'markTradeAsRead' : IDL.Func([TradeId], [], []),
  'openDigitalDispute' : IDL.Func([TradeId, IDL.Text], [Result_9], []),
  'openDispute' : IDL.Func([TradeId, DisputeReason, IDL.Text], [Result_9], []),
  'promoteToModerator' : IDL.Func([UserId], [], []),
  'proposeCancelTrade' : IDL.Func([TradeId], [Result_8], []),
  'reactivateListing' : IDL.Func([ListingId], [Result], []),
  'recordRequest' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], ['oneway']),
  'recordTreasuryFee' : IDL.Func([TradeId, IDL.Nat, TradeToken], [], []),
  'refreshRates' : IDL.Func([], [IDL.Nat], []),
  'refreshVaultBalance' : IDL.Func([ChainType], [BalanceView], []),
  'registerAsJuror' : IDL.Func([IDL.Float64], [Result], []),
  'removeListingByAdmin' : IDL.Func([ListingId, IDL.Text], [], []),
  'reopenDispute' : IDL.Func([DisputeId], [Result], []),
  'requestRefund' : IDL.Func([TradeId], [Result], []),
  'resolveDispute' : IDL.Func(
      [DisputeId, ResolutionOutcome, IDL.Text],
      [Result],
      [],
    ),
  'resolveDisputeEscrow' : IDL.Func(
      [DisputeId, ResolutionOutcome],
      [Result],
      [],
    ),
  'retryMeestTTNCreation' : IDL.Func([TradeId], [Result_7], []),
  'retryTTNCreation' : IDL.Func([TradeId], [Result_7], []),
  'retryUkrposhtaTTNCreation' : IDL.Func([TradeId], [Result_7], []),
  'searchListings' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(ListingCategory),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(ItemCondition),
        IDL.Opt(ShippingCarrier),
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Vec(ListingCard)],
      ['query'],
    ),
  'sendMessage' : IDL.Func(
      [TradeId, IDL.Text, IDL.Vec(MediaAttachment)],
      [Result_6],
      [],
    ),
  'setAvalancheApiKey' : IDL.Func([IDL.Text], [], []),
  'setBscScanApiKey' : IDL.Func([IDL.Text], [], []),
  'setDisputeUnderReview' : IDL.Func([DisputeId], [Result], []),
  'setInfuraApiKey' : IDL.Func([IDL.Text], [], []),
  'setMeestApiKey' : IDL.Func([IDL.Text], [], []),
  'setMyProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Result_5],
      [],
    ),
  'setNovaPoshtaApiKey' : IDL.Func([IDL.Text], [], []),
  'setPolygonApiKey' : IDL.Func([IDL.Text], [], []),
  'setSolanaRpcUrl' : IDL.Func([IDL.Text], [], []),
  'setTronGridApiKey' : IDL.Func([IDL.Text], [], []),
  'setUkrPoshtaApiKey' : IDL.Func([IDL.Text], [], []),
  'submitJurorVote' : IDL.Func(
      [DisputeId, JurorVoteChoice, IDL.Text],
      [Result],
      [],
    ),
  'suspendUser' : IDL.Func([UserId, Timestamp, IDL.Text], [], []),
  'trackMeestShipment' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'trackShipment' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'trackUkrPoshtaShipment' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'transformPaymentResponse' : IDL.Func(
      [
        IDL.Record({
          'context' : IDL.Vec(IDL.Nat8),
          'response' : HttpResponse,
        }),
      ],
      [HttpResponse],
      ['query'],
    ),
  'unbanUser' : IDL.Func([UserId], [], []),
  'unregisterJuror' : IDL.Func([], [Result], []),
  'updateListing' : IDL.Func(
      [
        ListingId,
        IDL.Text,
        IDL.Text,
        ListingCategory,
        IDL.Nat,
        TradeToken,
        ItemCondition,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(ShippingMethod),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(PackageDetails),
        IDL.Opt(NovaPoshtaConfig),
        IDL.Opt(UkrposhtaConfig),
        IDL.Opt(MeestConfig),
      ],
      [Result],
      [],
    ),
  'updateSystemSettings' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Vec(TradeToken), IDL.Nat, IDL.Nat, IDL.Float64],
      [],
      [],
    ),
  'verifyEvmAddress' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
  'verifyPayment' : IDL.Func([TradeId, IDL.Text, TradeToken], [Result_2], []),
  'verifySolanaAddress' : IDL.Func([IDL.Text], [Result_1], []),
  'verifyTradePayment' : IDL.Func(
      [TradeId, IDL.Text, IDL.Text],
      [Result_2],
      [],
    ),
  'verifyTronAddress' : IDL.Func([IDL.Text], [Result_1], []),
  'voteOnProposal' : IDL.Func([ProposalId, IDL.Bool], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const DisputeId = IDL.Nat;
  const MediaAttachment = IDL.Record({
    'url' : IDL.Text,
    'mimeType' : IDL.Text,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
  });
  const Error = IDL.Variant({
    'insufficient_funds' : IDL.Null,
    'rate_limited' : IDL.Null,
    'dispute_already_open' : IDL.Null,
    'not_found' : IDL.Null,
    'banned' : IDL.Null,
    'invalid_input' : IDL.Text,
    'escrow_error' : IDL.Text,
    'already_exists' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const TradeToken = IDL.Variant({
    'USDT_ERC20' : IDL.Null,
    'USDT_AVAX' : IDL.Null,
    'USDC_ERC20' : IDL.Null,
    'USDT_BEP20' : IDL.Null,
    'USDC_AVAX' : IDL.Null,
    'ckUSDC' : IDL.Null,
    'ckUSDT' : IDL.Null,
    'USDC_SPL' : IDL.Null,
    'USDT_TRC20' : IDL.Null,
    'USDC_POLYGON' : IDL.Null,
    'USDT_POLYGON' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const AddressVerification = IDL.Record({
    'active' : IDL.Bool,
    'expiresAt' : Timestamp,
    'level' : IDL.Nat,
    'txCount' : IDL.Nat,
    'verifiedAt' : Timestamp,
  });
  const PaymentMethod = IDL.Record({
    'token' : TradeToken,
    'addedAt' : Timestamp,
    'address' : IDL.Text,
    'verification' : IDL.Opt(AddressVerification),
  });
  const Result_25 = IDL.Variant({ 'ok' : PaymentMethod, 'err' : Error });
  const TradeId = IDL.Nat;
  const EscrowAccount = IDL.Record({
    'fee' : IDL.Nat,
    'sellerPrincipal' : UserId,
    'token' : TradeToken,
    'ledgerCanisterId' : IDL.Principal,
    'deadline' : Timestamp,
    'tradeId' : TradeId,
    'lockedAt' : Timestamp,
    'buyerPrincipal' : UserId,
    'amount' : IDL.Nat,
  });
  const TradeStatus = IDL.Variant({
    'payment_verified' : IDL.Null,
    'cancelled' : IDL.Null,
    'disputed' : IDL.Null,
    'pending' : IDL.Null,
    'refunded' : IDL.Null,
    'funded' : IDL.Null,
    'buyer_confirmed' : IDL.Null,
    'complete' : IDL.Null,
    'awaiting_approval' : IDL.Null,
  });
  const ListingId = IDL.Nat;
  const ShippingSelection = IDL.Record({
    'provider' : IDL.Text,
    'branchRef' : IDL.Opt(IDL.Text),
    'cost' : IDL.Nat,
    'deliveryType' : IDL.Text,
    'address' : IDL.Opt(IDL.Text),
  });
  const DigitalDelivery = IDL.Record({
    'inspectionDeadline' : IDL.Opt(Timestamp),
    'password' : IDL.Opt(IDL.Text),
    'fileHash' : IDL.Opt(IDL.Text),
    'revealedAt' : IDL.Opt(Timestamp),
    'fileUrl' : IDL.Text,
  });
  const TTNStatus = IDL.Variant({
    'Failed' : IDL.Null,
    'Success' : IDL.Null,
    'InProgress' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const TradeView = IDL.Record({
    'id' : TradeId,
    'escrowAccount' : IDL.Opt(EscrowAccount),
    'status' : TradeStatus,
    'completedAt' : IDL.Opt(Timestamp),
    'listing' : ListingId,
    'token' : TradeToken,
    'ttnNumber' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'confirmedAt' : IDL.Opt(Timestamp),
    'seller' : UserId,
    'shippingSelection' : IDL.Opt(ShippingSelection),
    'refundDeadline' : IDL.Opt(Timestamp),
    'fundedAt' : IDL.Opt(Timestamp),
    'buyer' : UserId,
    'amount' : IDL.Nat,
    'digitalDelivery' : IDL.Opt(DigitalDelivery),
    'ttnCreationStatus' : TTNStatus,
  });
  const ShippingServiceType = IDL.Variant({
    'express' : IDL.Null,
    'standard' : IDL.Null,
  });
  const JurorVoteChoice = IDL.Variant({
    'sellerWins' : IDL.Null,
    'buyerWins' : IDL.Null,
  });
  const Result_8 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : Error });
  const ProposalId = IDL.Nat;
  const ProposalStatus = IDL.Variant({
    'active' : IDL.Null,
    'expired' : IDL.Null,
    'rejected' : IDL.Null,
    'executed' : IDL.Null,
    'passed' : IDL.Null,
  });
  const Result_24 = IDL.Variant({ 'ok' : ProposalStatus, 'err' : Error });
  const ListingCategory = IDL.Variant({
    'clothing' : IDL.Null,
    'other' : IDL.Null,
    'books' : IDL.Null,
    'digital' : IDL.Null,
    'services' : IDL.Null,
    'electronics' : IDL.Null,
  });
  const ItemCondition = IDL.Variant({
    'new' : IDL.Null,
    'fair' : IDL.Null,
    'good' : IDL.Null,
    'poor' : IDL.Null,
    'likeNew' : IDL.Null,
  });
  const ShippingCarrier = IDL.Variant({
    'meest' : IDL.Null,
    'nova_poshta' : IDL.Null,
    'self_pickup' : IDL.Null,
    'digital' : IDL.Null,
    'ukrposhta' : IDL.Null,
  });
  const ShippingMethod = IDL.Record({
    'type' : ShippingServiceType,
    'estimatedDays' : IDL.Nat,
    'carrier' : ShippingCarrier,
  });
  const PackageDetails = IDL.Record({
    'weight' : IDL.Nat,
    'height' : IDL.Nat,
    'places' : IDL.Nat,
    'length' : IDL.Nat,
    'declaredValue' : IDL.Nat,
    'width' : IDL.Nat,
  });
  const NovaPoshtaConfig = IDL.Record({
    'enabled' : IDL.Bool,
    'senderBranchRef' : IDL.Text,
    'deliveryTypes' : IDL.Vec(IDL.Text),
  });
  const UkrposhtaConfig = IDL.Record({
    'enabled' : IDL.Bool,
    'senderOfficeRef' : IDL.Opt(IDL.Text),
    'deliveryTypes' : IDL.Vec(IDL.Text),
  });
  const MeestConfig = IDL.Record({
    'senderPudoRef' : IDL.Opt(IDL.Text),
    'enabled' : IDL.Bool,
    'deliveryTypes' : IDL.Vec(IDL.Text),
  });
  const TrustLevel = IDL.Variant({
    'new' : IDL.Null,
    'bronze' : IDL.Null,
    'gold' : IDL.Null,
    'silver' : IDL.Null,
  });
  const ListingCard = IDL.Record({
    'id' : ListingId,
    'title' : IDL.Text,
    'sellerPrincipal' : UserId,
    'priceAmount' : IDL.Nat,
    'shippingMethods' : IDL.Vec(ShippingMethod),
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'sellerTrustLevel' : TrustLevel,
    'sellerRating' : IDL.Int,
    'priceToken' : TradeToken,
    'category' : ListingCategory,
    'sellerUsername' : IDL.Text,
    'location' : IDL.Text,
    'photos' : IDL.Vec(IDL.Text),
    'digitalFileUrl' : IDL.Text,
    'condition' : ItemCondition,
  });
  const Result_23 = IDL.Variant({ 'ok' : ListingCard, 'err' : Error });
  const Result_7 = IDL.Variant({ 'ok' : IDL.Text, 'err' : Error });
  const ProposalType = IDL.Variant({
    'TextResolution' : IDL.Record({ 'description' : IDL.Text }),
    'TreasuryTransfer' : IDL.Record({
      'recipient' : IDL.Principal,
      'amount' : IDL.Nat,
    }),
    'ParameterChange' : IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Text }),
  });
  const Result_22 = IDL.Variant({ 'ok' : ProposalId, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'moderator' : IDL.Null,
    'user' : IDL.Null,
  });
  const UserFilter = IDL.Record({
    'roleFilter' : IDL.Opt(UserRole),
    'bannedFilter' : IDL.Opt(IDL.Bool),
  });
  const LiabilityEvent = IDL.Record({
    'tradeId' : IDL.Opt(IDL.Nat),
    'timestamp' : Timestamp,
    'amount' : IDL.Int,
    'reason' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'reputationScore' : IDL.Int,
    'username' : IDL.Text,
    'createdAt' : Timestamp,
    'trustLevel' : TrustLevel,
    'role' : UserRole,
    'liabilityBalance' : IDL.Int,
    'avatarUrl' : IDL.Text,
    'liabilityHistory' : IDL.Vec(LiabilityEvent),
    'isBanned' : IDL.Bool,
    'suspendedUntil' : IDL.Opt(Timestamp),
    'paymentMethods' : IDL.Vec(PaymentMethod),
  });
  const PagedResult_1 = IDL.Record({
    'page' : IDL.Nat,
    'totalCount' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(UserProfile),
  });
  const AuditFilter = IDL.Record({
    'targetFilter' : IDL.Opt(IDL.Text),
    'actionFilter' : IDL.Opt(IDL.Text),
    'actorFilter' : IDL.Opt(IDL.Principal),
  });
  const AuditEntry = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'actorId' : IDL.Principal,
    'timestamp' : Timestamp,
    'details' : IDL.Text,
    'targetId' : IDL.Opt(IDL.Text),
  });
  const PagedResult = IDL.Record({
    'page' : IDL.Nat,
    'totalCount' : IDL.Nat,
    'pageSize' : IDL.Nat,
    'items' : IDL.Vec(AuditEntry),
  });
  const RateCacheEntry = IDL.Record({
    'rateInCents' : IDL.Nat,
    'fetchedAt' : IDL.Int,
  });
  const ComplianceNote = IDL.Record({
    'id' : IDL.Nat,
    'note' : IDL.Text,
    'actorId' : IDL.Principal,
    'timestamp' : Timestamp,
  });
  const CyclesStatus = IDL.Record({
    'isWarning' : IDL.Bool,
    'currentBalance' : IDL.Nat,
    'warningThreshold' : IDL.Nat,
    'estimatedDailyBurn' : IDL.Nat,
  });
  const PlatformMetrics__1 = IDL.Record({
    'totalTrades' : IDL.Nat,
    'activeUsersLast24h' : IDL.Nat,
    'totalVolume' : IDL.Float64,
    'monthlyActiveUsers' : IDL.Nat,
    'completedTrades' : IDL.Nat,
    'avgSettlementTimeMin' : IDL.Float64,
    'disputeRate' : IDL.Float64,
    'swapSuccessRate' : IDL.Float64,
  });
  const Result_21 = IDL.Variant({ 'ok' : DigitalDelivery, 'err' : Error });
  const DisputeStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'opened' : IDL.Null,
    'escalated_to_admin' : IDL.Null,
    'under_review' : IDL.Null,
  });
  const JurorVote = IDL.Record({
    'vote' : JurorVoteChoice,
    'reasoning' : IDL.Text,
    'timestamp' : IDL.Int,
    'jurorPrincipal' : IDL.Principal,
  });
  const JuryView = IDL.Record({
    'jurors' : IDL.Vec(IDL.Principal),
    'votes' : IDL.Vec(JurorVote),
    'deadline' : Timestamp,
  });
  const ResolutionOutcome = IDL.Variant({
    'buyer_wins' : IDL.Null,
    'split' : IDL.Null,
    'seller_wins' : IDL.Null,
  });
  const DisputeResolution = IDL.Record({
    'notes' : IDL.Text,
    'outcome' : ResolutionOutcome,
    'resolvedBy' : UserId,
  });
  const DisputeReason = IDL.Variant({
    'other' : IDL.Null,
    'item_damaged' : IDL.Null,
    'seller_unresponsive' : IDL.Null,
    'item_differs' : IDL.Null,
    'item_not_received' : IDL.Null,
  });
  const DisputeView = IDL.Record({
    'id' : DisputeId,
    'evidenceUrls' : IDL.Vec(IDL.Text),
    'status' : DisputeStatus,
    'trade' : TradeId,
    'evidenceAttachments' : IDL.Vec(MediaAttachment),
    'initiator' : UserId,
    'jury' : IDL.Opt(JuryView),
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'resolution' : IDL.Opt(DisputeResolution),
    'moderatorNotes' : IDL.Vec(IDL.Text),
    'resolvedAt' : IDL.Opt(Timestamp),
    'reason' : DisputeReason,
  });
  const ErrorSeverity = IDL.Variant({
    'warning' : IDL.Null,
    'info' : IDL.Null,
    'error' : IDL.Null,
    'critical' : IDL.Null,
  });
  const ErrorLogEntry = IDL.Record({
    'id' : IDL.Nat,
    'functionName' : IDL.Text,
    'moduleName' : IDL.Text,
    'errorMessage' : IDL.Text,
    'userPrincipal' : IDL.Opt(IDL.Principal),
    'timestamp' : IDL.Int,
    'severity' : ErrorSeverity,
  });
  const ProposalView = IDL.Record({
    'id' : ProposalId,
    'status' : ProposalStatus,
    'noVotes' : IDL.Nat,
    'executedAt' : IDL.Opt(Timestamp),
    'yesVotes' : IDL.Nat,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'deadline' : Timestamp,
    'proposalType' : ProposalType,
    'proposer' : UserId,
    'voterCount' : IDL.Nat,
  });
  const FeedbackId = IDL.Nat;
  const Feedback = IDL.Record({
    'id' : FeedbackId,
    'trade' : TradeId,
    'createdAt' : Timestamp,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
    'reviewed' : UserId,
    'reviewer' : UserId,
  });
  const JurorDashboardEntry = IDL.Record({
    'deadline' : Timestamp,
    'tradeId' : TradeId,
    'sellerVotes' : IDL.Nat,
    'hasVoted' : IDL.Bool,
    'totalJurors' : IDL.Nat,
    'buyerVotes' : IDL.Nat,
    'reason' : DisputeReason,
    'disputeId' : DisputeId,
  });
  const JurorStats = IDL.Record({
    'principal' : IDL.Principal,
    'successRate' : IDL.Float64,
    'activeCount' : IDL.Nat,
    'stakedAmount' : IDL.Float64,
    'registeredAt' : Timestamp,
    'resolvedCount' : IDL.Nat,
  });
  const Result_20 = IDL.Variant({ 'ok' : IDL.Vec(JurorStats), 'err' : Error });
  const LinkPreview = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Opt(IDL.Text),
    'fetchedAt' : Timestamp,
    'description' : IDL.Opt(IDL.Text),
    'siteName' : IDL.Opt(IDL.Text),
    'imageUrl' : IDL.Opt(IDL.Text),
  });
  const Result_19 = IDL.Variant({ 'ok' : LinkPreview, 'err' : Error });
  const Result_18 = IDL.Variant({
    'ok' : IDL.Vec(
      IDL.Record({
        'id' : IDL.Text,
        'name' : IDL.Text,
        'type' : IDL.Text,
        'address' : IDL.Text,
      })
    ),
    'err' : Error,
  });
  const MetricsSummary = IDL.Record({
    'totalTrades' : IDL.Nat,
    'totalVolume' : IDL.Nat,
    'p95LatencyMs' : IDL.Nat,
    'errorRate' : IDL.Float64,
    'memoryUsage' : IDL.Nat,
    'activeTrades' : IDL.Nat,
    'avgTradeValue' : IDL.Nat,
    'disputeRate' : IDL.Float64,
    'totalRevenue' : IDL.Nat,
    'cyclesBalance' : IDL.Nat,
  });
  const MessageId = IDL.Nat;
  const Message = IDL.Record({
    'id' : MessageId,
    'attachmentUrl' : IDL.Opt(IDL.Text),
    'trade' : TradeId,
    'content' : IDL.Text,
    'sender' : UserId,
    'sentAt' : Timestamp,
    'attachments' : IDL.Vec(MediaAttachment),
  });
  const ModuleMetricsView = IDL.Record({
    'memoryUsedBytes' : IDL.Nat,
    'cyclesConsumed' : IDL.Nat,
    'moduleName' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'errorCount' : IDL.Nat,
    'requestCount' : IDL.Nat,
  });
  const Result_17 = IDL.Variant({
    'ok' : IDL.Vec(JurorDashboardEntry),
    'err' : Error,
  });
  const TxHistoryFilter = IDL.Record({
    'to' : IDL.Opt(Timestamp),
    'status' : IDL.Opt(TradeStatus),
    'token' : IDL.Opt(TradeToken),
    'from' : IDL.Opt(Timestamp),
  });
  const Page = IDL.Record({
    'totalCount' : IDL.Nat,
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
    'items' : IDL.Vec(TradeView),
  });
  const NovaPoshtaBranch = IDL.Record({
    'ref' : IDL.Text,
    'cityRef' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'schedule' : IDL.Opt(IDL.Text),
  });
  const Result_16 = IDL.Variant({
    'ok' : IDL.Vec(NovaPoshtaBranch),
    'err' : Error,
  });
  const Result_15 = IDL.Variant({ 'ok' : IDL.Vec(DisputeView), 'err' : Error });
  const PaymentVerificationStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'failed' : IDL.Null,
  });
  const PaymentVerificationResult = IDL.Record({
    'status' : PaymentVerificationStatus,
    'blockNumber' : IDL.Nat,
    'confirmedAmount' : IDL.Float64,
    'confirmedRecipient' : IDL.Text,
    'txHash' : IDL.Text,
    'errorReason' : IDL.Opt(IDL.Text),
  });
  const PlatformMetrics = IDL.Record({
    'totalTrades' : IDL.Nat,
    'activeUsersLast30d' : IDL.Nat,
    'avgTradeCompletionMs' : IDL.Nat,
    'totalListings' : IDL.Nat,
    'tradesByToken' : IDL.Vec(IDL.Tuple(TradeToken, IDL.Nat)),
    'disputeRatePct' : IDL.Nat,
  });
  const Result_14 = IDL.Variant({ 'ok' : IDL.Int, 'err' : Error });
  const ShippingOption = IDL.Record({
    'cost' : IDL.Float64,
    'deliveryDays' : IDL.Nat,
    'available' : IDL.Bool,
    'carrier' : ShippingCarrier,
    'costNat' : IDL.Nat,
  });
  const CarrierInfo = IDL.Record({
    'displayName' : IDL.Text,
    'description' : IDL.Text,
    'carrier' : ShippingCarrier,
  });
  const TokenInfo = IDL.Record({
    'decimals' : IDL.Nat,
    'token' : TradeToken,
    'name' : IDL.Text,
    'network' : IDL.Text,
    'isNative' : IDL.Bool,
    'priority' : IDL.Nat,
    'symbol' : IDL.Text,
  });
  const NotificationEvent = IDL.Record({
    'id' : IDL.Nat,
    'read' : IDL.Bool,
    'tradeId' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'eventType' : IDL.Text,
  });
  const TradePaymentStatus = IDL.Record({
    'status' : TradeStatus,
    'isManual' : IDL.Bool,
    'token' : TradeToken,
    'formattedAmount' : IDL.Text,
    'tradeId' : TradeId,
    'tokenInfo' : IDL.Opt(TokenInfo),
    'amount' : IDL.Nat,
    'verificationResult' : IDL.Opt(PaymentVerificationResult),
  });
  const WithdrawalRecord = IDL.Record({
    'id' : IDL.Nat,
    'executedAt' : Timestamp,
    'recipient' : IDL.Principal,
    'amount' : IDL.Nat,
    'proposalId' : IDL.Nat,
  });
  const Result_13 = IDL.Variant({
    'ok' : IDL.Vec(
      IDL.Record({
        'name' : IDL.Text,
        'address' : IDL.Text,
        'index' : IDL.Text,
      })
    ),
    'err' : Error,
  });
  const Result_12 = IDL.Variant({
    'ok' : IDL.Record({
      'status' : IDL.Text,
      'trackingNumber' : IDL.Text,
      'estimatedDelivery' : IDL.Opt(IDL.Text),
      'statusHistory' : IDL.Vec(
        IDL.Record({ 'status' : IDL.Text, 'timestamp' : IDL.Int })
      ),
      'isDelivered' : IDL.Bool,
      'carrier' : IDL.Text,
    }),
    'err' : Error,
  });
  const ReputationStats = IDL.Record({
    'reputationScore' : IDL.Int,
    'trustLevel' : TrustLevel,
    'averageRating' : IDL.Float64,
    'completedTrades' : IDL.Nat,
    'disputeRate' : IDL.Float64,
  });
  const ChainType = IDL.Variant({
    'SPL' : IDL.Null,
    'BEP20' : IDL.Null,
    'TRC20' : IDL.Null,
    'Polygon' : IDL.Null,
    'ERC20' : IDL.Null,
    'Avalanche' : IDL.Null,
  });
  const VaultAddressView = IDL.Record({
    'chain' : ChainType,
    'network' : IDL.Text,
    'tokenSymbol' : IDL.Text,
    'address' : IDL.Text,
    'derivedAt' : IDL.Int,
  });
  const BalanceView = IDL.Record({
    'chain' : ChainType,
    'error' : IDL.Opt(IDL.Text),
    'usdtBalance' : IDL.Nat,
    'usdcBalance' : IDL.Nat,
    'lastChecked' : IDL.Int,
  });
  const Result_11 = IDL.Variant({ 'ok' : TradeId, 'err' : Error });
  const Result_10 = IDL.Variant({ 'ok' : FeedbackId, 'err' : Error });
  const Result_9 = IDL.Variant({ 'ok' : DisputeId, 'err' : Error });
  const Result_6 = IDL.Variant({ 'ok' : Message, 'err' : Error });
  const Result_5 = IDL.Variant({ 'ok' : UserProfile, 'err' : Error });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpResponse = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const Result_1 = IDL.Variant({
    'ok' : IDL.Record({
      'active' : IDL.Bool,
      'txCount' : IDL.Nat,
      'verifiedAt' : Timestamp,
    }),
    'err' : Error,
  });
  const Result_2 = IDL.Variant({
    'ok' : PaymentVerificationResult,
    'err' : Error,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func([IDL.Text], [], []),
    '_transformResponse' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : IDL.Record({
              'status' : IDL.Nat,
              'body' : IDL.Vec(IDL.Nat8),
              'headers' : IDL.Vec(
                IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
              ),
            }),
          }),
        ],
        [
          IDL.Record({
            'status' : IDL.Nat,
            'body' : IDL.Vec(IDL.Nat8),
            'headers' : IDL.Vec(
              IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })
            ),
          }),
        ],
        ['query'],
      ),
    'addComplianceNote' : IDL.Func([UserId, IDL.Text], [], []),
    'addEvidence' : IDL.Func(
        [DisputeId, IDL.Vec(MediaAttachment)],
        [Result],
        [],
      ),
    'addModeratorNote' : IDL.Func([DisputeId, IDL.Text], [Result], []),
    'addPaymentMethod' : IDL.Func(
        [TradeToken, IDL.Text, IDL.Bool],
        [Result_25],
        [],
      ),
    'adminGetAllTrades' : IDL.Func([], [IDL.Vec(TradeView)], ['query']),
    'adminRemoveListing' : IDL.Func([ListingId, IDL.Text], [Result], []),
    'appealDispute' : IDL.Func([DisputeId, IDL.Text], [Result], []),
    'assignJurors' : IDL.Func([DisputeId], [Result], []),
    'banUser' : IDL.Func([UserId, IDL.Text], [], []),
    'calculateShippingCost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, ShippingServiceType],
        [
          IDL.Variant({
            'ok' : IDL.Record({ 'transitDays' : IDL.Nat, 'costUAH' : IDL.Nat }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'canConfirmDelivery' : IDL.Func([TradeId], [IDL.Bool], []),
    'castJurorVote' : IDL.Func(
        [DisputeId, JurorVoteChoice, IDL.Text],
        [Result],
        [],
      ),
    'checkAndExpireTimeouts' : IDL.Func([], [IDL.Nat], []),
    'checkDigitalInspectionDeadline' : IDL.Func([TradeId], [Result_8], []),
    'checkJuryDeadlines' : IDL.Func([], [IDL.Nat], []),
    'cleanupResolvedListings' : IDL.Func(
        [],
        [
          IDL.Record({
            'deletedCount' : IDL.Nat,
            'skippedByDispute' : IDL.Nat,
            'photosToDelete' : IDL.Vec(IDL.Text),
          }),
        ],
        [],
      ),
    'closeProposal' : IDL.Func([ProposalId], [Result_24], []),
    'confirmPaymentReceived' : IDL.Func([TradeId], [Result], []),
    'confirmPaymentSent' : IDL.Func([TradeId], [Result], []),
    'createListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ListingCategory,
          IDL.Nat,
          TradeToken,
          ItemCondition,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(ShippingMethod),
          IDL.Bool,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(PackageDetails),
          IDL.Opt(NovaPoshtaConfig),
          IDL.Opt(UkrposhtaConfig),
          IDL.Opt(MeestConfig),
        ],
        [Result_23],
        [],
      ),
    'createMeestTTN' : IDL.Func([TradeId], [Result_7], []),
    'createMeestWaybill' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createNovaPoshtaTTN' : IDL.Func([TradeId], [Result_7], []),
    'createProposal' : IDL.Func([ProposalType, IDL.Text], [Result_22], []),
    'createUkrPoshtaWaybill' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'createUkrposhtaTTN' : IDL.Func([TradeId], [Result_7], []),
    'createWaybill' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Nat,
          ShippingServiceType,
        ],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deactivateListing' : IDL.Func([ListingId], [Result], []),
    'debugGetCertifiedData' : IDL.Func(
        [],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'demoteFromModerator' : IDL.Func([UserId], [], []),
    'estimateTokenAmount' : IDL.Func(
        [IDL.Nat, TradeToken],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'executeProposal' : IDL.Func([ProposalId], [Result], []),
    'getAllUsers' : IDL.Func(
        [IDL.Nat, IDL.Nat, UserFilter],
        [PagedResult_1],
        [],
      ),
    'getAuditLog' : IDL.Func(
        [IDL.Nat, IDL.Nat, AuditFilter],
        [PagedResult],
        ['query'],
      ),
    'getCachedRate' : IDL.Func(
        [TradeToken],
        [IDL.Opt(RateCacheEntry)],
        ['query'],
      ),
    'getComplianceNotes' : IDL.Func(
        [UserId],
        [IDL.Vec(ComplianceNote)],
        ['query'],
      ),
    'getCyclesStatus' : IDL.Func([], [CyclesStatus], ['query']),
    'getDashboardMetrics' : IDL.Func([], [PlatformMetrics__1], ['query']),
    'getDigitalDelivery' : IDL.Func([TradeId], [Result_21], []),
    'getDispute' : IDL.Func([DisputeId], [IDL.Opt(DisputeView)], ['query']),
    'getDisputeJurors' : IDL.Func([DisputeId], [IDL.Opt(JuryView)], ['query']),
    'getDisputesByTrade' : IDL.Func(
        [TradeId],
        [IDL.Vec(DisputeView)],
        ['query'],
      ),
    'getEndpointErrorRate' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Float64],
        ['query'],
      ),
    'getErrorLog' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Vec(ErrorLogEntry)],
        ['query'],
      ),
    'getExecutionHistory' : IDL.Func([], [IDL.Vec(ProposalView)], ['query']),
    'getExpiredListings' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ListingCard)],
        ['query'],
      ),
    'getFeedbackForTrade' : IDL.Func([TradeId], [IDL.Vec(Feedback)], ['query']),
    'getJurorDashboard' : IDL.Func(
        [],
        [IDL.Vec(JurorDashboardEntry)],
        ['query'],
      ),
    'getJuryPool' : IDL.Func([], [Result_20], ['query']),
    'getLinkPreview' : IDL.Func([IDL.Text], [Result_19], []),
    'getListing' : IDL.Func([ListingId], [IDL.Opt(ListingCard)], ['query']),
    'getListingsByUser' : IDL.Func(
        [UserId, IDL.Nat, IDL.Nat],
        [IDL.Vec(ListingCard)],
        ['query'],
      ),
    'getMeestPUDOs' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [Result_18],
        [],
      ),
    'getMetricsSummary' : IDL.Func([], [MetricsSummary], ['query']),
    'getModeratorThread' : IDL.Func([TradeId], [IDL.Vec(Message)], ['query']),
    'getModuleMetrics' : IDL.Func([], [IDL.Vec(ModuleMetricsView)], ['query']),
    'getMyDisputes' : IDL.Func([], [IDL.Vec(DisputeView)], ['query']),
    'getMyFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getMyJurorDashboard' : IDL.Func([], [Result_17], ['query']),
    'getMyListings' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ListingCard)],
        ['query'],
      ),
    'getMyPaymentMethods' : IDL.Func([], [IDL.Vec(PaymentMethod)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMyTrades' : IDL.Func(
        [
          IDL.Variant({
            'all' : IDL.Null,
            'seller' : IDL.Null,
            'buyer' : IDL.Null,
          }),
        ],
        [IDL.Vec(TradeView)],
        ['query'],
      ),
    'getMyTransactionHistory' : IDL.Func(
        [TxHistoryFilter, IDL.Nat, IDL.Nat],
        [Page],
        ['query'],
      ),
    'getNovaPoshtaBranches' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [Result_16],
        [],
      ),
    'getNovaPoshtaCityRef' : IDL.Func([IDL.Text], [Result_7], []),
    'getOpenDisputeQueue' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [Result_15],
        ['query'],
      ),
    'getP95Latency' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], ['query']),
    'getPaymentMethods' : IDL.Func([], [IDL.Vec(PaymentMethod)], ['query']),
    'getPaymentVerificationStatus' : IDL.Func(
        [TradeId],
        [IDL.Opt(PaymentVerificationResult)],
        ['query'],
      ),
    'getPlatformMetrics' : IDL.Func([], [PlatformMetrics], ['query']),
    'getProposal' : IDL.Func([ProposalId], [IDL.Opt(ProposalView)], ['query']),
    'getProposals' : IDL.Func(
        [IDL.Opt(ProposalStatus)],
        [IDL.Vec(ProposalView)],
        ['query'],
      ),
    'getRequestRate' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], ['query']),
    'getSellerLiability' : IDL.Func([IDL.Principal], [Result_14], ['query']),
    'getShippingOptions' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(ShippingOption), 'err' : IDL.Text })],
        [],
      ),
    'getSupportedCarriers' : IDL.Func([], [IDL.Vec(CarrierInfo)], ['query']),
    'getSupportedTokens' : IDL.Func([], [IDL.Vec(TokenInfo)], ['query']),
    'getSystemSettings' : IDL.Func(
        [],
        [
          IDL.Record({
            'maxListingPriceUSD' : IDL.Nat,
            'paymentTimeoutHours' : IDL.Nat,
            'allowedTokens' : IDL.Vec(TradeToken),
            'cyclesBalanceThreshold' : IDL.Nat,
            'minTradeAmountUSD' : IDL.Nat,
            'errorRateThreshold' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getTokenInfo' : IDL.Func([TradeToken], [IDL.Opt(TokenInfo)], ['query']),
    'getTrade' : IDL.Func([TradeId], [IDL.Opt(TradeView)], ['query']),
    'getTradeMessages' : IDL.Func(
        [TradeId, IDL.Nat, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getTradeNotifications' : IDL.Func(
        [],
        [IDL.Vec(NotificationEvent)],
        ['query'],
      ),
    'getTradePaymentStatus' : IDL.Func(
        [TradeId],
        [IDL.Opt(TradePaymentStatus)],
        ['query'],
      ),
    'getTradesByListing' : IDL.Func(
        [ListingId],
        [IDL.Vec(TradeView)],
        ['query'],
      ),
    'getTradesPerDay' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat }))],
        ['query'],
      ),
    'getTreasuryBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getTreasuryWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRecord)],
        ['query'],
      ),
    'getUkrposhtaOffices' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [Result_13],
        [],
      ),
    'getUnifiedTrackingInfo' : IDL.Func([TradeId], [Result_12], []),
    'getUnreadCount' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(TradeId, IDL.Nat))],
        ['query'],
      ),
    'getUserFeedback' : IDL.Func([UserId], [IDL.Vec(Feedback)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserReputationStats' : IDL.Func(
        [UserId],
        [IDL.Opt(ReputationStats)],
        ['query'],
      ),
    'getVaultAddresses' : IDL.Func([], [IDL.Vec(VaultAddressView)], []),
    'getVaultBalance' : IDL.Func(
        [ChainType],
        [IDL.Opt(BalanceView)],
        ['query'],
      ),
    'incrementListingView' : IDL.Func([ListingId], [], []),
    'initiateOnChainTrade' : IDL.Func(
        [ListingId, TradeToken, IDL.Opt(ShippingSelection)],
        [Result_11],
        [],
      ),
    'initiateTrade' : IDL.Func(
        [ListingId, TradeToken, IDL.Opt(ShippingSelection)],
        [Result_11],
        [],
      ),
    'leaveFeedback' : IDL.Func(
        [TradeId, UserId, IDL.Nat, IDL.Text],
        [Result_10],
        [],
      ),
    'markAllNotificationsRead' : IDL.Func([], [Result], []),
    'markNotificationRead' : IDL.Func([IDL.Nat], [Result], []),
    'markTradeAsRead' : IDL.Func([TradeId], [], []),
    'openDigitalDispute' : IDL.Func([TradeId, IDL.Text], [Result_9], []),
    'openDispute' : IDL.Func(
        [TradeId, DisputeReason, IDL.Text],
        [Result_9],
        [],
      ),
    'promoteToModerator' : IDL.Func([UserId], [], []),
    'proposeCancelTrade' : IDL.Func([TradeId], [Result_8], []),
    'reactivateListing' : IDL.Func([ListingId], [Result], []),
    'recordRequest' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], ['oneway']),
    'recordTreasuryFee' : IDL.Func([TradeId, IDL.Nat, TradeToken], [], []),
    'refreshRates' : IDL.Func([], [IDL.Nat], []),
    'refreshVaultBalance' : IDL.Func([ChainType], [BalanceView], []),
    'registerAsJuror' : IDL.Func([IDL.Float64], [Result], []),
    'removeListingByAdmin' : IDL.Func([ListingId, IDL.Text], [], []),
    'reopenDispute' : IDL.Func([DisputeId], [Result], []),
    'requestRefund' : IDL.Func([TradeId], [Result], []),
    'resolveDispute' : IDL.Func(
        [DisputeId, ResolutionOutcome, IDL.Text],
        [Result],
        [],
      ),
    'resolveDisputeEscrow' : IDL.Func(
        [DisputeId, ResolutionOutcome],
        [Result],
        [],
      ),
    'retryMeestTTNCreation' : IDL.Func([TradeId], [Result_7], []),
    'retryTTNCreation' : IDL.Func([TradeId], [Result_7], []),
    'retryUkrposhtaTTNCreation' : IDL.Func([TradeId], [Result_7], []),
    'searchListings' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(ListingCategory),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(ItemCondition),
          IDL.Opt(ShippingCarrier),
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Vec(ListingCard)],
        ['query'],
      ),
    'sendMessage' : IDL.Func(
        [TradeId, IDL.Text, IDL.Vec(MediaAttachment)],
        [Result_6],
        [],
      ),
    'setAvalancheApiKey' : IDL.Func([IDL.Text], [], []),
    'setBscScanApiKey' : IDL.Func([IDL.Text], [], []),
    'setDisputeUnderReview' : IDL.Func([DisputeId], [Result], []),
    'setInfuraApiKey' : IDL.Func([IDL.Text], [], []),
    'setMeestApiKey' : IDL.Func([IDL.Text], [], []),
    'setMyProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Result_5],
        [],
      ),
    'setNovaPoshtaApiKey' : IDL.Func([IDL.Text], [], []),
    'setPolygonApiKey' : IDL.Func([IDL.Text], [], []),
    'setSolanaRpcUrl' : IDL.Func([IDL.Text], [], []),
    'setTronGridApiKey' : IDL.Func([IDL.Text], [], []),
    'setUkrPoshtaApiKey' : IDL.Func([IDL.Text], [], []),
    'submitJurorVote' : IDL.Func(
        [DisputeId, JurorVoteChoice, IDL.Text],
        [Result],
        [],
      ),
    'suspendUser' : IDL.Func([UserId, Timestamp, IDL.Text], [], []),
    'trackMeestShipment' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'trackShipment' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'trackUkrPoshtaShipment' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'transformPaymentResponse' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : HttpResponse,
          }),
        ],
        [HttpResponse],
        ['query'],
      ),
    'unbanUser' : IDL.Func([UserId], [], []),
    'unregisterJuror' : IDL.Func([], [Result], []),
    'updateListing' : IDL.Func(
        [
          ListingId,
          IDL.Text,
          IDL.Text,
          ListingCategory,
          IDL.Nat,
          TradeToken,
          ItemCondition,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(ShippingMethod),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(PackageDetails),
          IDL.Opt(NovaPoshtaConfig),
          IDL.Opt(UkrposhtaConfig),
          IDL.Opt(MeestConfig),
        ],
        [Result],
        [],
      ),
    'updateSystemSettings' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Vec(TradeToken), IDL.Nat, IDL.Nat, IDL.Float64],
        [],
        [],
      ),
    'verifyEvmAddress' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'verifyPayment' : IDL.Func([TradeId, IDL.Text, TradeToken], [Result_2], []),
    'verifySolanaAddress' : IDL.Func([IDL.Text], [Result_1], []),
    'verifyTradePayment' : IDL.Func(
        [TradeId, IDL.Text, IDL.Text],
        [Result_2],
        [],
      ),
    'verifyTronAddress' : IDL.Func([IDL.Text], [Result_1], []),
    'voteOnProposal' : IDL.Func([ProposalId, IDL.Bool], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };