/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { type HttpAgentOptions, type ActorConfig, type Agent } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
export type Result_32 = {
    __kind__: "ok";
    ok: ListingCard;
} | {
    __kind__: "err";
    err: Error_;
};
export type Result_2 = {
    __kind__: "ok";
    ok: PaymentVerificationResult;
} | {
    __kind__: "err";
    err: Error_;
};
export type ProposalType = {
    __kind__: "TextResolution";
    TextResolution: {
        description: string;
    };
} | {
    __kind__: "TreasuryTransfer";
    TreasuryTransfer: {
        recipient: Principal;
        amount: bigint;
    };
} | {
    __kind__: "ParameterChange";
    ParameterChange: {
        key: string;
        value: string;
    };
};
export interface ShippingMethodExport {
    type: ShippingServiceType;
    estimatedDays: ExportInt;
    carrier: ShippingCarrier;
}
export interface TradeView {
    id: TradeId;
    escrowAccount?: EscrowAccount;
    status: TradeStatus;
    completedAt: bigint;
    listing: ListingId;
    pendingOnChainSettlement?: PendingOnChainSettlementView;
    token: TradeToken;
    ttnNumber?: string;
    npDeliveredGraceEndsAt: bigint;
    createdAt: bigint;
    confirmedAt: bigint;
    deliveryRecordAt: bigint;
    seller: UserId;
    shippingSelection?: ShippingSelection;
    sellerResponseDeadline: bigint;
    refundDeadline: bigint;
    shippedAt: bigint;
    payoutWalletHeld: boolean;
    fundedAt: bigint;
    shipByDeadline: bigint;
    paymentIntent?: PaymentIntent;
    buyer: UserId;
    npDeliveredAt: bigint;
    amount: bigint;
    payoutWalletSnapshot?: PayoutWalletSnapshot;
    digitalDelivery?: DigitalDeliveryView;
    ttnCreationStatus: TTNStatus;
}
export interface MetricsSummary {
    totalTrades: bigint;
    totalVolume: bigint;
    p95LatencyMs: bigint;
    errorRate: number;
    memoryUsage: bigint;
    activeTrades: bigint;
    avgTradeValue: bigint;
    disputeRate: number;
    totalRevenue: bigint;
    cyclesBalance: bigint;
}
export interface MeestConfig {
    senderPudoRef?: string;
    enabled: boolean;
    deliveryTypes: Array<string>;
}
export interface AccountExportBundle {
    favoriteListingIds: Array<ListingId>;
    principal: UserId;
    messages: Array<AccountMessageExport>;
    listings: Array<ListingCardExport>;
    trades: Array<TradeViewExport>;
    feedback: Array<FeedbackExport>;
    exportedAt: ExportInt;
    hasProfile: boolean;
    savedSearches: Array<SavedSearchExport>;
    profile: UserProfileExport;
}
export interface ShipHttpHeader {
    value: string;
    name: string;
}
export interface ComplianceNote {
    id: bigint;
    note: string;
    actorId: Principal;
    timestamp: Timestamp;
}
export interface ReserveLedgerView {
    pendingPayouts: bigint;
    liquidBalanceE8s: bigint;
    accrualCount: bigint;
}
export interface PayoutWalletSnapshotExport {
    snapshottedAt: ExportInt;
    walletLinkId: ExportInt;
    token: TradeToken;
    chain: WalletChain;
    address: string;
}
export interface PayoutRequestView {
    id: bigint;
    status: PayoutStatus;
    liabilityId: bigint;
    token: TradeToken;
    collusionSignals: Array<CollusionSignal>;
    executedAt: Timestamp;
    beneficiary: Principal;
    unrecoveredLoss: bigint;
    firstApprover?: Principal;
    tradeId: TradeId;
    fraudReview?: FraudReviewRecord;
    secondApprover?: Principal;
    approvedAmount: bigint;
    requestedAt: Timestamp;
}
export interface ListingInquiryMessage {
    id: ListingInquiryMessageId;
    content: string;
    createdAt: bigint;
    sender: UserId;
    inquiryId: ListingInquiryId;
}
export type Result_34 = {
    __kind__: "ok";
    ok: BuyerCancelPenaltySplit;
} | {
    __kind__: "err";
    err: Error_;
};
export type Result_6 = {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: Error_;
};
export interface TokenInfo {
    decimals: bigint;
    token: TradeToken;
    name: string;
    network: string;
    isNative: boolean;
    priority: bigint;
    symbol: string;
}
export interface DisputeView {
    id: DisputeId;
    evidenceUrls: Array<string>;
    status: DisputeStatus;
    l1SlaDeadline: bigint;
    trade: TradeId;
    evidenceAttachments: Array<MediaAttachment>;
    tradeKind: DisputeTradeKind;
    initiator: UserId;
    jury?: JuryView;
    createdAt: bigint;
    description: string;
    resolution?: DisputeResolution;
    l2QueuedAt: bigint;
    level: DisputeLevel;
    l2DecisionDeadline: bigint;
    slaFlags: DisputeSlaFlags;
    l2TriageDeadline: bigint;
    moderatorNotes: Array<string>;
    resolvedAt: bigint;
    reason: DisputeReason;
    evidencePack: DisputeEvidencePack;
}
export type ListingInquiryMessageId = bigint;
export interface CyclesStatus {
    isWarning: boolean;
    currentBalance: bigint;
    warningThreshold: bigint;
    estimatedDailyBurn: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type Result_26 = {
    __kind__: "ok";
    ok: Array<ListingInquiryMessage>;
} | {
    __kind__: "err";
    err: Error_;
};
export type Result_12 = {
    __kind__: "ok";
    ok: WalletLinkChallengeView;
} | {
    __kind__: "err";
    err: Error_;
};
export type ProposalId = bigint;
export interface HttpHeader {
    value: string;
    name: string;
}
export interface StakeBalanceView {
    locked: bigint;
    available: bigint;
}
export interface ErrorLogEntry {
    id: bigint;
    functionName: string;
    moduleName: string;
    errorMessage: string;
    userPrincipal?: Principal;
    timestamp: bigint;
    severity: ErrorSeverity;
}
export type UserId = Principal;
export interface SavedSearch {
    id: SavedSearchId;
    alertsEnabled: boolean;
    owner: UserId;
    paramsJson: string;
    name: string;
    createdAt: bigint;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type Result_10 = {
    __kind__: "ok";
    ok: SavedSearch;
} | {
    __kind__: "err";
    err: Error_;
};
export type MessageId = bigint;
export type Error_ = {
    __kind__: "insufficient_funds";
    insufficient_funds: null;
} | {
    __kind__: "rate_limited";
    rate_limited: null;
} | {
    __kind__: "dispute_already_open";
    dispute_already_open: null;
} | {
    __kind__: "not_found";
    not_found: null;
} | {
    __kind__: "banned";
    banned: null;
} | {
    __kind__: "invalid_input";
    invalid_input: string;
} | {
    __kind__: "escrow_error";
    escrow_error: string;
} | {
    __kind__: "already_exists";
    already_exists: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
};
export type Result_8 = {
    __kind__: "ok";
    ok: ListingInquiryMessage;
} | {
    __kind__: "err";
    err: Error_;
};
export interface PagedResult_1 {
    page: bigint;
    totalCount: bigint;
    pageSize: bigint;
    items: Array<UserProfile>;
}
export interface PendingOnChainSettlementView {
    op: OnChainSettlementOp;
    queuedAt: bigint;
    attempts: bigint;
    lastError?: string;
    targetStatus: TradeStatus;
}
export interface PayoutWalletSnapshot {
    snapshottedAt: bigint;
    walletLinkId: bigint;
    token: TradeToken;
    chain: WalletChain;
    address: string;
}
export interface ShippingOption {
    cost: number;
    deliveryDays: bigint;
    available: boolean;
    carrier: ShippingCarrier;
    costNat: bigint;
}
export interface CategoryAttributeField {
    key: string;
    labelEn: string;
    labelUk: string;
    required: boolean;
    fieldType: Variant_text_number;
}
export interface ProtectionView {
    maxPayoutE8s: bigint;
    tier: InsuranceCopyTier;
    dailyRemainingE8s: bigint;
    insuranceOffered: boolean;
    liquidBalanceE8s: bigint;
    tradeAmountUsdCents: bigint;
}
export interface TradeCapTierCheck {
    sellerVerifiedTierOk: boolean;
    tier: TradeCapTier;
    elevatedStakeRequired: bigint;
    allowed: boolean;
    sellerStakeOk: boolean;
    ckOnlyRequired: boolean;
    blockReason?: string;
    usdCents: bigint;
    gateCRequired: boolean;
}
export type Result_13 = {
    __kind__: "ok";
    ok: DigitalFileAsset;
} | {
    __kind__: "err";
    err: Error_;
};
export type Result_25 = {
    __kind__: "ok";
    ok: Array<{
        id: string;
        name: string;
        type: string;
        address: string;
    }>;
} | {
    __kind__: "err";
    err: Error_;
};
export interface PaymentMethod {
    walletLinkId: bigint;
    token: TradeToken;
    addedAt: bigint;
    address: string;
    verification?: AddressVerification;
}
export interface DisputeSlaFlags {
    l2TriageOverdue: boolean;
    l2DecisionOverdue: boolean;
    l1SlaOverdue: boolean;
}
export interface BalanceView {
    chain: ChainType;
    error?: string;
    usdtBalance: bigint;
    usdcBalance: bigint;
    lastChecked: bigint;
}
export interface AuditFilter {
    targetFilter?: string;
    actionFilter?: string;
    actorFilter?: Principal;
}
export interface AccountMessageExport {
    attachmentUrl?: string;
    content: string;
    messageId: MessageId;
    sender: UserId;
    sentAt: ExportInt;
    tradeId: TradeId;
    attachments: Array<MediaAttachmentExport>;
}
export type Result_11 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: Error_;
};
export type Result_27 = {
    __kind__: "ok";
    ok: LinkPreview;
} | {
    __kind__: "err";
    err: Error_;
};
export interface ReputationStats {
    reputationScore: bigint;
    buyerScore: bigint;
    trustLevel: TrustLevel;
    averageRating: number;
    completedTrades: bigint;
    disputeRate: number;
    sellerScore: bigint;
}
export type ListingId = bigint;
export interface LinkPreview {
    url: string;
    title?: string;
    fetchedAt: bigint;
    description?: string;
    siteName?: string;
    imageUrl?: string;
}
export interface JuryView {
    jurors: Array<Principal>;
    votes: Array<JurorVote>;
    deadline: bigint;
}
export interface LiabilityEvent {
    liabilityId: bigint;
    tradeId: bigint;
    timestamp: bigint;
    amount: bigint;
    reason: string;
}
export type FeedbackId = bigint;
export interface FraudReviewRecord {
    decision: string;
    reviewedAt: Timestamp;
    slaDueAt: Timestamp;
    rationale: string;
    reviewer: Principal;
    evidenceHash: string;
}
export type Result_21 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: Error_;
};
export interface PendingOnChainSettlementExport {
    op: OnChainSettlementOpExport;
    queuedAt: ExportInt;
    attempts: ExportInt;
    lastError?: string;
    targetStatus: TradeStatus;
}
export interface ModuleMetricsView {
    memoryUsedBytes: bigint;
    cyclesConsumed: bigint;
    moduleName: string;
    lastUpdated: bigint;
    errorCount: bigint;
    requestCount: bigint;
}
export type Result_36 = {
    __kind__: "ok";
    ok: Array<LiabilityRecordView>;
} | {
    __kind__: "err";
    err: Error_;
};
export interface SavedSearchExport {
    id: SavedSearchId;
    alertsEnabled: boolean;
    owner: UserId;
    paramsJson: string;
    name: string;
    createdAt: ExportInt;
}
export interface MediaAttachmentExport {
    url: string;
    mimeType: string;
    fileName: string;
    fileSize: ExportInt;
}
export interface MediaAttachment {
    url: string;
    mimeType: string;
    fileName: string;
    fileSize: bigint;
}
export type Result_18 = {
    __kind__: "ok";
    ok: TradeId;
} | {
    __kind__: "err";
    err: Error_;
};
export interface DigitalFileAsset {
    contentHash?: string;
    mimeType: string;
    blobHash: string;
    blobUrlEncrypted: string;
    fileVersionId: bigint;
    sizeBytes: bigint;
    registeredAt: bigint;
    dekEncrypted: string;
}
export interface PaymentIntentExport {
    token: TradeToken;
    createdAt: ExportInt;
    path: PaymentSettlementPath;
    recipient: string;
    network: string;
    expiry: ExportInt;
    exactAmount: ExportInt;
}
export interface HttpResponse {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export type Result_23 = {
    __kind__: "ok";
    ok: Array<NovaPoshtaBranch>;
} | {
    __kind__: "err";
    err: Error_;
};
export type Result_15 = {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: Error_;
};
export interface NovaPoshtaConfig {
    enabled: boolean;
    senderBranchRef: string;
    deliveryTypes: Array<string>;
}
export type CategoryId = bigint;
export interface DisputeResolution {
    notes: string;
    outcome: ResolutionOutcome;
    resolvedBy: UserId;
}
export interface CarrierInfo {
    displayName: string;
    description: string;
    carrier: ShippingCarrier;
}
export interface VaultAddressView {
    chain: ChainType;
    network: string;
    tokenSymbol: string;
    address: string;
    derivedAt: bigint;
}
export interface UserProfileExport {
    id: UserId;
    bio: string;
    reputationScore: bigint;
    linkedWallets: Array<LinkedExternalWalletExport>;
    buyerScore: bigint;
    username: string;
    createdAt: ExportInt;
    trustLevel: TrustLevel;
    role: UserRole;
    liabilityBalance: bigint;
    avatarUrl: string;
    liabilityHistory: Array<LiabilityEventExport>;
    isBanned: boolean;
    accountClosedAt: ExportInt;
    suspendedUntil: ExportInt;
    sellerScore: bigint;
    paymentMethods: Array<PaymentMethodExport>;
    kycTier: KycTier;
}
export interface ListingCard {
    id: ListingId;
    categoryId: CategoryId;
    status: ListingStatus;
    title: string;
    sellerPrincipal: UserId;
    priceAmount: bigint;
    categorySlug: string;
    shippingMethods: Array<ShippingMethod>;
    createdAt: bigint;
    description: string;
    sellerTrustLevel: TrustLevel;
    isPromoted: boolean;
    sellerRating: bigint;
    attributes: Array<CategoryAttributeValue>;
    priceToken: TradeToken;
    category: ListingCategory;
    sellerUsername: string;
    location: string;
    photos: Array<string>;
    digitalFileUrl: string;
    condition: ItemCondition;
}
export interface LiabilityRecordView {
    id: bigint;
    status: LiabilityStatus;
    originalAmount: bigint;
    initiator: Principal;
    userId: UserId;
    createdAt: bigint;
    updatedAt: bigint;
    tradeId?: TradeId;
    remainingBalance: bigint;
    currency: TradeToken;
    auditTrail: Array<LiabilityAuditEntry>;
    reason: LiabilityReason;
}
export interface Feedback {
    id: FeedbackId;
    trade: TradeId;
    createdAt: bigint;
    comment: string;
    rating: bigint;
    reviewed: UserId;
    reviewer: UserId;
}
export type Result_5 = {
    __kind__: "ok";
    ok: PayoutWalletSnapshot;
} | {
    __kind__: "err";
    err: Error_;
};
export interface TxHistoryFilter {
    to?: Timestamp;
    status?: TradeStatus;
    token?: TradeToken;
    from?: Timestamp;
}
export interface PackageDetails {
    weight: bigint;
    height: bigint;
    places: bigint;
    length: bigint;
    declaredValue: bigint;
    width: bigint;
}
export interface SellerFaultSettlementView {
    liabilityId?: bigint;
    buyerObligationCents: bigint;
    residualCents: bigint;
    path: SettlementPath;
    insurancePayoutId?: bigint;
    stakeSeizedCents: bigint;
    tradeId: TradeId;
    onChainRefundExpected: boolean;
    copyTier: SettlementCopyTier;
}
export interface NovaPoshtaBranch {
    ref: string;
    cityRef: string;
    name: string;
    address: string;
    schedule?: string;
}
export interface NotificationEvent {
    id: bigint;
    read: boolean;
    tradeId: bigint;
    message: string;
    timestamp: bigint;
    eventType: string;
}
export type OnChainSettlementOp = {
    __kind__: "buyerCancelSplit";
    buyerCancelSplit: BuyerCancelPenaltySplit;
} | {
    __kind__: "releaseToSeller";
    releaseToSeller: null;
} | {
    __kind__: "refundBuyer";
    refundBuyer: {
        memo: string;
    };
} | {
    __kind__: "disputeBuyerWins";
    disputeBuyerWins: null;
} | {
    __kind__: "disputeSplit";
    disputeSplit: {
        sellerHasNegativeRep: boolean;
    };
} | {
    __kind__: "disputeSellerWins";
    disputeSellerWins: {
        sellerHasNegativeRep: boolean;
    };
};
export type ExportInt = bigint;
export type SavedSearchId = bigint;
export interface Page {
    totalCount: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<TradeView>;
}
export interface EscrowAccount {
    fee: bigint;
    sellerPrincipal: UserId;
    token: TradeToken;
    ledgerCanisterId: Principal;
    deadline: bigint;
    tradeId: TradeId;
    lockedAt: bigint;
    buyerPrincipal: UserId;
    amount: bigint;
}
export type Result_31 = {
    __kind__: "ok";
    ok: PaymentIntent;
} | {
    __kind__: "err";
    err: Error_;
};
export interface PlatformMetrics {
    totalTrades: bigint;
    activeUsersLast30d: bigint;
    avgTradeCompletionMs: bigint;
    totalListings: bigint;
    tradesByToken: Array<[TradeToken, bigint]>;
    disputeRatePct: bigint;
}
export interface TradeFeeQuote {
    usesDefaultFeeBps: boolean;
    token: TradeToken;
    totalBuyerAmount: bigint;
    platformFeeAmount: bigint;
    platformFeeBps: bigint;
    itemPrice: bigint;
}
export type Result_7 = {
    __kind__: "ok";
    ok: Message;
} | {
    __kind__: "err";
    err: Error_;
};
export interface AddressVerification {
    active: boolean;
    expiresAt: bigint;
    level: bigint;
    txCount: bigint;
    verifiedAt: bigint;
}
export interface PlatformMetrics__1 {
    totalTrades: bigint;
    activeUsersLast24h: bigint;
    totalVolume: number;
    monthlyActiveUsers: bigint;
    completedTrades: bigint;
    avgSettlementTimeMin: number;
    disputeRate: number;
    swapSuccessRate: number;
}
export interface BuyerCancelPenaltySplit {
    buyerRefund: bigint;
    platformFee: bigint;
    sellerCompensation: bigint;
    lockedAmount: bigint;
}
export interface ListingCardExport {
    id: ListingId;
    categoryId: CategoryId;
    title: string;
    sellerPrincipal: UserId;
    priceAmount: ExportInt;
    categorySlug: string;
    shippingMethods: Array<ShippingMethodExport>;
    createdAt: ExportInt;
    description: string;
    sellerTrustLevel: TrustLevel;
    isPromoted: boolean;
    listingStatus: ListingStatus;
    sellerRating: bigint;
    attributes: Array<CategoryAttributeValue>;
    priceToken: TradeToken;
    category: ListingCategory;
    sellerUsername: string;
    location: string;
    photos: Array<string>;
    digitalFileUrl: string;
    condition: ItemCondition;
}
export type Result_28 = {
    __kind__: "ok";
    ok: Array<JurorStats>;
} | {
    __kind__: "err";
    err: Error_;
};
export interface LinkedExternalWalletExport {
    id: ExportInt;
    linkedAt: ExportInt;
    chain: WalletChain;
    messageHash: string;
    address: string;
    sessionId: string;
    purpose: WalletLinkPurpose;
}
export interface WalletLinkChallengeView {
    expiresAt: bigint;
    chain: WalletChain;
    challengeId: bigint;
    message: string;
    address: string;
    sessionId: string;
    purpose: WalletLinkPurpose;
}
export interface UserFilter {
    roleFilter?: UserRole;
    bannedFilter?: boolean;
}
export interface ShippingMethod {
    type: ShippingServiceType;
    estimatedDays: bigint;
    carrier: ShippingCarrier;
}
export interface DigitalDeliveryViewExport {
    inspectionDeadline: ExportInt;
    password?: string;
    deliveryRecordAt: ExportInt;
    mimeType?: string;
    fileHash?: string;
    dekHex?: string;
    fileVersionId: ExportInt;
    revealedAt: ExportInt;
    fileUrl: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type TradeId = bigint;
export type ListingInquiryId = bigint;
export interface LinkedExternalWallet {
    id: bigint;
    linkedAt: bigint;
    chain: WalletChain;
    messageHash: string;
    address: string;
    sessionId: string;
    purpose: WalletLinkPurpose;
}
export interface TradePaymentStatus {
    status: TradeStatus;
    isManual: boolean;
    token: TradeToken;
    formattedAmount: string;
    tradeId: TradeId;
    tokenInfo?: TokenInfo;
    amount: bigint;
    verificationResult?: PaymentVerificationResult;
}
export type Result_9 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: Error_;
};
export interface PaymentMethodExport {
    walletLinkId: ExportInt;
    token: TradeToken;
    addedAt: ExportInt;
    address: string;
    verification?: AddressVerificationExport;
}
export interface JurorVote {
    vote: JurorVoteChoice;
    reasoning: string;
    timestamp: bigint;
    jurorPrincipal: Principal;
}
export type Result_30 = {
    __kind__: "ok";
    ok: ProposalId;
} | {
    __kind__: "err";
    err: Error_;
};
export interface ShippingSelectionExport {
    provider: string;
    branchRef?: string;
    cost: ExportInt;
    deliveryType: string;
    address?: string;
}
export interface AuditEntry {
    id: bigint;
    action: string;
    actorId: Principal;
    timestamp: Timestamp;
    details: string;
    targetId?: string;
}
export interface UserProfile {
    id: UserId;
    bio: string;
    reputationScore: bigint;
    linkedWallets: Array<LinkedExternalWallet>;
    buyerScore: bigint;
    username: string;
    createdAt: bigint;
    trustLevel: TrustLevel;
    role: UserRole;
    liabilityBalance: bigint;
    avatarUrl: string;
    liabilityHistory: Array<LiabilityEvent>;
    isBanned: boolean;
    accountClosedAt: bigint;
    suspendedUntil: bigint;
    sellerScore: bigint;
    paymentMethods: Array<PaymentMethod>;
    kycTier: KycTier;
}
export interface PaymentVerificationResult {
    status: PaymentVerificationStatus;
    blockNumber: bigint;
    confirmedAmount: number;
    confirmedRecipient: string;
    txHash: string;
    errorReason?: string;
}
export interface BuyerCancelPenaltySplitExport {
    buyerRefund: ExportInt;
    platformFee: ExportInt;
    sellerCompensation: ExportInt;
    lockedAmount: ExportInt;
}
export type Timestamp = bigint;
export interface ShipHttpResponse {
    status: bigint;
    body: Uint8Array;
    headers: Array<ShipHttpHeader>;
}
export type Result_37 = {
    __kind__: "ok";
    ok: PaymentMethod;
} | {
    __kind__: "err";
    err: Error_;
};
export type Result_17 = {
    __kind__: "ok";
    ok: FeedbackId;
} | {
    __kind__: "err";
    err: Error_;
};
export interface PagedResult {
    page: bigint;
    totalCount: bigint;
    pageSize: bigint;
    items: Array<AuditEntry>;
}
export interface CategoryNode {
    id: CategoryId;
    labelEn: string;
    labelUk: string;
    slug: string;
    legacyCategory: ListingCategory;
    parentId?: CategoryId;
}
export interface FeedbackExport {
    id: FeedbackId;
    trade: TradeId;
    createdAt: ExportInt;
    comment: string;
    rating: ExportInt;
    reviewed: UserId;
    reviewer: UserId;
}
export type Result_16 = {
    __kind__: "ok";
    ok: DisputeId;
} | {
    __kind__: "err";
    err: Error_;
};
export type Result_1 = {
    __kind__: "ok";
    ok: {
        active: boolean;
        txCount: bigint;
        verifiedAt: Timestamp;
    };
} | {
    __kind__: "err";
    err: Error_;
};
export interface EscrowAccountExport {
    fee: ExportInt;
    sellerPrincipal: UserId;
    token: TradeToken;
    ledgerCanisterId: Principal;
    deadline: ExportInt;
    tradeId: TradeId;
    lockedAt: ExportInt;
    buyerPrincipal: UserId;
    amount: ExportInt;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Result_22 = {
    __kind__: "ok";
    ok: Array<DisputeView>;
} | {
    __kind__: "err";
    err: Error_;
};
export type OnChainSettlementOpExport = {
    __kind__: "buyerCancelSplit";
    buyerCancelSplit: BuyerCancelPenaltySplitExport;
} | {
    __kind__: "releaseToSeller";
    releaseToSeller: null;
} | {
    __kind__: "refundBuyer";
    refundBuyer: {
        memo: string;
    };
} | {
    __kind__: "disputeBuyerWins";
    disputeBuyerWins: null;
} | {
    __kind__: "disputeSplit";
    disputeSplit: {
        sellerHasNegativeRep: boolean;
    };
} | {
    __kind__: "disputeSellerWins";
    disputeSellerWins: {
        sellerHasNegativeRep: boolean;
    };
};
export interface LiabilityEventExport {
    liabilityId: ExportInt;
    tradeId: ExportInt;
    timestamp: ExportInt;
    amount: bigint;
    reason: string;
}
export interface JurorDashboardEntry {
    deadline: bigint;
    tradeId: TradeId;
    sellerVotes: bigint;
    hasVoted: boolean;
    totalJurors: bigint;
    buyerVotes: bigint;
    reason: DisputeReason;
    disputeId: DisputeId;
}
export type Result_19 = {
    __kind__: "ok";
    ok: {
        status: string;
        trackingNumber: string;
        estimatedDelivery?: string;
        statusHistory: Array<{
            status: string;
            timestamp: bigint;
        }>;
        isDelivered: boolean;
        carrier: string;
    };
} | {
    __kind__: "err";
    err: Error_;
};
export type Result_29 = {
    __kind__: "ok";
    ok: DigitalDeliveryView;
} | {
    __kind__: "err";
    err: Error_;
};
export interface GateCChecklistView {
    securitySignOffRef: string;
    rollbackTestsPassed: boolean;
    subaccountDesignReviewed: boolean;
    checklistComplete: boolean;
    trustlessEscrowEnabled: boolean;
    testnetE2ePassed: boolean;
    betaCapsConfigured: boolean;
    ckBetaCapUsdCents: bigint;
}
export type Result_24 = {
    __kind__: "ok";
    ok: Array<JurorDashboardEntry>;
} | {
    __kind__: "err";
    err: Error_;
};
export type Result_14 = {
    __kind__: "ok";
    ok: LinkedExternalWallet;
} | {
    __kind__: "err";
    err: Error_;
};
export interface PaymentIntent {
    token: TradeToken;
    createdAt: bigint;
    path: PaymentSettlementPath;
    recipient: string;
    network: string;
    expiry: bigint;
    exactAmount: bigint;
}
export interface ListingStakeView {
    status: ListingStakeStatus;
    token: TradeToken;
    listingId: ListingId;
    seller: UserId;
    lockedAt: bigint;
    amount: bigint;
}
export interface AddressVerificationExport {
    active: boolean;
    expiresAt: ExportInt;
    level: ExportInt;
    txCount: ExportInt;
    verifiedAt: ExportInt;
}
export interface ProposalView {
    id: ProposalId;
    status: ProposalStatus;
    noVotes: bigint;
    executedAt?: Timestamp;
    yesVotes: bigint;
    createdAt: Timestamp;
    description: string;
    deadline: Timestamp;
    proposalType: ProposalType;
    proposer: UserId;
    voterCount: bigint;
}
export interface DisputeEvidencePack {
    chatThreadLink?: string;
    packagePhotoUrls: Array<string>;
    fileHash?: string;
    downloadTimestamp: bigint;
    ttnScreenshotUrl?: string;
}
export type Result_33 = {
    __kind__: "ok";
    ok: ProposalStatus;
} | {
    __kind__: "err";
    err: Error_;
};
export interface WithdrawalRecord {
    id: bigint;
    executedAt: Timestamp;
    recipient: Principal;
    amount: bigint;
    proposalId: bigint;
}
export interface UkrposhtaConfig {
    enabled: boolean;
    senderOfficeRef?: string;
    deliveryTypes: Array<string>;
}
export interface JurorStats {
    principal: Principal;
    successRate: number;
    activeCount: bigint;
    stakedAmount: number;
    registeredAt: bigint;
    resolvedCount: bigint;
}
export type DisputeId = bigint;
export interface ShippingSelection {
    provider: string;
    branchRef?: string;
    cost: bigint;
    deliveryType: string;
    address?: string;
}
export interface DigitalDeliveryView {
    inspectionDeadline: bigint;
    password?: string;
    deliveryRecordAt: bigint;
    mimeType?: string;
    fileHash?: string;
    dekHex?: string;
    fileVersionId: bigint;
    revealedAt: bigint;
    fileUrl: string;
}
export interface CategoryAttributeValue {
    key: string;
    value: string;
}
export interface RateCacheEntry {
    rateInCents: bigint;
    fetchedAt: bigint;
}
export type Result_35 = {
    __kind__: "ok";
    ok: PayoutRequestView;
} | {
    __kind__: "err";
    err: Error_;
};
export interface LiabilityAuditEntry {
    action: LiabilityAuditAction;
    note: string;
    performedBy: Principal;
    timestamp: bigint;
    amount: bigint;
}
export interface Message {
    id: MessageId;
    attachmentUrl?: string;
    trade: TradeId;
    content: string;
    sender: UserId;
    sentAt: bigint;
    attachments: Array<MediaAttachment>;
}
export interface TradeViewExport {
    id: TradeId;
    escrowAccount?: EscrowAccountExport;
    completedAt: ExportInt;
    listing: ListingId;
    pendingOnChainSettlement?: PendingOnChainSettlementExport;
    token: TradeToken;
    ttnNumber?: string;
    npDeliveredGraceEndsAt: ExportInt;
    createdAt: ExportInt;
    confirmedAt: ExportInt;
    deliveryRecordAt: ExportInt;
    seller: UserId;
    shippingSelection?: ShippingSelectionExport;
    sellerResponseDeadline: ExportInt;
    refundDeadline: ExportInt;
    shippedAt: ExportInt;
    payoutWalletHeld: boolean;
    fundedAt: ExportInt;
    shipByDeadline: ExportInt;
    paymentIntent?: PaymentIntentExport;
    buyer: UserId;
    npDeliveredAt: ExportInt;
    amount: ExportInt;
    payoutWalletSnapshot?: PayoutWalletSnapshotExport;
    digitalDelivery?: DigitalDeliveryViewExport;
    tradeStatus: TradeStatus;
    ttnCreationStatus: TTNStatus;
}
export type Result_20 = {
    __kind__: "ok";
    ok: Array<{
        name: string;
        address: string;
        index: string;
    }>;
} | {
    __kind__: "err";
    err: Error_;
};
export interface VaultHttpResponse {
    status: bigint;
    body: Uint8Array;
    headers: Array<{
        value: string;
        name: string;
    }>;
}
export enum ChainType {
    SPL = "SPL",
    BEP20 = "BEP20",
    TRC20 = "TRC20",
    Polygon = "Polygon",
    ERC20 = "ERC20",
    Avalanche = "Avalanche"
}
export enum CollusionSignal {
    rapid_account_cycling = "rapid_account_cycling",
    reciprocal_trades = "reciprocal_trades",
    shared_wallet = "shared_wallet",
    repeated_claims = "repeated_claims"
}
export enum DisputeLevel {
    l1 = "l1",
    l2 = "l2"
}
export enum DisputeReason {
    other = "other",
    item_damaged = "item_damaged",
    seller_unresponsive = "seller_unresponsive",
    item_differs = "item_differs",
    item_not_received = "item_not_received"
}
export enum DisputeStatus {
    resolved = "resolved",
    opened = "opened",
    escalated_to_admin = "escalated_to_admin",
    l2_queued = "l2_queued",
    under_review = "under_review",
    draft = "draft"
}
export enum DisputeTradeKind {
    physical = "physical",
    digital = "digital"
}
export enum ErrorSeverity {
    warning = "warning",
    info = "info",
    error = "error",
    critical = "critical"
}
export enum InsuranceCopyTier {
    stake_only = "stake_only",
    capped_reserve = "capped_reserve",
    no_guarantee = "no_guarantee"
}
export enum ItemCondition {
    new_ = "new",
    fair = "fair",
    good = "good",
    poor = "poor",
    likeNew = "likeNew"
}
export enum JurorVoteChoice {
    sellerWins = "sellerWins",
    buyerWins = "buyerWins"
}
export enum KycTier {
    verified = "verified",
    none = "none"
}
export enum LiabilityAuditAction {
    created = "created",
    stake_applied = "stake_applied",
    partial_clear = "partial_clear",
    full_clear = "full_clear"
}
export enum LiabilityReason {
    admin_adjustment = "admin_adjustment",
    cancellation_fee = "cancellation_fee",
    stake_seizure_residual = "stake_seizure_residual",
    seller_fault = "seller_fault",
    dispute_lost = "dispute_lost",
    buyer_cancel_compensation = "buyer_cancel_compensation"
}
export enum LiabilityStatus {
    open = "open",
    cleared = "cleared",
    partial = "partial"
}
export enum ListingCategory {
    clothing = "clothing",
    other = "other",
    books = "books",
    digital = "digital",
    services = "services",
    electronics = "electronics"
}
export enum ListingStakeStatus {
    locked = "locked",
    seized = "seized",
    released = "released"
}
export enum ListingStatus {
    active = "active",
    sold = "sold",
    inactive = "inactive",
    draft = "draft",
    removed = "removed"
}
export enum PaymentSettlementPath {
    ck = "ck",
    manual = "manual"
}
export enum PaymentVerificationStatus {
    verified = "verified",
    pending = "pending",
    failed = "failed"
}
export enum PayoutStatus {
    pending_first_approval = "pending_first_approval",
    held_fraud_review = "held_fraud_review",
    denied = "denied",
    pending_second_approval = "pending_second_approval",
    approved = "approved",
    executed = "executed"
}
export enum ProposalStatus {
    active = "active",
    expired = "expired",
    rejected = "rejected",
    executed = "executed",
    passed = "passed"
}
export enum ResolutionOutcome {
    buyer_wins = "buyer_wins",
    split = "split",
    seller_wins = "seller_wins"
}
export enum SettlementCopyTier {
    on_chain_recovery = "on_chain_recovery",
    partial_recovery = "partial_recovery",
    manual_restriction_only = "manual_restriction_only"
}
export enum SettlementPath {
    on_chain_ck = "on_chain_ck",
    manual = "manual"
}
export enum ShippingCarrier {
    meest = "meest",
    nova_poshta = "nova_poshta",
    self_pickup = "self_pickup",
    digital = "digital",
    ukrposhta = "ukrposhta"
}
export enum ShippingServiceType {
    express = "express",
    standard = "standard"
}
export enum TTNStatus {
    Failed = "Failed",
    Success = "Success",
    InProgress = "InProgress",
    Pending = "Pending"
}
export enum TradeCapTier {
    high_value_ck = "high_value_ck",
    rejected = "rejected",
    elevated = "elevated",
    standard = "standard"
}
export enum TradeStatus {
    shipped = "shipped",
    payment_intent = "payment_intent",
    payment_verified = "payment_verified",
    fulfillment_pending = "fulfillment_pending",
    cancelled = "cancelled",
    disputed = "disputed",
    pending = "pending",
    refunded = "refunded",
    dispute_l1 = "dispute_l1",
    dispute_l2 = "dispute_l2",
    payment_intent_expired = "payment_intent_expired",
    funded = "funded",
    buyer_confirmed = "buyer_confirmed",
    complete = "complete",
    digital_delivered = "digital_delivered",
    awaiting_receipt = "awaiting_receipt",
    awaiting_approval = "awaiting_approval",
    manual_payment_pending = "manual_payment_pending",
    cancelled_buyer_pre_ship = "cancelled_buyer_pre_ship",
    awaiting_seller_handshake = "awaiting_seller_handshake",
    cancelled_no_seller_response = "cancelled_no_seller_response"
}
export enum TradeToken {
    USDT_ERC20 = "USDT_ERC20",
    USDT_AVAX = "USDT_AVAX",
    USDC_ERC20 = "USDC_ERC20",
    USDT_BEP20 = "USDT_BEP20",
    USDC_AVAX = "USDC_AVAX",
    ckUSDC = "ckUSDC",
    ckUSDT = "ckUSDT",
    USDC_SPL = "USDC_SPL",
    USDT_TRC20 = "USDT_TRC20",
    USDC_POLYGON = "USDC_POLYGON",
    USDT_POLYGON = "USDT_POLYGON"
}
export enum TrustLevel {
    new_ = "new",
    bronze = "bronze",
    gold = "gold",
    silver = "silver"
}
export enum UserRole {
    admin = "admin",
    moderator = "moderator",
    user = "user"
}
export enum Variant_all_seller_buyer {
    all = "all",
    seller = "seller",
    buyer = "buyer"
}
export enum Variant_text_number {
    text = "text",
    number_ = "number"
}
export enum WalletChain {
    tron = "tron",
    evm_bsc = "evm_bsc",
    evm_eth = "evm_eth"
}
export enum WalletLinkPurpose {
    stake = "stake",
    payment = "payment",
    payout = "payout"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _transformResponse(args: {
        context: Uint8Array;
        response: {
            status: bigint;
            body: Uint8Array;
            headers: Array<{
                value: string;
                name: string;
            }>;
        };
    }): Promise<{
        status: bigint;
        body: Uint8Array;
        headers: Array<{
            value: string;
            name: string;
        }>;
    }>;
    addComplianceNote(target: UserId, note: string): Promise<void>;
    addEvidence(disputeId: DisputeId, evidenceAttachments: Array<MediaAttachment>): Promise<Result>;
    addFavorite(listingId: ListingId): Promise<Result>;
    addModeratorNote(disputeId: DisputeId, note: string): Promise<Result>;
    addPaymentMethod(token: TradeToken, address: string, autoVerify: boolean): Promise<Result_37>;
    adminApproveInsurancePayout(payoutId: bigint): Promise<Result_35>;
    adminClearUserLiability(target: UserId, note: string): Promise<Result>;
    adminGetAllTrades(): Promise<Array<TradeView>>;
    adminGetGateCChecklist(): Promise<GateCChecklistView>;
    adminListLiabilities(offset: bigint, limit: bigint): Promise<Result_36>;
    adminPartialClearLiability(liabilityId: bigint, clearAmountCents: bigint, note: string): Promise<Result>;
    adminPromoteListing(id: ListingId): Promise<Result>;
    adminRemoveListing(id: ListingId, reason: string): Promise<Result>;
    adminRequestInsurancePayout(tradeId: TradeId, beneficiary: Principal, liabilityId: bigint, unrecoveredLossE8s: bigint, token: TradeToken): Promise<Result_35>;
    adminResolveInsuranceFraudReview(payoutId: bigint, approve: boolean, rationale: string, evidenceHash: string): Promise<Result_35>;
    adminSetTrustlessEscrowEnabled(enabled: boolean, securitySignOffRef: string): Promise<Result>;
    adminSetUserKycTier(target: UserId, tier: KycTier): Promise<Result>;
    adminUpdateGateCChecklist(testnetE2ePassed: boolean | null, rollbackTestsPassed: boolean | null, subaccountDesignReviewed: boolean | null, betaCapsConfigured: boolean | null, ckBetaCapUsdCents: bigint | null): Promise<void>;
    appealDispute(disputeId: DisputeId, reason: string): Promise<Result>;
    assignJurors(disputeId: DisputeId): Promise<Result>;
    banUser(target: UserId, reason: string): Promise<void>;
    bumpListing(id: ListingId): Promise<Result>;
    buyerCancelBeforeShipment(tradeId: TradeId): Promise<Result_34>;
    calculateShippingCost(senderCity: string, recipientCity: string, weightKg: number, serviceType: ShippingServiceType): Promise<{
        __kind__: "ok";
        ok: {
            transitDays: bigint;
            costUAH: bigint;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
    canConfirmDelivery(tradeId: TradeId): Promise<boolean>;
    castJurorVote(disputeId: DisputeId, vote: JurorVoteChoice, reasoning: string): Promise<Result>;
    checkAndExpireTimeouts(): Promise<bigint>;
    checkAndReleaseListingStakeAfterClaim(listingId: ListingId, tradeId: TradeId): Promise<Result_15>;
    checkDigitalInspectionDeadline(tradeId: TradeId): Promise<Result_15>;
    checkFulfillmentDeadlines(): Promise<{
        disputeL1Escalations: bigint;
        digitalAutoCompletions: bigint;
        autoCompletions: bigint;
        shipByEscalations: bigint;
    }>;
    checkHandshakeTimeouts(): Promise<bigint>;
    checkJuryDeadlines(): Promise<bigint>;
    checkPaymentIntentExpiry(): Promise<bigint>;
    cleanupResolvedListings(): Promise<{
        deletedCount: bigint;
        skippedByDispute: bigint;
        photosToDelete: Array<string>;
    }>;
    closeProposal(proposalId: ProposalId): Promise<Result_33>;
    confirmBuyerReceipt(tradeId: TradeId): Promise<Result>;
    confirmPaymentReceived(tradeId: TradeId): Promise<Result>;
    confirmPaymentSent(tradeId: TradeId): Promise<Result>;
    confirmSellerHandshake(tradeId: TradeId): Promise<Result>;
    createListing(title: string, description: string, category: ListingCategory, categoryId: CategoryId | null, priceAmount: bigint, priceToken: TradeToken, condition: ItemCondition, photos: Array<string>, location: string, shippingMethods: Array<ShippingMethod>, isDigital: boolean, digitalFileUrl: string | null, digitalFileHash: string | null, digitalPassword: string | null, packageDetails: PackageDetails | null, novaPoshtaConfig: NovaPoshtaConfig | null, ukrposhtaConfig: UkrposhtaConfig | null, meestConfig: MeestConfig | null, attributes: Array<CategoryAttributeValue>): Promise<Result_32>;
    createMeestTTN(tradeId: TradeId): Promise<Result_11>;
    createMeestWaybill(senderCity: string, recipientCity: string, weightKg: number, description: string, cost: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createNovaPoshtaTTN(tradeId: TradeId): Promise<Result_11>;
    createPaymentIntent(tradeId: TradeId, walletLinkId: bigint | null, path: PaymentSettlementPath): Promise<Result_31>;
    createProposal(proposalType: ProposalType, description: string): Promise<Result_30>;
    createUkrPoshtaWaybill(senderCity: string, recipientCity: string, weightKg: number, description: string, cost: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createUkrposhtaTTN(tradeId: TradeId): Promise<Result_11>;
    createWaybill(senderCity: string, recipientCity: string, weightKg: number, description: string, cost: bigint, serviceType: ShippingServiceType): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deactivateListing(id: ListingId): Promise<Result>;
    declineSellerHandshake(tradeId: TradeId): Promise<Result>;
    deleteMyAccount(confirmation: string): Promise<Result>;
    deleteSavedSearch(id: SavedSearchId): Promise<Result>;
    demoteFromModerator(target: UserId): Promise<void>;
    depositStake(token: TradeToken, amount: bigint): Promise<Result>;
    escalateDisputeToL2(disputeId: DisputeId): Promise<Result>;
    estimateTokenAmount(usdCents: bigint, token: TradeToken): Promise<bigint | null>;
    executeProposal(proposalId: ProposalId): Promise<Result>;
    exportMyAccountData(): Promise<AccountExportBundle>;
    getAllUsers(page: bigint, pageSize: bigint, filter: UserFilter): Promise<PagedResult_1>;
    getAuditLog(page: bigint, pageSize: bigint, filter: AuditFilter): Promise<PagedResult>;
    getCachedRate(token: TradeToken): Promise<RateCacheEntry | null>;
    getCategoryAttributeSchema(categoryId: CategoryId): Promise<Array<CategoryAttributeField>>;
    getComplianceNotes(target: UserId): Promise<Array<ComplianceNote>>;
    getCyclesStatus(): Promise<CyclesStatus>;
    getDashboardMetrics(): Promise<PlatformMetrics__1>;
    getDigitalDelivery(tradeId: TradeId): Promise<Result_29>;
    getDispute(disputeId: DisputeId): Promise<DisputeView | null>;
    getDisputeJurors(disputeId: DisputeId): Promise<JuryView | null>;
    getDisputesByTrade(tradeId: TradeId): Promise<Array<DisputeView>>;
    getEndpointErrorRate(endpoint: string, windowHours: bigint): Promise<number>;
    getErrorLog(limit: bigint, severityFilter: string | null): Promise<Array<ErrorLogEntry>>;
    getExecutionHistory(): Promise<Array<ProposalView>>;
    getExpiredListings(offset: bigint, limit: bigint): Promise<Array<ListingCard>>;
    getExplorerApiKeyStatus(): Promise<{
        bscScanConfigured: boolean;
        infuraConfigured: boolean;
        tronGridConfigured: boolean;
    }>;
    getFavoriteListings(): Promise<Array<ListingCard>>;
    getFeedbackForTrade(tradeId: TradeId): Promise<Array<Feedback>>;
    getInsurancePayoutRequest(payoutId: bigint): Promise<PayoutRequestView | null>;
    getInsuranceProtectionView(tradeAmount: bigint, tradeToken: TradeToken): Promise<ProtectionView>;
    getInsuranceReserveLedger(): Promise<ReserveLedgerView>;
    getJurorDashboard(): Promise<Array<JurorDashboardEntry>>;
    getJuryPool(): Promise<Result_28>;
    getLinkPreview(url: string): Promise<Result_27>;
    getLinkedWallets(): Promise<Array<LinkedExternalWallet>>;
    getLinkedWalletsForToken(token: TradeToken): Promise<Array<LinkedExternalWallet>>;
    getListing(id: ListingId): Promise<ListingCard | null>;
    getListingInquiryMessages(listingId: ListingId, buyerPrincipal: UserId): Promise<Result_26>;
    getListingStake(listingId: ListingId): Promise<ListingStakeView | null>;
    getListingsByUser(userId: UserId, offset: bigint, limit: bigint): Promise<Array<ListingCard>>;
    getMeestPUDOs(cityName: string, searchString: string | null, limit: bigint | null): Promise<Result_25>;
    getMetricsSummary(): Promise<MetricsSummary>;
    getModeratorThread(tradeId: TradeId): Promise<Array<Message>>;
    getModuleMetrics(): Promise<Array<ModuleMetricsView>>;
    getMyDisputes(): Promise<Array<DisputeView>>;
    getMyFeedback(): Promise<Array<Feedback>>;
    getMyJurorDashboard(): Promise<Result_24>;
    getMyListings(offset: bigint, limit: bigint): Promise<Array<ListingCard>>;
    getMyPaymentMethods(): Promise<Array<PaymentMethod>>;
    getMyProfile(): Promise<UserProfile | null>;
    getMyStakeBalance(token: TradeToken): Promise<StakeBalanceView>;
    getMyTrades(role: Variant_all_seller_buyer): Promise<Array<TradeView>>;
    getMyTransactionHistory(filter: TxHistoryFilter, offset: bigint, limit: bigint): Promise<Page>;
    getNovaPoshtaBranches(cityName: string, searchString: string | null, limit: bigint | null): Promise<Result_23>;
    getNovaPoshtaCityRef(cityName: string): Promise<Result_11>;
    getOpenDisputeQueue(offset: bigint, limit: bigint): Promise<Result_22>;
    getP95Latency(endpoint: string, windowHours: bigint): Promise<bigint>;
    getPaymentMethods(): Promise<Array<PaymentMethod>>;
    getPaymentVerificationStatus(tradeId: TradeId): Promise<PaymentVerificationResult | null>;
    getPlatformFlags(): Promise<{
        ckUsdcLedgerId: string;
        ckUsdtLedgerId: string;
        trustlessEscrowEnabled: boolean;
    }>;
    getPlatformMetrics(): Promise<PlatformMetrics>;
    getProposal(proposalId: ProposalId): Promise<ProposalView | null>;
    getProposals(statusFilter: ProposalStatus | null): Promise<Array<ProposalView>>;
    getPublicListingsByUser(userId: UserId, offset: bigint, limit: bigint): Promise<Array<ListingCard>>;
    getRequestRate(endpoint: string, windowHours: bigint): Promise<bigint>;
    getRequiredListingStake(priceAmount: bigint, token: TradeToken): Promise<bigint>;
    getSavedSearches(): Promise<Array<SavedSearch>>;
    getSellerFaultSettlementView(tradeId: TradeId): Promise<SellerFaultSettlementView | null>;
    getSellerLiability(p: Principal): Promise<Result_21>;
    getSellerPaymentMethodsForTrade(tradeId: TradeId): Promise<Array<PaymentMethod>>;
    getShippingOptions(weight: number, fromCity: string, toCity: string): Promise<{
        __kind__: "ok";
        ok: Array<ShippingOption>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getStakeOnChainEnabled(): Promise<boolean>;
    getSupportedCarriers(): Promise<Array<CarrierInfo>>;
    getSupportedTokens(): Promise<Array<TokenInfo>>;
    getSystemSettings(): Promise<{
        maxListingPriceUSD: bigint;
        paymentTimeoutHours: bigint;
        allowedTokens: Array<TradeToken>;
        cyclesBalanceThreshold: bigint;
        minTradeAmountUSD: bigint;
        errorRateThreshold: number;
    }>;
    getTokenInfo(token: TradeToken): Promise<TokenInfo | null>;
    getTrade(tradeId: TradeId): Promise<TradeView | null>;
    getTradeFeeQuote(listingId: ListingId): Promise<TradeFeeQuote | null>;
    getTradeMessages(tradeId: TradeId, offset: bigint, limit: bigint): Promise<Array<Message>>;
    getTradeNotifications(): Promise<Array<NotificationEvent>>;
    getTradePaymentStatus(tradeId: TradeId): Promise<TradePaymentStatus | null>;
    getTradesByListing(listingId: ListingId): Promise<Array<TradeView>>;
    getTradesPerDay(days: bigint): Promise<Array<{
        date: string;
        count: bigint;
    }>>;
    getTreasuryBalance(): Promise<bigint>;
    getTreasuryWithdrawals(): Promise<Array<WithdrawalRecord>>;
    getUkrposhtaOffices(cityName: string, searchString: string | null, limit: bigint | null): Promise<Result_20>;
    getUnifiedTrackingInfo(tradeId: TradeId): Promise<Result_19>;
    getUnreadCount(): Promise<Array<[TradeId, bigint]>>;
    getUserFeedback(userId: UserId): Promise<Array<Feedback>>;
    getUserProfile(userId: Principal): Promise<UserProfile | null>;
    getUserReputationStats(userId: UserId): Promise<ReputationStats | null>;
    getVaultAddresses(): Promise<Array<VaultAddressView>>;
    getVaultBalance(chain: ChainType): Promise<BalanceView | null>;
    incrementListingView(id: ListingId): Promise<void>;
    initiateOnChainTrade(tradeId: TradeId): Promise<Result_18>;
    initiateTrade(listingId: ListingId, token: TradeToken, shippingSelection: ShippingSelection | null): Promise<Result_18>;
    isListingFavorite(listingId: ListingId): Promise<boolean>;
    leaveFeedback(tradeId: TradeId, reviewed: UserId, rating: bigint, comment: string): Promise<Result_17>;
    linkExternalWallet(challengeId: bigint, signatureHex: string, signedMessage: string): Promise<Result_14>;
    listCategories(): Promise<Array<CategoryNode>>;
    markAllNotificationsRead(): Promise<Result>;
    markNotificationRead(notificationId: bigint): Promise<Result>;
    markShipped(tradeId: TradeId, ttn: string): Promise<Result>;
    markTradeAsRead(tradeId: TradeId): Promise<void>;
    openDigitalDispute(tradeId: TradeId, reason: string): Promise<Result_16>;
    openDispute(tradeId: TradeId, reason: DisputeReason, description: string, evidencePack: DisputeEvidencePack): Promise<Result_16>;
    platformFeeBps(): Promise<bigint>;
    processDisputeSlaEscalations(): Promise<bigint>;
    promoteToModerator(target: UserId): Promise<void>;
    proposeCancelTrade(tradeId: TradeId): Promise<Result_15>;
    publishListing(listingId: ListingId): Promise<Result>;
    reactivateListing(id: ListingId): Promise<Result>;
    recordRequest(endpoint: string, durationMs: bigint, status: bigint): Promise<void>;
    recordTreasuryFee(tradeId: TradeId, amount: bigint, token: TradeToken): Promise<void>;
    recoverWalletLink(challengeId: bigint, signatureHex: string, signedMessage: string): Promise<Result_14>;
    refreshRates(): Promise<bigint>;
    refreshVaultBalance(chain: ChainType): Promise<BalanceView>;
    registerAsJuror(stake: number): Promise<Result>;
    registerDigitalFile(listingId: ListingId, blobHash: string, mimeType: string, sizeBytes: bigint, blobUrl: string, dekHex: string, contentHash: string | null): Promise<Result_13>;
    releaseListingStake(listingId: ListingId): Promise<Result_9>;
    removeFavorite(listingId: ListingId): Promise<Result>;
    removeListingByAdmin(listingId: ListingId, reason: string): Promise<void>;
    reopenDispute(disputeId: DisputeId): Promise<Result>;
    reportListing(listingId: ListingId, reason: string): Promise<Result>;
    requestRefund(tradeId: TradeId): Promise<Result>;
    requestWalletLinkNonce(chain: WalletChain, address: string, purpose: WalletLinkPurpose, sessionId: string): Promise<Result_12>;
    resolveDispute(disputeId: DisputeId, outcome: ResolutionOutcome, notes: string): Promise<Result>;
    resolveDisputeEscrow(disputeId: DisputeId, outcome: ResolutionOutcome): Promise<Result>;
    retryMeestTTNCreation(tradeId: TradeId): Promise<Result_11>;
    retryPendingOnChainSettlements(): Promise<{
        attempted: bigint;
        failed: bigint;
        succeeded: bigint;
    }>;
    retryTTNCreation(tradeId: TradeId): Promise<Result_11>;
    retryUkrposhtaTTNCreation(tradeId: TradeId): Promise<Result_11>;
    /**
     * / This canister's own principal — used as the escrow recipient in ICRC-2 transfers.
     */
    saveSearch(name: string, paramsJson: string): Promise<Result_10>;
    searchListings(query: string | null, category: ListingCategory | null, categoryId: CategoryId | null, priceMin: bigint | null, priceMax: bigint | null, location: string | null, condition: ItemCondition | null, shippingCarrier: ShippingCarrier | null, offset: bigint, limit: bigint, priceToken: TradeToken | null): Promise<Array<ListingCard>>;
    seizeListingStake(listingId: ListingId, reason: string | null): Promise<Result_9>;
    sendListingInquiry(listingId: ListingId, content: string): Promise<Result_8>;
    sendListingInquiryReply(listingId: ListingId, buyerPrincipal: UserId, content: string): Promise<Result_8>;
    sendMessage(tradeId: TradeId, content: string, attachments: Array<MediaAttachment>): Promise<Result_7>;
    setAvalancheApiKey(apiKey: string): Promise<void>;
    setBscScanApiKey(apiKey: string): Promise<void>;
    setDisputeUnderReview(disputeId: DisputeId): Promise<Result>;
    setInfuraApiKey(apiKey: string): Promise<void>;
    setMeestApiKey(apiKey: string): Promise<void>;
    setMyProfile(username: string, bio: string, avatarUrl: string, email: string | null): Promise<Result_6>;
    setNovaPoshtaApiKey(apiKey: string): Promise<void>;
    setPolygonApiKey(apiKey: string): Promise<void>;
    setSavedSearchAlerts(id: SavedSearchId, enabled: boolean): Promise<Result>;
    setSolanaRpcUrl(url: string): Promise<void>;
    setTronGridApiKey(apiKey: string): Promise<void>;
    setUkrPoshtaApiKey(apiKey: string): Promise<void>;
    snapshotPayoutWallet(tradeId: TradeId, walletLinkId: bigint): Promise<Result_5>;
    submitJurorVote(disputeId: DisputeId, vote: JurorVoteChoice, reasoning: string): Promise<Result>;
    suspendUser(target: UserId, until: Timestamp, reason: string): Promise<void>;
    trackMeestShipment(trackingNumber: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    trackShipment(trackingNumber: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    trackUkrPoshtaShipment(barcode: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    tradeCapTierCheck(listingId: ListingId, tradeToken: TradeToken): Promise<TradeCapTierCheck>;
    transformJsonRpcResponse(args: {
        context: Uint8Array;
        response: HttpResponse;
    }): Promise<HttpResponse>;
    transformPaymentResponse(raw: {
        context: Uint8Array;
        response: HttpResponse;
    }): Promise<HttpResponse>;
    transformShippingResponse(raw: {
        context: Uint8Array;
        response: ShipHttpResponse;
    }): Promise<ShipHttpResponse>;
    transformVaultResponse(raw: {
        context: Uint8Array;
        response: VaultHttpResponse;
    }): Promise<VaultHttpResponse>;
    unbanUser(target: UserId): Promise<void>;
    unlinkExternalWallet(walletLinkId: bigint): Promise<Result>;
    unregisterJuror(): Promise<Result>;
    updateListing(id: ListingId, title: string, description: string, category: ListingCategory, categoryId: CategoryId | null, priceAmount: bigint, priceToken: TradeToken, condition: ItemCondition, photos: Array<string>, location: string, shippingMethods: Array<ShippingMethod>, digitalFileUrl: string | null, digitalFileHash: string | null, digitalPassword: string | null, packageDetails: PackageDetails | null, novaPoshtaConfig: NovaPoshtaConfig | null, ukrposhtaConfig: UkrposhtaConfig | null, meestConfig: MeestConfig | null, attributes: Array<CategoryAttributeValue>): Promise<Result>;
    updateSystemSettings(minTradeAmountUSD: bigint, paymentTimeoutHours: bigint, allowedTokens: Array<TradeToken>, maxListingPriceUSD: bigint, cyclesBalanceThreshold: bigint, errorRateThreshold: number): Promise<void>;
    verifyEvmAddress(address: string, network: string): Promise<Result_1>;
    verifyPayment(tradeId: TradeId, txHash: string, network: TradeToken): Promise<Result_2>;
    verifySolanaAddress(address: string): Promise<Result_1>;
    verifyTradePayment(tradeId: TradeId, txHash: string, network: string): Promise<Result_2>;
    verifyTradePaymentExplorer(tradeId: TradeId, txHash: string, network: TradeToken): Promise<Result_2>;
    verifyTronAddress(address: string): Promise<Result_1>;
    voteOnProposal(proposalId: ProposalId, voteYes: boolean): Promise<Result>;
    withdrawStake(token: TradeToken, amount: bigint): Promise<Result>;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export declare function createActor(canisterId: string, optionsOrUploadFile?: CreateActorOptions | unknown, downloadFile?: unknown, actorOptions?: CreateActorOptions): backendInterface;
